-- PAWU V8.2.0-B4
-- 보호자 입원 경과 공유
-- 기존 데이터 삭제 없음

begin;

create table if not exists public.hospitalization_guardian_updates (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  hospitalization_id bigint not null references public.hospitalizations(id) on delete cascade,
  pet_id bigint references public.pets(id) on delete set null,
  guardian_user_id uuid references auth.users(id) on delete set null,
  category text not null default 'general' check (category in ('general','meal','medication','condition','procedure','discharge')),
  title text not null,
  message text not null,
  image_url text,
  published_at timestamptz not null default now(),
  retracted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hospitalization_guardian_updates_hospitalization_idx
  on public.hospitalization_guardian_updates(hospitalization_id, published_at desc);

create index if not exists hospitalization_guardian_updates_guardian_idx
  on public.hospitalization_guardian_updates(guardian_user_id, published_at desc)
  where retracted_at is null;

commit;
