begin;

create table if not exists public.ai_medical_drafts (
  id bigint generated by default as identity primary key,
  medical_record_id bigint not null references public.medical_records(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint references public.pets(id) on delete set null,
  guardian_summary text not null default '',
  care_instructions text not null default '',
  medication_instructions text not null default '',
  warning_signs text not null default '',
  next_visit_recommendation text not null default '',
  status text not null default 'draft' check (status in ('draft','approved')),
  provider text not null default 'template' check (provider in ('template','openai')),
  model text,
  generated_by uuid references auth.users(id) on delete set null,
  generated_at timestamptz not null default now(),
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists ai_medical_drafts_record_uidx
  on public.ai_medical_drafts(medical_record_id);
create index if not exists ai_medical_drafts_hospital_updated_idx
  on public.ai_medical_drafts(hospital_id, updated_at desc);

alter table public.ai_medical_drafts enable row level security;

drop policy if exists "hospital members read ai medical drafts" on public.ai_medical_drafts;
create policy "hospital members read ai medical drafts"
on public.ai_medical_drafts for select to authenticated
using (
  exists (select 1 from public.hospital_staff hs where hs.user_id = auth.uid() and hs.hospital_id = ai_medical_drafts.hospital_id and hs.is_active = true)
  or exists (select 1 from public.hospital_admins ha where ha.user_id = auth.uid() and ha.hospital_id = ai_medical_drafts.hospital_id)
);

grant select on public.ai_medical_drafts to authenticated;
grant all on public.ai_medical_drafts to service_role;
grant usage, select on sequence public.ai_medical_drafts_id_seq to service_role;

commit;
