begin;

create table if not exists public.ai_pet_memory_snapshots (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  source_record_id bigint references public.medical_records(id) on delete set null,
  overview text not null default '',
  timeline jsonb not null default '[]'::jsonb,
  patterns jsonb not null default '[]'::jsonb,
  cautions jsonb not null default '[]'::jsonb,
  record_count integer not null default 0 check (record_count >= 0),
  provider text not null default 'template' check (provider in ('template','openai')),
  model text,
  generated_by uuid references auth.users(id) on delete set null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, pet_id)
);

create index if not exists ai_pet_memory_hospital_updated_idx
  on public.ai_pet_memory_snapshots (hospital_id, updated_at desc);
create index if not exists ai_pet_memory_pet_idx
  on public.ai_pet_memory_snapshots (pet_id);
create index if not exists medical_records_pet_history_idx
  on public.medical_records (hospital_id, pet_id, created_at desc);

alter table public.ai_pet_memory_snapshots enable row level security;

comment on table public.ai_pet_memory_snapshots is
  'PAWU V9.1 의료진용 과거 진료기록 정리 스냅샷. 서비스 역할 API를 통해서만 접근하며 보호자에게 직접 공개하지 않는다.';

commit;
