begin;

create table if not exists public.beta_announcements (
  id bigint generated by default as identity primary key,
  hospital_id bigint references public.hospitals(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 160),
  content text not null check (char_length(content) between 2 and 10000),
  level text not null default 'info' check (level in ('info','maintenance','warning','critical')),
  is_published boolean not null default false,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.beta_feedback (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  reporter_user_id uuid references auth.users(id) on delete set null,
  reporter_email text,
  category text not null check (category in ('bug','improvement','question','data','other')),
  severity text not null default 'normal' check (severity in ('low','normal','high','critical')),
  title text not null check (char_length(title) between 2 and 120),
  description text not null check (char_length(description) between 5 and 5000),
  page_url text,
  browser_info text,
  status text not null default 'received' check (status in ('received','reviewing','planned','resolved','closed')),
  operator_note text,
  assigned_to uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists beta_announcements_active_idx on public.beta_announcements (is_published, published_at desc);
create index if not exists beta_announcements_hospital_idx on public.beta_announcements (hospital_id, published_at desc);
create index if not exists beta_feedback_hospital_created_idx on public.beta_feedback (hospital_id, created_at desc);
create index if not exists beta_feedback_status_severity_idx on public.beta_feedback (status, severity, created_at desc);

alter table public.beta_announcements enable row level security;
alter table public.beta_feedback enable row level security;

-- 서비스 역할을 사용하는 서버 API에서만 쓰기/전체 조회합니다.
-- 브라우저 직접 접근은 차단해 병원 간 의견 노출을 방지합니다.

grant select, insert, update, delete on public.beta_announcements to service_role;
grant select, insert, update, delete on public.beta_feedback to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.beta_announcements (title, content, level, is_published)
select 'PAWU 베타 운영센터가 열렸습니다', '오류나 개선 의견을 베타 운영센터에서 접수해 주세요. 진료정보와 개인정보는 입력하지 말아 주세요.', 'info', true
where not exists (select 1 from public.beta_announcements where title = 'PAWU 베타 운영센터가 열렸습니다');

commit;
