-- PAWU V9.5.0 System Monitor & Operational Stabilization
create table if not exists public.system_health_snapshots (
  id bigint generated by default as identity primary key,
  overall_status text not null check (overall_status in ('ok', 'warning', 'error')),
  app_version text not null,
  response_time_ms integer not null default 0,
  process_memory_mb integer,
  process_uptime_seconds integer,
  checks jsonb not null default '[]'::jsonb,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists system_health_snapshots_checked_at_idx
  on public.system_health_snapshots (checked_at desc);
create index if not exists system_health_snapshots_status_checked_idx
  on public.system_health_snapshots (overall_status, checked_at desc);

alter table public.system_health_snapshots enable row level security;

-- 서비스 역할만 기록/조회하도록 공개 정책은 만들지 않습니다.
comment on table public.system_health_snapshots is
  'PAWU 서버 상태 정기 점검 기록. PAWU_CRON_SECRET로 보호된 heartbeat API가 저장합니다.';

-- 90일이 지난 상세 스냅샷 정리용 함수. Supabase Cron에서 하루 1회 호출 가능.
create or replace function public.cleanup_old_system_health_snapshots()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.system_health_snapshots
  where checked_at < now() - interval '90 days';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
revoke all on function public.cleanup_old_system_health_snapshots() from public, anon, authenticated;
