"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Schedule = { id: number; scheduled_time: string };
type Prescription = { id:number; medication_name:string; dosage:string|null; route:string|null; instructions:string|null; start_date:string|null; end_date:string|null; medical_prescription_schedules:Schedule[]|null };
type ReservationRow = { id:number; pet_name:string|null; pets:{name:string}|{name:string}[]|null; medical_records:{id:number;medical_prescriptions:Prescription|Prescription[]|null}|{id:number;medical_prescriptions:Prescription|Prescription[]|null}[]|null };
type DoseLog = { id:number; medical_prescription_id:number; scheduled_date:string; scheduled_time:string; status:"pending"|"taken"|"skipped"; taken_at:string|null };
type Dose = { key:string; prescriptionId:number; medicationName:string; dosage:string; petName:string; date:string; time:string; route:string; instructions:string; status:"pending"|"taken"|"skipped" };
type AlertSettings = { is_enabled:boolean; pre_alert_minutes:number; retry_alert_minutes:number; retry_enabled:boolean };
const DEFAULT_SETTINGS: AlertSettings = { is_enabled:true, pre_alert_minutes:10, retry_alert_minutes:30, retry_enabled:true };
function one<T>(v:T|T[]|null|undefined):T|null{return Array.isArray(v)?v[0]??null:v??null}
function many<T>(v:T|T[]|null|undefined):T[]{return Array.isArray(v)?v:v?[v]:[]}
function dateText(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function label(s:Dose["status"]){return s==="taken"?"복용 완료":s==="skipped"?"건너뜀":"복용 예정"}

export default function MedicationsPage(){
 const [userId,setUserId]=useState(""); const [rows,setRows]=useState<ReservationRow[]>([]); const [logs,setLogs]=useState<DoseLog[]>([]); const [settings,setSettings]=useState(DEFAULT_SETTINGS); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [permission,setPermission]=useState<NotificationPermission|"unsupported">("default");
 const today=useMemo(()=>new Date(),[]), start=dateText(today), end=dateText(addDays(today,6));
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage("로그인이 필요합니다.");return}setUserId(user.id);const [r,l,s]=await Promise.all([
  supabase.from("reservations").select(`id,pet_name,pets(name),medical_records(id,medical_prescriptions(id,medication_name,dosage,route,instructions,start_date,end_date,medical_prescription_schedules(id,scheduled_time)))`).eq("user_id",user.id).eq("status","completed").order("reservation_date",{ascending:false}),
  supabase.from("medication_dose_logs").select("id,medical_prescription_id,scheduled_date,scheduled_time,status,taken_at").eq("user_id",user.id).gte("scheduled_date",start).lte("scheduled_date",end),
  supabase.from("medication_notification_settings").select("is_enabled,pre_alert_minutes,retry_alert_minutes,retry_enabled").eq("user_id",user.id).maybeSingle()
 ]);if(r.error)throw r.error;if(l.error)throw l.error;setRows((r.data as ReservationRow[]|null)??[]);setLogs((l.data as DoseLog[]|null)??[]);if(s.data)setSettings(s.data as AlertSettings)}catch(e){setMessage(e instanceof Error?e.message:"복약 일정을 불러오지 못했습니다.")}finally{setLoading(false)}},[start,end]);
 useEffect(()=>{void load();setPermission(typeof Notification==="undefined"?"unsupported":Notification.permission)},[load]);
 const doses=useMemo(()=>{const map=new Map(logs.map(x=>[`${x.medical_prescription_id}-${x.scheduled_date}-${String(x.scheduled_time).slice(0,5)}`,x]));const out:Dose[]=[];for(const r of rows){const petName=one(r.pets)?.name??r.pet_name??"반려동물";for(const mr of many(r.medical_records))for(const p of many(mr.medical_prescriptions)){if(!p.start_date||!p.end_date)continue;for(let day=0;day<7;day++){const date=dateText(addDays(today,day));if(date<p.start_date||date>p.end_date)continue;for(const sc of p.medical_prescription_schedules??[]){const time=String(sc.scheduled_time).slice(0,5),key=`${p.id}-${date}-${time}`,log=map.get(key);out.push({key,prescriptionId:p.id,medicationName:p.medication_name,dosage:p.dosage??"용량 미입력",petName,date,time,route:p.route??"투여 경로 미입력",instructions:p.instructions??"별도의 복약 안내가 없습니다.",status:log?.status??"pending"})}}}}return out.sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`))},[rows,logs,today]);
 const todayDoses=doses.filter(d=>d.date===start),done=todayDoses.filter(d=>d.status==="taken").length,rate=todayDoses.length?Math.round(done/todayDoses.length*100):0;
 async function updateDose(d:Dose,status:Dose["status"]){if(!userId)return;const {error}=await supabase.from("medication_dose_logs").upsert({user_id:userId,medical_prescription_id:d.prescriptionId,scheduled_date:d.date,scheduled_time:`${d.time}:00`,status,taken_at:status==="taken"?new Date().toISOString():null,updated_at:new Date().toISOString()},{onConflict:"user_id,medical_prescription_id,scheduled_date,scheduled_time"});if(error)setMessage(error.message);else void load()}
 async function saveSettings(next:AlertSettings){setSettings(next);if(!userId)return;const {error}=await supabase.from("medication_notification_settings").upsert({user_id:userId,...next,updated_at:new Date().toISOString()});if(error)setMessage(error.message);else setMessage("복약 알림 설정을 저장했습니다.")}
 async function allow(){if(typeof Notification==="undefined")return setPermission("unsupported");setPermission(await Notification.requestPermission())}
 useEffect(()=>{if(permission!=="granted"||!settings.is_enabled)return;const check=()=>{const now=new Date(),current=dateText(now),mins=now.getHours()*60+now.getMinutes();for(const d of doses){if(d.date!==current||d.status!=="pending")continue;const [h,m]=d.time.split(":").map(Number),target=h*60+m,diff=mins-target;const alerts=[{kind:"pre",at:-settings.pre_alert_minutes,title:`💊 ${d.petName} 복약 ${settings.pre_alert_minutes}분 전`},{kind:"now",at:0,title:`💊 ${d.petName} 복약 시간`},...(settings.retry_enabled?[{kind:"retry",at:settings.retry_alert_minutes,title:`⏰ ${d.petName} 복약 확인`}]:[])];for(const a of alerts){if(Math.abs(diff-a.at)>1)continue;const key=`pawu-v108-${a.kind}-${d.key}`;if(localStorage.getItem(key))continue;new Notification(a.title,{body:`${d.medicationName} · ${d.dosage} · ${d.time}`});localStorage.setItem(key,"sent")}}};check();const id=window.setInterval(check,30000);return()=>window.clearInterval(id)},[doses,permission,settings]);
 return <main className="mx-auto w-full max-w-3xl px-4 pb-28 pt-5">
  <section className="rounded-[28px] bg-[#173e35] p-6 text-white"><p className="text-xs font-bold tracking-[.18em] text-white/60">MEDICATION CARE</p><h1 className="mt-2 text-2xl font-bold">복약 일정·알림</h1><p className="mt-2 text-sm text-white/70">병원 처방 시간과 복용 기록, 알림 설정을 한곳에서 관리하세요.</p><div className="mt-5 grid grid-cols-3 gap-2">{[["오늘 일정",todayDoses.length],["복용 완료",done],["복약률",`${rate}%`]].map(([a,b])=><div key={String(a)} className="rounded-2xl bg-white/10 p-3"><p className="text-xs text-white/60">{a}</p><p className="mt-1 text-xl font-bold">{b}</p></div>)}</div></section>
  <section className="mt-4 rounded-3xl border bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">복약 알림 설정</h2><p className="mt-1 text-xs text-slate-500">앱이 열려 있을 때 알림이 동작합니다.</p></div><button onClick={()=>void saveSettings({...settings,is_enabled:!settings.is_enabled})} className={`rounded-full px-4 py-2 text-xs font-bold ${settings.is_enabled?"bg-emerald-100 text-emerald-800":"bg-slate-100"}`}>{settings.is_enabled?"켜짐":"꺼짐"}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">사전 알림<select value={settings.pre_alert_minutes} onChange={e=>void saveSettings({...settings,pre_alert_minutes:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3"><option value={0}>사용 안 함</option><option value={5}>5분 전</option><option value={10}>10분 전</option><option value={30}>30분 전</option></select></label><label className="text-sm font-semibold">미복용 재알림<select value={settings.retry_enabled?settings.retry_alert_minutes:0} onChange={e=>void saveSettings({...settings,retry_enabled:Number(e.target.value)>0,retry_alert_minutes:Number(e.target.value)||30})} className="mt-2 w-full rounded-xl border p-3"><option value={0}>사용 안 함</option><option value={15}>15분 후</option><option value={30}>30분 후</option><option value={60}>60분 후</option></select></label></div>{permission!=="granted"&&<button onClick={()=>void allow()} className="mt-4 w-full rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">앱 알림 허용</button>}</section>
  {message&&<p className="mt-4 rounded-2xl bg-slate-100 p-4 text-sm">{message}</p>}
  <section className="mt-6"><div className="flex justify-between"><h2 className="text-xl font-bold">오늘 복약</h2><span className="text-sm text-slate-500">{start}</span></div><div className="mt-3 space-y-3">{todayDoses.map(d=><article key={d.key} className="rounded-3xl border bg-white p-4"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-slate-500">{d.petName} · {d.time}</p><h3 className="mt-1 text-lg font-bold">{d.medicationName}</h3><p className="text-sm text-slate-600">{d.dosage} · {d.route}</p></div><span className="text-xs font-bold">{label(d.status)}</span></div><p className="mt-3 rounded-2xl bg-slate-50 p-3 text-sm">{d.instructions}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>void updateDose(d,"taken")} className="rounded-2xl bg-[#173e35] p-3 text-sm font-bold text-white">복용 완료</button><button onClick={()=>void updateDose(d,"skipped")} className="rounded-2xl border p-3 text-sm font-bold">건너뛰기</button></div></article>)}{!loading&&!todayDoses.length&&<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-500">오늘 예정된 복약이 없습니다.</div>}{loading&&<div className="p-8 text-center text-sm text-slate-500">불러오는 중입니다.</div>}</div></section>
  <section className="mt-7"><h2 className="text-xl font-bold">다가오는 7일</h2><div className="mt-3 space-y-2">{doses.filter(d=>d.date!==start).map(d=><div key={d.key} className="flex justify-between rounded-2xl border bg-white p-4"><div><p className="text-xs text-slate-400">{d.date} · {d.time}</p><p className="font-bold">{d.petName} · {d.medicationName}</p></div><span className="text-sm">{d.dosage}</span></div>)}</div><Link href="/prescriptions" className="mt-4 inline-flex rounded-full border px-4 py-2 text-sm font-bold">처방전 전체 보기</Link></section>
 </main>
}
