"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "../../../lib/supabase";
import { inventoryAlertLabel,movementLabel,type InventoryAlertType,type InventoryMovementType } from "../../../lib/v6-5-8-inventory-types";

type Item={id:number;name:string;category:string;unit:string;current_quantity:number;minimum_quantity:number;reorder_quantity:number;average_unit_cost:number;storage_location:string|null;management_type:string;regulatory_type:string;};
export default function InventoryPage(){const[data,setData]=useState<any>(null);const[query,setQuery]=useState("");const[filter,setFilter]=useState("전체");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token??""}
async function load(){setBusy(true);const t=await token();if(!t){setBusy(false);return}const r=await fetch("/api/hospital/inventory/overview",{headers:{authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.message??"재고를 불러오지 못했습니다.");return}setData(j.data);setMessage("")}
useEffect(()=>{void load()},[]);const items:Item[]=data?.items??[];const cats=["전체",...new Set(items.map(x=>x.category))];const visible=useMemo(()=>items.filter(x=>(filter==="전체"||x.category===filter)&&x.name.toLowerCase().includes(query.trim().toLowerCase())),[items,filter,query]);
async function resolve(id:number){const t=await token();const r=await fetch("/api/hospital/inventory/alerts",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({id})});if(r.ok)void load()}
return <main className="min-h-screen bg-slate-50 px-5 py-8 text-black"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">PAWU V6.5.8</p><h1 className="text-3xl font-black">재고·약품 관리</h1><p className="mt-2 text-sm text-slate-600">LOT·유효기간·자동 차감·입출고 이력을 병원 단위로 관리합니다.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-2">{busy?"갱신 중":"새로고침"}</button><Link href="/hospital-admin/inventory/new" className="rounded-xl border bg-white px-4 py-2">품목 등록</Link><Link href="/hospital-admin/inventory/movement" className="rounded-xl bg-slate-950 px-4 py-2 font-bold text-white">입고·출고</Link></div></div>{message&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{message}</p>}
<section className="mt-6 grid gap-3 md:grid-cols-5"><Metric t="활성 품목" v={`${data?.counts?.activeItems??0}개`}/><Metric t="안전재고 부족" v={`${data?.counts?.lowStockItems??0}개`} warn/><Metric t="품절" v={`${data?.counts?.outOfStockItems??0}개`} danger/><Metric t="미처리 알림" v={`${data?.counts?.openAlerts??0}건`} warn/><Metric t="추정 재고액" v={`${Number(data?.counts?.estimatedInventoryValue??0).toLocaleString("ko-KR")}원`}/></section>
<section className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="품목명 검색" className="min-w-56 flex-1 rounded-xl border px-4 py-3"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border px-4 py-3">{cats.map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">분류/품목</th><th>현재</th><th>안전/발주</th><th>평균단가</th><th>LOT/규제</th><th>위치</th></tr></thead><tbody>{visible.map(x=>{const low=Number(x.current_quantity)<=Number(x.minimum_quantity);return <tr key={x.id} className="border-t"><td className="p-3"><span className="text-xs text-slate-500">{x.category}</span><div className="font-bold">{x.name}</div></td><td className={low?"font-black text-red-600":"font-bold"}>{x.current_quantity} {x.unit}</td><td>{x.minimum_quantity} / {x.reorder_quantity||0}</td><td>{Number(x.average_unit_cost||0).toLocaleString("ko-KR")}원</td><td>{x.management_type} · {x.regulatory_type||"general"}</td><td>{x.storage_location||"-"}</td></tr>})}</tbody></table>{!visible.length&&<p className="p-8 text-center text-slate-500">조건에 맞는 품목이 없습니다.</p>}</div></div>
<div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><h2 className="font-black">재고 경고</h2><div className="mt-3 max-h-80 space-y-2 overflow-auto">{(data?.alerts??[]).map((a:any)=><article key={a.id} className={`rounded-xl border p-3 ${a.severity==="critical"?"border-red-200 bg-red-50":"border-orange-200 bg-orange-50"}`}><div className="flex justify-between gap-3"><strong>{inventoryAlertLabel[a.alert_type as InventoryAlertType]??a.alert_type}</strong><button onClick={()=>void resolve(a.id)} className="text-xs underline">확인 처리</button></div><p className="mt-1 text-sm">{a.message}</p></article>)}{!data?.alerts?.length&&<p className="text-sm text-slate-500">현재 미처리 경고가 없습니다.</p>}</div></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-black">최근 입출고</h2><div className="mt-3 max-h-80 space-y-2 overflow-auto">{(data?.recentMovements??[]).map((m:any)=><div key={m.id} className="flex justify-between gap-3 border-b py-2 text-sm"><div><strong>{m.inventory_items?.name}</strong><p className="text-xs text-slate-500">{movementLabel[m.movement_type as InventoryMovementType]??m.movement_type} · {m.reason||"사유 없음"}</p></div><span className={Number(m.quantity_change)>0?"font-bold text-blue-600":"font-bold text-red-600"}>{Number(m.quantity_change)>0?"+":""}{m.quantity_change}</span></div>)}</div></section></div></section></div></main>}
function Metric({t,v,warn=false,danger=false}:{t:string;v:string;warn?:boolean;danger?:boolean}){return <article className={`rounded-2xl border p-4 ${danger?"border-red-200 bg-red-50":warn?"border-orange-200 bg-orange-50":"bg-white"}`}><p className="text-xs text-slate-500">{t}</p><p className="mt-1 text-2xl font-black">{v}</p></article>}
