"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { HospitalPage, StatCard } from "../../../components/hospital/HospitalPageUI";
import { supabase } from "../../../lib/supabase";
import type { Admission, AdmissionTask, Bed, DashboardPayload, Surgery } from "../../../lib/v6-5-9-inpatient-surgery-types";

const input = "border border-slate-300 bg-white px-3 py-2 text-sm";
const button = "border border-slate-900 bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40";

export default function InpatientSurgeryPage() {
  const [data, setData] = useState<DashboardPayload>({ beds: [], admissions: [], tasks: [], surgeries: [] });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [bed, setBed] = useState({ name: "", ward: "입원실", bed_type: "general" });
  const [admit, setAdmit] = useState({ patient_name: "", guardian_name: "", guardian_phone: "", bed_id: "", reason: "", expected_discharge_at: "" });
  const [task, setTask] = useState({ admission_id: "", title: "", due_at: "", assignee_name: "" });
  const [surgery, setSurgery] = useState({ patient_name: "", admission_id: "", title: "", surgeon_name: "", operating_room: "수술실 1", scheduled_start: "", scheduled_end: "" });

  const token = useCallback(async () => (await supabase.auth.getSession()).data.session?.access_token ?? "", []);
  const load = useCallback(async () => { const t = await token(); const r = await fetch("/api/hospital/inpatient-surgery/dashboard", { headers: { Authorization: `Bearer ${t}` }, cache: "no-store" }); const j = await r.json(); if (!r.ok) throw new Error(j.error ?? "조회 실패"); setData(j); }, [token]);
  useEffect(() => { load().catch((e: unknown) => setError(e instanceof Error ? e.message : "조회 실패")); }, [load]);
  const act = async (payload: Record<string, unknown>) => { setBusy(true); setError(""); try { const t = await token(); const r = await fetch("/api/hospital/inpatient-surgery/action", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${t}` }, body: JSON.stringify(payload) }); const j = await r.json(); if (!r.ok) throw new Error(j.error ?? "처리 실패"); await load(); } catch (e) { setError(e instanceof Error ? e.message : "처리 실패"); } finally { setBusy(false); } };
  const freeBeds = useMemo(() => data.beds.filter((b: Bed) => b.is_active && !b.occupied), [data.beds]);
  const todayTasks = data.tasks.filter((t: AdmissionTask) => t.status === "pending");

  return <HospitalPage eyebrow="PAWU · BED & SURGERY OPERATIONS" title="병상·수술 운영" description="기존 병상 배정, 처치 일정, 수술 준비 기능을 유지합니다. 환자별 활력징후와 입원 타임라인은 입원 차트에서 관리합니다." actions={<div className="flex flex-wrap gap-2"><Link href="/hospital-admin/inpatients" className="border border-slate-900 bg-white px-4 py-2 text-sm font-bold text-slate-900">입원 차트 열기</Link><button className={button} onClick={() => load()} disabled={busy}>새로고침</button></div>}>
    <section className="grid grid-cols-2 gap-3 py-4 lg:grid-cols-5"><StatCard label="전체 병상" value={`${data.beds.length}개`} /><StatCard label="가용 병상" value={`${freeBeds.length}개`} /><StatCard label="입원 중" value={`${data.admissions.filter((a: Admission) => a.status === "admitted").length}건`} /><StatCard label="미완료 처치" value={`${todayTasks.length}건`} /><StatCard label="예정·진행 수술" value={`${data.surgeries.length}건`} /></section>
    {error && <p className="mb-4 border border-red-300 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
    <section className="grid gap-4 xl:grid-cols-3">
      <div className="border border-slate-300 bg-white p-4"><h2 className="font-black">병상 등록</h2><div className="mt-3 grid gap-2"><input className={input} placeholder="병상명 (예: A-01)" value={bed.name} onChange={e=>setBed({...bed,name:e.target.value})}/><input className={input} placeholder="병동" value={bed.ward} onChange={e=>setBed({...bed,ward:e.target.value})}/><select className={input} value={bed.bed_type} onChange={e=>setBed({...bed,bed_type:e.target.value})}><option value="general">일반</option><option value="icu">중환자</option><option value="isolation">격리</option></select><button className={button} disabled={busy} onClick={()=>act({action:"create_bed",...bed})}>병상 추가</button></div></div>
      <div className="border border-slate-300 bg-white p-4"><h2 className="font-black">입원 접수</h2><div className="mt-3 grid gap-2"><input className={input} placeholder="환자명" value={admit.patient_name} onChange={e=>setAdmit({...admit,patient_name:e.target.value})}/><input className={input} placeholder="보호자명" value={admit.guardian_name} onChange={e=>setAdmit({...admit,guardian_name:e.target.value})}/><input className={input} placeholder="연락처" value={admit.guardian_phone} onChange={e=>setAdmit({...admit,guardian_phone:e.target.value})}/><select className={input} value={admit.bed_id} onChange={e=>setAdmit({...admit,bed_id:e.target.value})}><option value="">병상 선택</option>{freeBeds.map((b: Bed)=><option key={b.id} value={b.id}>{b.ward} · {b.name}</option>)}</select><input className={input} placeholder="입원 사유" value={admit.reason} onChange={e=>setAdmit({...admit,reason:e.target.value})}/><input className={input} type="datetime-local" value={admit.expected_discharge_at} onChange={e=>setAdmit({...admit,expected_discharge_at:e.target.value})}/><button className={button} disabled={busy} onClick={()=>act({action:"admit",...admit})}>입원 및 병상 배정</button></div></div>
      <div className="border border-slate-300 bg-white p-4"><h2 className="font-black">처치 일정 추가</h2><div className="mt-3 grid gap-2"><select className={input} value={task.admission_id} onChange={e=>setTask({...task,admission_id:e.target.value})}><option value="">입원 환자 선택</option>{data.admissions.map((a: Admission)=><option key={a.id} value={a.id}>{a.patient_name} · {a.bed_name}</option>)}</select><input className={input} placeholder="처치 내용" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><input className={input} type="datetime-local" value={task.due_at} onChange={e=>setTask({...task,due_at:e.target.value})}/><input className={input} placeholder="담당자" value={task.assignee_name} onChange={e=>setTask({...task,assignee_name:e.target.value})}/><button className={button} disabled={busy} onClick={()=>act({action:"create_task",...task})}>처치 일정 등록</button></div></div>
    </section>
    <section className="mt-4 grid gap-4 xl:grid-cols-2"><div className="border border-slate-300 bg-white p-4"><h2 className="font-black">입원 현황</h2><div className="mt-3 space-y-2">{data.admissions.length===0?<p className="text-sm text-slate-500">입원 환자가 없습니다.</p>:data.admissions.map((a: Admission)=><div key={a.id} className="flex items-center justify-between border border-slate-200 p-3"><div><b>{a.patient_name}</b><p className="text-xs text-slate-500">{a.bed_name} · {a.reason || "사유 없음"}</p></div><button className="border border-slate-400 px-3 py-1 text-xs font-bold" onClick={()=>act({action:"discharge",admission_id:a.id})}>퇴원</button></div>)}</div></div><div className="border border-slate-300 bg-white p-4"><h2 className="font-black">처치 보드</h2><div className="mt-3 space-y-2">{todayTasks.length===0?<p className="text-sm text-slate-500">대기 중인 처치가 없습니다.</p>:todayTasks.map((t: AdmissionTask)=><div key={t.id} className="flex items-center justify-between border border-slate-200 p-3"><div><b>{t.title}</b><p className="text-xs text-slate-500">{new Date(t.due_at).toLocaleString("ko-KR")} · {t.assignee_name || "미배정"}</p></div><button className="border border-slate-400 px-3 py-1 text-xs font-bold" onClick={()=>act({action:"complete_task",task_id:t.id})}>완료</button></div>)}</div></div></section>
    <section className="mt-4 border border-slate-300 bg-white p-4"><h2 className="font-black">수술 예약</h2><div className="mt-3 grid gap-2 md:grid-cols-4"><input className={input} placeholder="환자명" value={surgery.patient_name} onChange={e=>setSurgery({...surgery,patient_name:e.target.value})}/><input className={input} placeholder="수술명" value={surgery.title} onChange={e=>setSurgery({...surgery,title:e.target.value})}/><input className={input} placeholder="집도의" value={surgery.surgeon_name} onChange={e=>setSurgery({...surgery,surgeon_name:e.target.value})}/><input className={input} placeholder="수술실" value={surgery.operating_room} onChange={e=>setSurgery({...surgery,operating_room:e.target.value})}/><input className={input} type="datetime-local" value={surgery.scheduled_start} onChange={e=>setSurgery({...surgery,scheduled_start:e.target.value})}/><input className={input} type="datetime-local" value={surgery.scheduled_end} onChange={e=>setSurgery({...surgery,scheduled_end:e.target.value})}/><select className={input} value={surgery.admission_id} onChange={e=>setSurgery({...surgery,admission_id:e.target.value})}><option value="">입원 연결 없음</option>{data.admissions.map((a: Admission)=><option key={a.id} value={a.id}>{a.patient_name}</option>)}</select><button className={button} disabled={busy} onClick={()=>act({action:"create_surgery",...surgery})}>수술 예약 등록</button></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.surgeries.map((s: Surgery)=><SurgeryCard key={s.id} surgery={s} act={act} />)}</div></section>
  </HospitalPage>;
}

function SurgeryCard({ surgery:s, act }:{ surgery:Surgery; act:(p:Record<string,unknown>)=>Promise<void> }) { const [checks,setChecks]=useState({consent_confirmed:s.consent_confirmed,fasting_confirmed:s.fasting_confirmed,preop_test_confirmed:s.preop_test_confirmed,anesthesia_confirmed:s.anesthesia_confirmed}); return <div className="border border-slate-300 p-3"><div className="flex justify-between"><div><b>{s.patient_name} · {s.title}</b><p className="text-xs text-slate-500">{new Date(s.scheduled_start).toLocaleString("ko-KR")} · {s.surgeon_name || "집도의 미정"}</p></div><span className="text-xs font-bold">{s.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{([['consent_confirmed','동의서'],['fasting_confirmed','금식'],['preop_test_confirmed','수술 전 검사'],['anesthesia_confirmed','마취 확인']] as const).map(([k,l])=><label key={k}><input type="checkbox" checked={checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/> {l}</label>)}</div><div className="mt-3 flex flex-wrap gap-2">{["ready","in_progress","recovery","completed"].map(st=><button key={st} className="border border-slate-400 px-2 py-1 text-xs font-bold" onClick={()=>act({action:"update_surgery",surgery_id:s.id,status:st,...checks})}>{st}</button>)}</div></div> }
