"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Pet = { id: number; name: string; species: string; breed: string | null };
type Insight = { overview: string; patterns: string[]; weightNote: string | null; upcomingCare: string[]; questionsForVet: string[]; provider: "openai" | "template"; disclaimer: string };

export default function HealthInsightsPage() {
  const [pets, setPets] = useState<Pet[]>([]); const [petId, setPetId] = useState<number | null>(null); const [insight, setInsight] = useState<Insight | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { (async () => { const { data: auth } = await supabase.auth.getSession(); const token = auth.session?.access_token; if (!token) { setError("로그인이 필요합니다."); setLoading(false); return; } const { data } = await supabase.from("pets").select("id,name,species,breed").order("created_at"); const list = (data || []) as Pet[]; setPets(list); if (list[0]) setPetId(list[0].id); else setLoading(false); })(); }, []);
  useEffect(() => { if (!petId) return; (async () => { setLoading(true); setError(""); setInsight(null); const { data } = await supabase.auth.getSession(); const response = await fetch("/api/guardian/health-insights", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${data.session?.access_token || ""}` }, body: JSON.stringify({ petId }) }); const result = await response.json(); if (!response.ok) setError(result.message || "건강 분석을 만들지 못했습니다."); else setInsight(result.insight); setLoading(false); })(); }, [petId]);
  return <main className="min-h-screen bg-[#f7f4ed] pb-24 text-[#153f34]"><div className="mx-auto max-w-5xl px-4 py-7 sm:px-7"><div className="flex justify-between gap-3"><Link href="/health-notebook" className="rounded-full border bg-white px-4 py-2 text-sm font-bold">← 건강 타임라인</Link><Link href="/emergency" className="rounded-full bg-[#e56f5b] px-4 py-2 text-sm font-bold text-white">응급·야간 병원</Link></div><header className="mt-8"><p className="text-xs font-black tracking-[.22em] text-[#e56f5b]">PAWU AI HEALTH</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">AI 건강 기록 요약</h1><p className="mt-3 text-sm leading-6 text-[#667069]">저장된 진료·처방·생활·체중 기록을 읽기 쉽게 정리합니다. 새로운 진단이나 처방은 만들지 않습니다.</p></header>
  {pets.length > 0 && <div className="mt-6 flex gap-2 overflow-x-auto">{pets.map(p => <button key={p.id} onClick={() => setPetId(p.id)} className={`whitespace-nowrap rounded-full px-5 py-3 text-sm font-bold ${petId===p.id?"bg-[#153f34] text-white":"border bg-white"}`}>{p.species==="dog"?"🐶":p.species==="cat"?"🐱":"🐾"} {p.name}</button>)}</div>}
  {error && <div className="mt-6 rounded-3xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>}
  {!loading && !pets.length && <div className="mt-8 rounded-3xl bg-white p-10 text-center"><p className="text-4xl">🐾</p><h2 className="mt-3 text-xl font-black">등록된 아이가 없어요</h2><Link href="/pets/new" className="mt-5 inline-flex rounded-full bg-[#153f34] px-5 py-3 text-sm font-bold text-white">아이 등록하기</Link></div>}
  {loading && <div className="mt-8 rounded-3xl bg-white p-10 text-center text-sm text-[#667069]">건강 기록을 안전하게 정리하고 있어요...</div>}
  {insight && <div className="mt-7 space-y-4"><section className="rounded-[30px] bg-[#153f34] p-6 text-white sm:p-8"><div className="flex items-center justify-between gap-3"><h2 className="text-2xl font-black">한눈에 보기</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{insight.provider==="openai"?"AI 요약":"기록 요약"}</span></div><p className="mt-4 leading-7 text-white/85">{insight.overview}</p></section><Grid title="기록에서 확인된 흐름" icon="🔎" items={insight.patterns}/>{insight.weightNote && <Grid title="체중 변화" icon="⚖️" items={[insight.weightNote]}/>}<Grid title="다가오는 관리" icon="📅" items={insight.upcomingCare}/><Grid title="병원에 물어볼 내용" icon="💬" items={insight.questionsForVet}/><p className="rounded-2xl border border-[#e2d8c8] bg-[#fffaf0] p-4 text-xs leading-5 text-[#766a58]">{insight.disclaimer}</p></div>}
  </div></main>;
}
function Grid({ title, icon, items }: { title: string; icon: string; items: string[] }) { if (!items.length) return null; return <section className="rounded-[28px] border border-[#e1ddd3] bg-white p-6"><h2 className="text-lg font-black">{icon} {title}</h2><ul className="mt-4 space-y-3">{items.map((x,i)=><li key={`${x}-${i}`} className="rounded-2xl bg-[#f5f6f2] p-4 text-sm leading-6">{x}</li>)}</ul></section> }
