"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { HospitalPage, StatCard } from "../../../components/hospital/HospitalPageUI";
import { supabase } from "../../../lib/supabase";
import { invoiceStatusLabel, paymentMethodLabel, type PaymentMethod } from "../../../lib/v6-5-7-billing-types";
type Waiting={id:number;reservation_id:number|null;pet_id:number|null;pet_name:string;guardian_name:string|null;phone:string|null;status:string;waiting_number:number;visit_reason:string|null};
type Catalog={id:number;name:string;category:string;default_price:number;is_favorite:boolean};
type Line={key:string;serviceItemId:number|null;name:string;unitPrice:number;quantity:number;discountAmount:number;additionalAmount:number};
type Pay={key:string;method:PaymentMethod;amount:number;approvalNumber:string};
const money=(v:number)=>`${Number(v||0).toLocaleString("ko-KR")}원`; const today=()=>new Date().toISOString().slice(0,10);
export default function BillingPage(){
 const[date,setDate]=useState(today());const[waiting,setWaiting]=useState<Waiting[]>([]);const[invoices,setInvoices]=useState<any[]>([]);const[catalog,setCatalog]=useState<Catalog[]>([]);const[selected,setSelected]=useState<Waiting|null>(null);const[petId,setPetId]=useState("");const[lines,setLines]=useState<Line[]>([]);const[discount,setDiscount]=useState(0);const[payments,setPayments]=useState<Pay[]>([{key:"p1",method:"card",amount:0,approvalNumber:""}]);const[memo,setMemo]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[lastReceipt,setLastReceipt]=useState<any>(null);
 async function token(){return(await supabase.auth.getSession()).data.session?.access_token??""}async function load(){const t=await token();const r=await fetch(`/api/hospital/billing/dashboard?date=${date}`,{headers:{authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok)return setMessage(j.message);setWaiting(j.waiting??[]);setInvoices(j.invoices??[]);setCatalog(j.catalog??[]);setMessage("");}
 useEffect(()=>{void load()},[date]);
 function choose(w:Waiting){setSelected(w);setPetId(w.pet_id?String(w.pet_id):"");setLines([]);setDiscount(0);setPayments([{key:`p-${Date.now()}`,method:"card",amount:0,approvalNumber:""}]);setMemo("");setLastReceipt(null)}
 function add(c:Catalog){setLines(v=>[...v,{key:`${c.id}-${Date.now()}-${v.length}`,serviceItemId:c.id,name:c.name,unitPrice:c.default_price,quantity:1,discountAmount:0,additionalAmount:0}])}function patchLine(key:string,p:Partial<Line>){setLines(v=>v.map(x=>x.key===key?{...x,...p}:x))}function patchPay(key:string,p:Partial<Pay>){setPayments(v=>v.map(x=>x.key===key?{...x,...p}:x))}
 const subtotal=useMemo(()=>lines.reduce((s,x)=>s+Math.max(0,x.unitPrice*x.quantity-x.discountAmount+x.additionalAmount),0),[lines]);const total=Math.max(0,subtotal-discount);const paid=payments.reduce((s,x)=>s+Math.max(0,x.amount),0);const outstanding=Math.max(0,total-paid);
 async function checkout(){if(!selected)return setMessage("수납할 환자를 선택해 주세요.");if(!Number.isInteger(Number(petId))||Number(petId)<=0)return setMessage("환자 ID를 확인해 주세요.");if(!lines.length)return setMessage("수납 항목을 한 개 이상 추가해 주세요.");setBusy(true);const t=await token();const r=await fetch("/api/hospital/billing/checkout",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({waitingEntryId:selected.id,reservationId:selected.reservation_id,petId:Number(petId),items:lines,invoiceDiscount:discount,payments,memo})});const j=await r.json();setBusy(false);if(!r.ok)return setMessage(j.message);setLastReceipt(j);setMessage(j.outstandingAmount>0?`부분 수납 완료 · 미수금 ${money(j.outstandingAmount)}`:"결제가 완료되었습니다.");await load();}
 const paidToday=invoices.filter(x=>x.status==="paid").reduce((s,x)=>s+Number(x.paid_amount||0),0);const unpaid=invoices.reduce((s,x)=>s+Number(x.outstanding_amount||0),0);
 return <HospitalPage eyebrow="Billing V6.5.7" title="수납 관리" description="진료 항목 계산부터 복합결제·미수금·영수증까지 한 화면에서 처리합니다." actions={<div className="flex gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border px-3 py-2 text-sm"/><button onClick={()=>void load()} className="border bg-white px-4 py-2 text-sm font-bold">새로고침</button><Link href="/hospital-admin/billing/catalog" className="border bg-white px-4 py-2 text-sm font-bold">항목 설정</Link></div>}>
 <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="수납 대기" value={`${waiting.filter(x=>x.status==="billing").length}건`}/><StatCard label="오늘 결제" value={money(paidToday)}/><StatCard label="미수금" value={money(unpaid)}/><StatCard label="영수증" value={`${invoices.filter(x=>x.receipt_number).length}건`}/></section>{message&&<p className={`mt-3 border p-3 text-sm font-bold ${lastReceipt?"border-emerald-300 bg-emerald-50":"border-amber-300 bg-amber-50"}`}>{message}</p>}
 <div className="mt-4 grid gap-4 xl:grid-cols-[320px_1fr_360px]"><section className="border bg-white"><h2 className="border-b p-4 text-lg font-black">수납 대기 환자</h2><div className="max-h-[650px] overflow-auto p-2">{waiting.filter(x=>x.status==="billing").map(w=><button key={w.id} onClick={()=>choose(w)} className={`mb-2 w-full border p-3 text-left ${selected?.id===w.id?"border-slate-900 bg-slate-100":"bg-white"}`}><b>#{w.waiting_number} {w.pet_name}</b><p className="mt-1 text-xs text-slate-500">{w.guardian_name??"보호자 미입력"} · {w.visit_reason??"진료 사유 없음"}</p></button>)}{!waiting.some(x=>x.status==="billing")&&<p className="p-4 text-sm text-slate-500">수납 대기 환자가 없습니다.</p>}</div></section>
 <section className="border bg-white p-4"><div className="flex items-center justify-between"><h2 className="text-lg font-black">진료비 항목</h2><span className="text-sm font-bold">{selected?selected.pet_name:"환자 미선택"}</span></div><label className="mt-3 block text-xs font-bold">환자 ID<input value={petId} onChange={e=>setPetId(e.target.value.replace(/[^0-9]/g,""))} placeholder="현장 환자는 환자 ID 입력" className="mt-1 w-full border p-2"/></label><div className="mt-4 flex flex-wrap gap-2">{catalog.map(c=><button key={c.id} onClick={()=>add(c)} className="border bg-slate-50 px-3 py-2 text-left text-xs"><b>{c.is_favorite?"★ ":""}{c.name}</b><span className="ml-2 text-slate-500">{money(c.default_price)}</span></button>)}</div><div className="mt-4 space-y-2">{lines.map(x=><article key={x.key} className="border p-3"><div className="flex gap-2"><input value={x.name} onChange={e=>patchLine(x.key,{name:e.target.value})} className="min-w-0 flex-1 border p-2 font-bold"/><button onClick={()=>setLines(v=>v.filter(y=>y.key!==x.key))} className="border px-3 text-xs">삭제</button></div><div className="mt-2 grid grid-cols-4 gap-2"><Num label="단가" value={x.unitPrice} set={v=>patchLine(x.key,{unitPrice:v})}/><Num label="수량" value={x.quantity} set={v=>patchLine(x.key,{quantity:Math.max(1,v)})}/><Num label="할인" value={x.discountAmount} set={v=>patchLine(x.key,{discountAmount:v})}/><Num label="추가" value={x.additionalAmount} set={v=>patchLine(x.key,{additionalAmount:v})}/></div></article>)}</div>{!lines.length&&<p className="mt-8 text-center text-sm text-slate-400">위 진료 항목을 눌러 추가하세요.</p>}</section>
 <section className="border bg-white p-4"><h2 className="text-lg font-black">결제</h2><div className="mt-3 border bg-slate-950 p-4 text-white"><Row label="항목 합계" value={money(subtotal)}/><label className="mt-3 block text-xs">전체 할인<input type="number" min={0} value={discount} onChange={e=>setDiscount(Math.max(0,Number(e.target.value)))} className="mt-1 w-full border border-slate-600 bg-white p-2 text-black"/></label><div className="mt-3 border-t border-slate-700 pt-3"><Row label="최종 금액" value={money(total)} strong/></div></div><div className="mt-3 space-y-2">{payments.map(p=><div key={p.key} className="grid grid-cols-[95px_1fr_34px] gap-2"><select value={p.method} onChange={e=>patchPay(p.key,{method:e.target.value as PaymentMethod})} className="border p-2 text-sm">{Object.entries(paymentMethodLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="number" min={0} value={p.amount} onChange={e=>patchPay(p.key,{amount:Math.max(0,Number(e.target.value))})} className="border p-2 text-sm"/><button onClick={()=>setPayments(v=>v.filter(x=>x.key!==p.key))} className="border">×</button>{p.method==="card"&&<input value={p.approvalNumber} onChange={e=>patchPay(p.key,{approvalNumber:e.target.value})} placeholder="카드 승인번호(선택)" className="col-span-3 border p-2 text-xs"/>}</div>)}</div><button onClick={()=>setPayments(v=>[...v,{key:`p-${Date.now()}`,method:"cash",amount:0,approvalNumber:""}])} className="mt-2 w-full border p-2 text-xs font-bold">+ 복합결제 수단 추가</button><div className="mt-3 border p-3 text-sm"><Row label="결제 합계" value={money(paid)}/><Row label="미수금" value={money(outstanding)} strong/></div><textarea value={memo} onChange={e=>setMemo(e.target.value)} placeholder="수납 메모" className="mt-3 w-full border p-3 text-sm"/><button disabled={busy} onClick={()=>void checkout()} className="mt-3 w-full bg-slate-950 p-4 font-black text-white disabled:bg-slate-400">{busy?"처리 중...":"결제 및 수납 완료"}</button>{lastReceipt&&<div className="mt-3 border border-emerald-300 bg-emerald-50 p-3"><p className="text-xs text-slate-500">영수증 번호</p><b>{lastReceipt.receiptNumber}</b><button onClick={()=>window.print()} className="mt-2 w-full border bg-white p-2 text-xs font-bold">영수증 인쇄</button></div>}</section></div>
 <section className="mt-4 border bg-white"><h2 className="border-b p-4 text-lg font-black">오늘 수납 내역</h2><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">영수증</th><th className="p-3">환자</th><th className="p-3">상태</th><th className="p-3 text-right">총액</th><th className="p-3 text-right">결제</th><th className="p-3 text-right">미수</th></tr></thead><tbody>{invoices.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-mono text-xs">{x.receipt_number??"-"}</td><td className="p-3">{Array.isArray(x.pets)?x.pets[0]?.name:x.pets?.name??`#${x.pet_id}`}</td><td className="p-3">{invoiceStatusLabel[x.status as keyof typeof invoiceStatusLabel]??x.status}</td><td className="p-3 text-right">{money(x.total_amount)}</td><td className="p-3 text-right">{money(x.paid_amount)}</td><td className="p-3 text-right font-bold">{money(x.outstanding_amount)}</td></tr>)}</tbody></table></div></section>
 </HospitalPage>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-[10px] font-bold">{label}<input type="number" min={0} value={value} onChange={e=>set(Math.max(0,Number(e.target.value)))} className="mt-1 w-full border p-2 text-xs"/></label>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <p className={`flex justify-between ${strong?"text-lg font-black":""}`}><span>{label}</span><span>{value}</span></p>}
