"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "../../../../lib/supabase";
type Item={id:number;name:string;category:string;default_price:number;description:string|null;species_scope:string;is_favorite:boolean;is_active:boolean};
const categories=["진찰","예방접종","검사","처치","수술","입원","약제","기타"];
export default function CatalogPage(){const[items,setItems]=useState<Item[]>([]);const[name,setName]=useState("");const[category,setCategory]=useState("진찰");const[price,setPrice]=useState("");const[message,setMessage]=useState("");
async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token??""} async function load(){const t=await token();if(!t)return;const r=await fetch("/api/hospital/billing/catalog",{headers:{authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok)setItems(j.items??[]);else setMessage(j.message)} useEffect(()=>{void load()},[]);
async function submit(e:FormEvent){e.preventDefault();const t=await token();const r=await fetch("/api/hospital/billing/catalog",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({name,category,defaultPrice:Number(price),isFavorite:true,speciesScope:"all"})});const j=await r.json();setMessage(r.ok?"등록했습니다.":j.message);if(r.ok){setName("");setPrice("");void load()}}
async function toggle(item:Item,field:"isFavorite"|"isActive"){const t=await token();await fetch("/api/hospital/billing/catalog",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({id:item.id,[field]:field==="isFavorite"?!item.is_favorite:!item.is_active})});void load()}
return <main className="min-h-screen bg-slate-50 px-5 py-8 text-black"><div className="mx-auto max-w-5xl"><div className="flex justify-between"><Link href="/hospital-admin/v5" className="rounded-xl border bg-white px-4 py-2">← V5</Link><Link href="/hospital-admin/billing/new" className="rounded-xl bg-black px-4 py-2 text-white">간편 청구서</Link></div><h1 className="mt-8 text-3xl font-black">자주 쓰는 진료 항목</h1><p className="mt-2 text-sm text-gray-600">금액은 각 병원의 기본 청구 기준이며 실제 청구 시 수정할 수 있습니다.</p>{message&&<p className="mt-4 rounded-xl bg-white p-3">{message}</p>}<form onSubmit={submit} className="mt-6 grid gap-3 rounded-3xl border bg-white p-5 md:grid-cols-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="항목명" className="rounded-xl border p-3"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border p-3">{categories.map(v=><option key={v}>{v}</option>)}</select><input required inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value.replace(/[^0-9]/g,""))} placeholder="기본 금액" className="rounded-xl border p-3"/><button className="rounded-xl bg-black p-3 font-bold text-white">등록</button></form><div className="mt-6 space-y-3">{items.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-4"><div><strong>{item.name}</strong><p className="text-sm text-gray-500">{item.category} · {item.default_price.toLocaleString("ko-KR")}원</p></div><div className="flex gap-2"><button onClick={()=>void toggle(item,"isFavorite")} className="rounded-lg border px-3 py-2 text-sm">{item.is_favorite?"★ 즐겨찾기":"☆ 즐겨찾기"}</button><button onClick={()=>void toggle(item,"isActive")} className="rounded-lg border px-3 py-2 text-sm">{item.is_active?"사용 중":"사용 중지"}</button></div></article>)}</div></div></main>}
