"use client";
import { useEffect, useMemo, useState } from "react";
import { HospitalPage, StatCard } from "../../../components/hospital/HospitalPageUI";
import { supabase } from "../../../lib/supabase";
import { waitingPriorityLabel, waitingStatusLabel, type WaitingStatus } from "../../../lib/v6-5-6-reception-types";

const columns: WaitingStatus[] = ["waiting", "called", "in_consultation", "exam", "billing", "completed"];
function today() { return new Date().toISOString().slice(0, 10); }
function minutes(iso?: string) { return iso ? Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 60000)) : 0; }

export default function ReceptionPage() {
  const [date, setDate] = useState(today()); const [entries, setEntries] = useState<any[]>([]); const [reservations, setReservations] = useState<any[]>([]);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ petName: "", guardianName: "", phone: "", visitReason: "", priority: "normal" });
  async function token() { return (await supabase.auth.getSession()).data.session?.access_token ?? ""; }
  async function load() { const t = await token(); const r = await fetch(`/api/hospital/reception?date=${date}`, { headers: { authorization: `Bearer ${t}` } }); const j = await r.json(); if (!r.ok) return setMessage(j.message); setEntries(j.entries); setReservations(j.reservations); setMessage(""); }
  useEffect(() => { void load(); const id = setInterval(() => void load(), 15000); return () => clearInterval(id); }, [date]);
  async function post(body: any) { setBusy(true); const t = await token(); const r = await fetch("/api/hospital/reception", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${t}` }, body: JSON.stringify({ waitingDate: date, ...body }) }); const j = await r.json(); setBusy(false); if (!r.ok) return setMessage(j.message); setForm({ petName: "", guardianName: "", phone: "", visitReason: "", priority: "normal" }); await load(); }
  async function patch(entry: any, body: any) { const t = await token(); const r = await fetch("/api/hospital/reception", { method: "PATCH", headers: { "content-type": "application/json", authorization: `Bearer ${t}` }, body: JSON.stringify({ id: entry.id, callCount: entry.call_count, ...body }) }); const j = await r.json(); if (!r.ok) return setMessage(j.message); await load(); }
  const count = (s: string) => entries.filter((e) => e.status === s).length;
  const ordered = useMemo(() => [...entries].sort((a,b) => ({emergency:0,urgent:1,normal:2}[a.priority as "emergency"] ?? 2) - ({emergency:0,urgent:1,normal:2}[b.priority as "emergency"] ?? 2) || a.waiting_number-b.waiting_number), [entries]);
  return <HospitalPage eyebrow="Reception & Waiting V6.5.6" title="접수·대기 보드" description="예약 및 현장 환자를 접수하고 대기부터 진료·검사·수납까지 한 화면에서 관리합니다." actions={<div className="flex gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border px-3 py-2 text-sm"/><button onClick={()=>void load()} className="border bg-white px-4 py-2 text-sm font-bold">새로고침</button></div>}>
    <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="전체 접수" value={`${entries.length}건`}/><StatCard label="대기" value={`${count("waiting")}건`}/><StatCard label="호출" value={`${count("called")}건`}/><StatCard label="진료 중" value={`${count("in_consultation")}건`}/><StatCard label="응급" value={`${entries.filter(e=>e.priority==="emergency" && !["completed","cancelled"].includes(e.status)).length}건`}/><StatCard label="완료" value={`${count("completed")}건`}/></section>
    {message && <div className="mt-3 border border-red-300 bg-red-50 p-3 text-sm text-red-700">{message}</div>}
    <section className="mt-4 grid gap-4 xl:grid-cols-2"><div className="border bg-white p-4"><h2 className="font-black">예약 환자 빠른 접수</h2><div className="mt-3 max-h-56 overflow-auto divide-y">{reservations.length===0?<p className="py-4 text-sm text-slate-500">접수 가능한 예약이 없습니다.</p>:reservations.map(r=><div key={r.id} className="flex items-center justify-between gap-3 py-3"><div><b>{(Array.isArray(r.pets)?r.pets[0]?.name:r.pets?.name) ?? r.pet_name}</b><p className="text-xs text-slate-500">{r.reservation_time?.slice(0,5)} · {r.guardian_name} · {r.visit_reason ?? "진료"}</p></div><button disabled={busy} onClick={()=>void post({reservationId:r.id})} className="border border-slate-900 bg-slate-900 px-3 py-2 text-xs font-bold text-white">접수</button></div>)}</div></div>
    <form className="border bg-white p-4" onSubmit={e=>{e.preventDefault();void post(form)}}><h2 className="font-black">현장 접수</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><input required placeholder="환자명 *" value={form.petName} onChange={e=>setForm({...form,petName:e.target.value})} className="border px-3 py-2 text-sm"/><input placeholder="보호자명" value={form.guardianName} onChange={e=>setForm({...form,guardianName:e.target.value})} className="border px-3 py-2 text-sm"/><input placeholder="연락처" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="border px-3 py-2 text-sm"/><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="border px-3 py-2 text-sm"><option value="normal">일반</option><option value="urgent">우선</option><option value="emergency">응급</option></select><input placeholder="내원 사유" value={form.visitReason} onChange={e=>setForm({...form,visitReason:e.target.value})} className="border px-3 py-2 text-sm sm:col-span-2"/></div><button disabled={busy} className="mt-3 w-full bg-slate-900 px-4 py-2 text-sm font-bold text-white">대기번호 발급 및 접수</button></form></section>
    <section className="mt-4 overflow-x-auto"><div className="grid min-w-[1500px] grid-cols-6 gap-3">{columns.map(status=><div key={status} className="border bg-slate-100"><h3 className="border-b bg-white px-3 py-2 text-sm font-black">{waitingStatusLabel[status]} · {count(status)}</h3><div className="space-y-2 p-2">{ordered.filter(e=>e.status===status).map(e=><article key={e.id} className={`border bg-white p-3 ${e.priority==="emergency"?"border-red-500":"border-slate-300"}`}><div className="flex justify-between"><b className="text-lg">#{e.waiting_number} {e.pet_name}</b><span className="text-xs font-bold">{waitingPriorityLabel[e.priority as keyof typeof waitingPriorityLabel]}</span></div><p className="mt-1 text-xs text-slate-500">{e.guardian_name ?? "보호자 미입력"} · 대기 {minutes(e.checked_in_at)}분 · 호출 {e.call_count}회</p><p className="mt-2 text-sm">{e.visit_reason ?? "진료 사유 미입력"}</p><div className="mt-2 grid grid-cols-2 gap-1"><button onClick={()=>void patch(e,{action:"call"})} className="border px-2 py-1 text-xs font-bold">호출</button><select value={e.priority} onChange={x=>void patch(e,{priority:x.target.value})} className="border px-2 py-1 text-xs"><option value="normal">일반</option><option value="urgent">우선</option><option value="emergency">응급</option></select><input defaultValue={e.room_name ?? ""} onBlur={x=>void patch(e,{room_name:x.target.value})} placeholder="진료실" className="border px-2 py-1 text-xs"/><input defaultValue={e.assigned_staff_name ?? ""} onBlur={x=>void patch(e,{assigned_staff_name:x.target.value})} placeholder="담당자" className="border px-2 py-1 text-xs"/><select value={e.status} onChange={x=>void patch(e,{status:x.target.value})} className="col-span-2 border px-2 py-1 text-xs">{columns.map(s=><option key={s} value={s}>{waitingStatusLabel[s]}</option>)}<option value="cancelled">취소</option><option value="no_show">미내원</option></select></div></article>)}</div></div>)}</div></section>
  </HospitalPage>;
}
