-- PAWU V7.6.2
-- 처방 복용 일정 구조화
-- 알림 기능에 사용할 정확한 날짜·시간 데이터 저장

begin;

alter table public.medical_prescriptions
  add column if not exists start_date date,
  add column if not exists end_date date;

create table if not exists public.medical_prescription_schedules (
  id bigint generated by default as identity primary key,
  medical_prescription_id bigint not null
    references public.medical_prescriptions(id)
    on delete cascade,
  scheduled_time time not null,
  created_at timestamptz not null default now()
);

create unique index if not exists medical_prescription_schedule_unique_idx
  on public.medical_prescription_schedules(
    medical_prescription_id,
    scheduled_time
  );

create index if not exists medical_prescription_schedule_prescription_idx
  on public.medical_prescription_schedules(
    medical_prescription_id,
    scheduled_time
  );

alter table public.medical_prescription_schedules enable row level security;

commit;
