-- PAWU V7.5.0
-- 병원 환자관리 + 전자차트 + 처방 기반

create table if not exists public.hospital_patients (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  guardian_user_id uuid references auth.users(id) on delete set null,
  first_reservation_id bigint references public.reservations(id) on delete set null,
  patient_number text,
  memo text,
  last_visit_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, pet_id)
);

create index if not exists hospital_patients_hospital_updated_idx
  on public.hospital_patients(hospital_id, updated_at desc);

create table if not exists public.medical_records (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  hospital_patient_id bigint not null references public.hospital_patients(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  reservation_id bigint references public.reservations(id) on delete set null,
  veterinarian_user_id uuid references auth.users(id) on delete set null,

  guardian_information text,
  ai_reference_summary text,

  chief_complaint text,
  subjective text,
  objective text,
  assessment text,
  plan text,
  diagnosis text,
  treatment text,
  follow_up text,
  veterinarian_note text,

  status text not null default 'draft'
    check (status in ('draft', 'completed', 'locked')),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medical_records_patient_created_idx
  on public.medical_records(hospital_patient_id, created_at desc);

create index if not exists medical_records_hospital_created_idx
  on public.medical_records(hospital_id, created_at desc);

create unique index if not exists medical_records_reservation_unique_idx
  on public.medical_records(reservation_id)
  where reservation_id is not null;

create table if not exists public.medical_prescriptions (
  id bigint generated by default as identity primary key,
  medical_record_id bigint not null references public.medical_records(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  medication_name text not null,
  dosage text,
  frequency text,
  duration text,
  route text,
  instructions text,
  created_at timestamptz not null default now()
);

create index if not exists medical_prescriptions_record_idx
  on public.medical_prescriptions(medical_record_id, created_at);

alter table public.hospital_patients enable row level security;
alter table public.medical_records enable row level security;
alter table public.medical_prescriptions enable row level security;

-- 병원 프로그램에서는 서버 API + service role로 권한을 검사합니다.
-- 보호자 앱에서 의료기록을 직접 수정하지 못하도록 공개 쓰기 정책은 생성하지 않습니다.
