-- PAWU V6.5.5B-02 REV1
-- 기존 V6.3의 emr_audit_logs 테이블을 보존하면서 확장하는 수정본입니다.
-- 이전 V6.5.5B-02 SQL이 트랜잭션 오류로 실패했어도 그대로 실행할 수 있습니다.

begin;

-- 1) 기존 테이블이 없을 때만 최소 구조 생성
create table if not exists public.emr_audit_logs (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  action text,
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- 2) V6.3 기존 테이블에 V6.5.5B 컬럼을 안전하게 추가
alter table public.emr_audit_logs
  add column if not exists hospital_id bigint references public.hospitals(id) on delete cascade,
  add column if not exists pet_id bigint references public.pets(id) on delete restrict,
  add column if not exists actor_display_name text,
  add column if not exists actor_role text,
  add column if not exists action_type text,
  add column if not exists changed_fields jsonb not null default '{}'::jsonb;

-- 3) 기존 로그의 병원/환자/작업 유형을 원본 차트에서 보정
update public.emr_audit_logs log
set
  hospital_id = coalesce(log.hospital_id, er.hospital_id),
  pet_id = coalesce(log.pet_id, er.pet_id),
  action_type = coalesce(log.action_type, log.action, 'updated'),
  changed_fields = coalesce(log.changed_fields, '{}'::jsonb)
from public.emr_records er
where er.id = log.emr_record_id
  and (
    log.hospital_id is null
    or log.pet_id is null
    or log.action_type is null
    or log.changed_fields is null
  );

-- 유효하지 않은 과거 action 문자열은 updated로 정규화
update public.emr_audit_logs
set action_type = 'updated'
where action_type is null
   or action_type not in ('created','updated','finalized','reopened');

-- 현재 데이터 보정 후 필수 컬럼으로 전환
alter table public.emr_audit_logs
  alter column hospital_id set not null,
  alter column pet_id set not null,
  alter column action_type set not null;

-- 기존/재실행 환경 모두에서 체크 제약을 안전하게 구성
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'emr_audit_logs_action_type_check'
      and conrelid = 'public.emr_audit_logs'::regclass
  ) then
    alter table public.emr_audit_logs
      add constraint emr_audit_logs_action_type_check
      check (action_type in ('created','updated','finalized','reopened'));
  end if;
end
$$;

create index if not exists emr_audit_logs_record_created_idx
  on public.emr_audit_logs(emr_record_id, created_at desc);
create index if not exists emr_audit_logs_hospital_created_idx
  on public.emr_audit_logs(hospital_id, created_at desc);
create index if not exists emr_audit_logs_pet_created_idx
  on public.emr_audit_logs(pet_id, created_at desc);

-- 4) 실제 변경 항목 비교 함수
create or replace function public.pawu_emr_changed_fields(
  old_row public.emr_records,
  new_row public.emr_records
)
returns jsonb
language plpgsql
stable
as $$
declare
  result jsonb := '{}'::jsonb;
begin
  if old_row.chief_complaint is distinct from new_row.chief_complaint then result := result || jsonb_build_object('chiefComplaint', jsonb_build_object('before', old_row.chief_complaint, 'after', new_row.chief_complaint)); end if;
  if old_row.subjective is distinct from new_row.subjective then result := result || jsonb_build_object('subjective', jsonb_build_object('before', old_row.subjective, 'after', new_row.subjective)); end if;
  if old_row.objective is distinct from new_row.objective then result := result || jsonb_build_object('objective', jsonb_build_object('before', old_row.objective, 'after', new_row.objective)); end if;
  if old_row.assessment is distinct from new_row.assessment then result := result || jsonb_build_object('assessment', jsonb_build_object('before', old_row.assessment, 'after', new_row.assessment)); end if;
  if old_row.plan is distinct from new_row.plan then result := result || jsonb_build_object('plan', jsonb_build_object('before', old_row.plan, 'after', new_row.plan)); end if;
  if old_row.diagnosis_summary is distinct from new_row.diagnosis_summary then result := result || jsonb_build_object('diagnosisSummary', jsonb_build_object('before', old_row.diagnosis_summary, 'after', new_row.diagnosis_summary)); end if;
  if old_row.weight_kg is distinct from new_row.weight_kg then result := result || jsonb_build_object('weightKg', jsonb_build_object('before', old_row.weight_kg, 'after', new_row.weight_kg)); end if;
  if old_row.temperature_c is distinct from new_row.temperature_c then result := result || jsonb_build_object('temperatureC', jsonb_build_object('before', old_row.temperature_c, 'after', new_row.temperature_c)); end if;
  if old_row.heart_rate is distinct from new_row.heart_rate then result := result || jsonb_build_object('heartRate', jsonb_build_object('before', old_row.heart_rate, 'after', new_row.heart_rate)); end if;
  if old_row.respiratory_rate is distinct from new_row.respiratory_rate then result := result || jsonb_build_object('respiratoryRate', jsonb_build_object('before', old_row.respiratory_rate, 'after', new_row.respiratory_rate)); end if;
  if old_row.bcs is distinct from new_row.bcs then result := result || jsonb_build_object('bcs', jsonb_build_object('before', old_row.bcs, 'after', new_row.bcs)); end if;
  if old_row.crt_seconds is distinct from new_row.crt_seconds then result := result || jsonb_build_object('crtSeconds', jsonb_build_object('before', old_row.crt_seconds, 'after', new_row.crt_seconds)); end if;
  if old_row.next_visit_date is distinct from new_row.next_visit_date then result := result || jsonb_build_object('nextVisitDate', jsonb_build_object('before', old_row.next_visit_date, 'after', new_row.next_visit_date)); end if;
  return result;
end;
$$;

-- 5) 생성/수정/확정/재개 로그 트리거
create or replace function public.pawu_emr_write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid;
  actor_name text;
  actor_role_value text;
  action_value text;
  change_value jsonb;
begin
  actor_id := coalesce(new.updated_by, new.created_by, new.finalized_by);

  select hs.display_name, hs.role
    into actor_name, actor_role_value
  from public.hospital_staff hs
  where hs.hospital_id = new.hospital_id
    and hs.user_id = actor_id
  limit 1;

  if actor_name is null and actor_id is not null then
    select coalesce(u.raw_user_meta_data->>'name', u.email, '병원 사용자'), 'owner'
      into actor_name, actor_role_value
    from auth.users u
    where u.id = actor_id;
  end if;

  if tg_op = 'INSERT' then
    action_value := 'created';
    change_value := '{}'::jsonb;
  else
    change_value := public.pawu_emr_changed_fields(old, new);

    if old.status is distinct from new.status and new.status = 'finalized' then
      action_value := 'finalized';
    elsif old.status is distinct from new.status
      and old.status = 'finalized'
      and new.status = 'draft' then
      action_value := 'reopened';
    elsif change_value <> '{}'::jsonb then
      action_value := 'updated';
    else
      return new;
    end if;
  end if;

  insert into public.emr_audit_logs(
    hospital_id,
    emr_record_id,
    pet_id,
    actor_user_id,
    actor_display_name,
    actor_role,
    action_type,
    action,
    reason,
    changed_fields
  ) values (
    new.hospital_id,
    new.id,
    new.pet_id,
    actor_id,
    coalesce(actor_name, '병원 사용자'),
    coalesce(actor_role_value, 'unknown'),
    action_value,
    action_value,
    case when action_value = 'reopened' then new.reopen_reason else null end,
    change_value
  );

  return new;
end;
$$;

drop trigger if exists emr_records_audit_trigger on public.emr_records;
create trigger emr_records_audit_trigger
after insert or update on public.emr_records
for each row execute function public.pawu_emr_write_audit_log();

-- 6) 구형 재개 함수도 트리거 기반으로 통일해 중복 로그 방지
create or replace function public.pawu_reopen_emr_record(
  p_hospital_id bigint,
  p_record_id bigint,
  p_actor_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if coalesce(trim(p_reason), '') = '' then
    raise exception '재개 사유가 필요합니다.';
  end if;

  select status
    into v_status
  from public.emr_records
  where id = p_record_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '전자차트를 찾지 못했습니다.';
  end if;

  if v_status <> 'finalized' then
    raise exception '확정된 차트만 다시 열 수 있습니다.';
  end if;

  update public.emr_records
  set status = 'draft',
      finalized_at = null,
      finalized_by = null,
      reopen_reason = trim(p_reason),
      updated_by = p_actor_user_id,
      updated_at = now()
  where id = p_record_id
    and hospital_id = p_hospital_id;

  return jsonb_build_object('record_id', p_record_id, 'status', 'draft');
end;
$$;

-- 7) 병원별 조회 정책
alter table public.emr_audit_logs enable row level security;

drop policy if exists "hospital members read emr audit logs" on public.emr_audit_logs;
create policy "hospital members read emr audit logs"
on public.emr_audit_logs
for select to authenticated
using (
  exists (
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = public.emr_audit_logs.hospital_id
      and hs.is_active = true
  )
  or exists (
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = public.emr_audit_logs.hospital_id
  )
);

grant select on public.emr_audit_logs to authenticated;
grant all on public.emr_audit_logs to service_role;
grant usage, select on sequence public.emr_audit_logs_id_seq to service_role;

notify pgrst, 'reload schema';
commit;

-- 실행 확인용 결과
select
  column_name,
  data_type,
  is_nullable
from information_schema.columns
where table_schema = 'public'
  and table_name = 'emr_audit_logs'
order by ordinal_position;
