-- PAWU EMR V6.3
-- V5, V6, V6.1, V6.2 적용 후 실행하세요.

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.hospital_staff
set permissions =
  coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') = 'owner' then
      '{"view_emr":true,"write_emr":true,"finalize_emr":true}'::jsonb
    when coalesce(role, '') = 'veterinarian' then
      '{"view_emr":true,"write_emr":true,"finalize_emr":true}'::jsonb
    when coalesce(role, '') in ('nurse','receptionist') then
      '{"view_emr":true,"write_emr":true,"finalize_emr":false}'::jsonb
    else
      '{"view_emr":true,"write_emr":false,"finalize_emr":false}'::jsonb
  end;

create table if not exists public.emr_records (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  reservation_id bigint references public.reservations(id) on delete set null,
  invoice_id bigint references public.hospital_invoices(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft','finalized')),
  chief_complaint text,
  subjective_notes text,
  objective_notes text,
  assessment_notes text,
  plan_notes text,
  diagnosis_summary text,
  treatment_summary text,
  guardian_summary text,
  weight_kg numeric(8,2) check (weight_kg is null or weight_kg >= 0),
  temperature_c numeric(5,2),
  heart_rate_bpm integer check (heart_rate_bpm is null or heart_rate_bpm >= 0),
  respiratory_rate_bpm integer check (respiratory_rate_bpm is null or respiratory_rate_bpm >= 0),
  follow_up_date date,
  attending_vet_id uuid references public.profiles(id) on delete set null,
  finalized_at timestamptz,
  finalized_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists emr_records_reservation_unique_idx
  on public.emr_records(reservation_id)
  where reservation_id is not null;

create index if not exists emr_records_hospital_pet_created_idx
  on public.emr_records(hospital_id, pet_id, created_at desc);

create index if not exists emr_records_hospital_status_idx
  on public.emr_records(hospital_id, status, created_at desc);

create table if not exists public.emr_diagnoses (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  diagnosis_name text not null,
  diagnosis_code text,
  diagnosis_type text not null default 'suspected'
    check (diagnosis_type in ('suspected','confirmed','ruled_out')),
  is_primary boolean not null default false,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists emr_diagnoses_record_idx
  on public.emr_diagnoses(emr_record_id, is_primary desc);

create table if not exists public.emr_procedures (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  service_item_id bigint references public.hospital_service_items(id) on delete set null,
  procedure_name text not null,
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists emr_procedures_record_idx
  on public.emr_procedures(emr_record_id);

create table if not exists public.emr_prescriptions (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  medication_name text not null,
  dosage text,
  unit text,
  frequency text,
  duration_days integer check (duration_days is null or duration_days > 0),
  route text,
  instructions text,
  created_at timestamptz not null default now()
);

create index if not exists emr_prescriptions_record_idx
  on public.emr_prescriptions(emr_record_id);

create table if not exists public.emr_followups (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  follow_up_type text not null default 'recheck'
    check (follow_up_type in ('recheck','vaccination','medication','test','other')),
  due_date date,
  title text not null,
  note text,
  status text not null default 'scheduled'
    check (status in ('scheduled','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists emr_followups_due_status_idx
  on public.emr_followups(due_date, status);

create table if not exists public.emr_audit_logs (
  id bigint generated by default as identity primary key,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  action text not null
    check (action in ('created','updated','finalized','reopened')),
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists emr_audit_logs_record_idx
  on public.emr_audit_logs(emr_record_id, created_at desc);

create or replace function public.pawu_reopen_emr_record(
  p_hospital_id bigint,
  p_record_id bigint,
  p_actor_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if coalesce(trim(p_reason), '') = '' then
    raise exception '재개 사유가 필요합니다.';
  end if;

  select status
  into v_status
  from public.emr_records
  where id = p_record_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '전자차트를 찾지 못했습니다.';
  end if;

  if v_status <> 'finalized' then
    raise exception '확정된 차트만 다시 열 수 있습니다.';
  end if;

  update public.emr_records
  set status = 'draft',
      finalized_at = null,
      finalized_by = null,
      updated_by = p_actor_user_id,
      updated_at = now()
  where id = p_record_id;

  insert into public.emr_audit_logs(
    emr_record_id, action, reason, actor_user_id
  )
  values(
    p_record_id, 'reopened', p_reason, p_actor_user_id
  );

  return jsonb_build_object(
    'record_id', p_record_id,
    'status', 'draft'
  );
end;
$$;

alter table public.emr_records enable row level security;
alter table public.emr_diagnoses enable row level security;
alter table public.emr_procedures enable row level security;
alter table public.emr_prescriptions enable row level security;
alter table public.emr_followups enable row level security;
alter table public.emr_audit_logs enable row level security;

drop policy if exists "hospital members read emr records" on public.emr_records;
create policy "hospital members read emr records"
on public.emr_records for select to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = emr_records.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = emr_records.hospital_id
  )
  or exists(
    select 1 from public.pets p
    where p.id = emr_records.pet_id
      and p.user_id = auth.uid()
      and emr_records.status = 'finalized'
  )
);

drop policy if exists "guardians read finalized diagnoses" on public.emr_diagnoses;
create policy "guardians read finalized diagnoses"
on public.emr_diagnoses for select to authenticated
using (
  exists(
    select 1
    from public.emr_records er
    join public.pets p on p.id = er.pet_id
    where er.id = emr_diagnoses.emr_record_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = er.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = er.hospital_id
        )
        or (p.user_id = auth.uid() and er.status = 'finalized')
      )
  )
);

drop policy if exists "guardians read finalized procedures" on public.emr_procedures;
create policy "guardians read finalized procedures"
on public.emr_procedures for select to authenticated
using (
  exists(
    select 1
    from public.emr_records er
    join public.pets p on p.id = er.pet_id
    where er.id = emr_procedures.emr_record_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = er.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = er.hospital_id
        )
        or (p.user_id = auth.uid() and er.status = 'finalized')
      )
  )
);

drop policy if exists "guardians read finalized prescriptions" on public.emr_prescriptions;
create policy "guardians read finalized prescriptions"
on public.emr_prescriptions for select to authenticated
using (
  exists(
    select 1
    from public.emr_records er
    join public.pets p on p.id = er.pet_id
    where er.id = emr_prescriptions.emr_record_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = er.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = er.hospital_id
        )
        or (p.user_id = auth.uid() and er.status = 'finalized')
      )
  )
);

drop policy if exists "guardians read finalized followups" on public.emr_followups;
create policy "guardians read finalized followups"
on public.emr_followups for select to authenticated
using (
  exists(
    select 1
    from public.emr_records er
    join public.pets p on p.id = er.pet_id
    where er.id = emr_followups.emr_record_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = er.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = er.hospital_id
        )
        or (p.user_id = auth.uid() and er.status = 'finalized')
      )
  )
);

-- 쓰기 작업은 서버 service-role API를 사용합니다.
-- 보호자는 확정된 차트 중 공개용 요약, 처방, 재진 정보만 확인합니다.
-- SOAP 원문과 병원 내부 평가 내용은 보호자 API에서 반환하지 않습니다.
