-- PAWU PRESCRIPTION & MEDICATION V6.5
-- V6.4.2 적용 후 실행하세요.

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.hospital_staff
set permissions =
  coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') in ('owner','veterinarian') then
      '{"view_prescription":true,"write_prescription":true,"finalize_prescription":true}'::jsonb
    when coalesce(role, '') in ('nurse','assistant') then
      '{"view_prescription":true,"write_prescription":true,"finalize_prescription":false}'::jsonb
    else
      '{"view_prescription":true,"write_prescription":false,"finalize_prescription":false}'::jsonb
  end;

create table if not exists public.prescriptions (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  emr_record_id bigint references public.emr_records(id) on delete set null,
  reservation_id bigint references public.reservations(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft','finalized','cancelled')),
  diagnosis_summary text,
  guardian_note text,
  guardian_visible boolean not null default false,
  start_date date,
  end_date date,
  finalized_at timestamptz,
  finalized_by uuid references auth.users(id) on delete set null,
  cancellation_reason text,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists prescriptions_hospital_status_created_idx
  on public.prescriptions(hospital_id, status, created_at desc);

create index if not exists prescriptions_pet_created_idx
  on public.prescriptions(pet_id, created_at desc);

create index if not exists prescriptions_emr_idx
  on public.prescriptions(emr_record_id);

create table if not exists public.prescription_items (
  id bigint generated by default as identity primary key,
  prescription_id bigint not null references public.prescriptions(id) on delete cascade,
  medication_name text not null,
  active_ingredient text,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  dose_amount numeric not null check (dose_amount > 0),
  dose_unit text not null,
  route text not null,
  frequency text not null,
  duration_days integer check (duration_days is null or duration_days > 0),
  total_quantity numeric check (total_quantity is null or total_quantity > 0),
  instructions text,
  warning_note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists prescription_items_prescription_sort_idx
  on public.prescription_items(prescription_id, sort_order, id);

create index if not exists prescription_items_inventory_idx
  on public.prescription_items(inventory_item_id);

create table if not exists public.prescription_templates (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  name text not null,
  category text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, name)
);

create index if not exists prescription_templates_hospital_active_idx
  on public.prescription_templates(hospital_id, is_active, name);

create table if not exists public.prescription_template_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.prescription_templates(id) on delete cascade,
  medication_name text not null,
  active_ingredient text,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  dose_amount numeric,
  dose_unit text,
  route text,
  frequency text,
  duration_days integer,
  total_quantity numeric,
  instructions text,
  warning_note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists prescription_template_items_template_sort_idx
  on public.prescription_template_items(template_id, sort_order, id);

create table if not exists public.prescription_audit_logs (
  id bigint generated by default as identity primary key,
  prescription_id bigint not null references public.prescriptions(id) on delete cascade,
  action text not null
    check (action in ('created','updated','finalized','reopened','cancelled')),
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists prescription_audit_logs_prescription_idx
  on public.prescription_audit_logs(prescription_id, created_at desc);

create or replace function public.pawu_reopen_prescription(
  p_hospital_id bigint,
  p_prescription_id bigint,
  p_actor_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if coalesce(trim(p_reason), '') = '' then
    raise exception '재개 사유가 필요합니다.';
  end if;

  select status
  into v_status
  from public.prescriptions
  where id = p_prescription_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '처방전을 찾지 못했습니다.';
  end if;

  if v_status <> 'finalized' then
    raise exception '확정된 처방전만 다시 열 수 있습니다.';
  end if;

  update public.prescriptions
  set status = 'draft',
      finalized_at = null,
      finalized_by = null,
      updated_by = p_actor_user_id,
      updated_at = now()
  where id = p_prescription_id;

  insert into public.prescription_audit_logs(
    prescription_id, action, reason, actor_user_id
  )
  values(
    p_prescription_id, 'reopened', p_reason, p_actor_user_id
  );

  return jsonb_build_object(
    'prescription_id', p_prescription_id,
    'status', 'draft'
  );
end;
$$;

alter table public.prescriptions enable row level security;
alter table public.prescription_items enable row level security;
alter table public.prescription_templates enable row level security;
alter table public.prescription_template_items enable row level security;
alter table public.prescription_audit_logs enable row level security;

drop policy if exists "hospital and guardian read prescriptions"
  on public.prescriptions;

create policy "hospital and guardian read prescriptions"
on public.prescriptions
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = prescriptions.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = prescriptions.hospital_id
  )
  or exists(
    select 1
    from public.pets p
    where p.id = prescriptions.pet_id
      and p.user_id = auth.uid()
      and prescriptions.status = 'finalized'
      and prescriptions.guardian_visible = true
  )
);

drop policy if exists "hospital and guardian read prescription items"
  on public.prescription_items;

create policy "hospital and guardian read prescription items"
on public.prescription_items
for select
to authenticated
using (
  exists(
    select 1
    from public.prescriptions pr
    join public.pets p on p.id = pr.pet_id
    where pr.id = prescription_items.prescription_id
      and (
        exists(
          select 1
          from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = pr.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1
          from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = pr.hospital_id
        )
        or (
          p.user_id = auth.uid()
          and pr.status = 'finalized'
          and pr.guardian_visible = true
        )
      )
  )
);

drop policy if exists "hospital members read prescription templates"
  on public.prescription_templates;

create policy "hospital members read prescription templates"
on public.prescription_templates
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = prescription_templates.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = prescription_templates.hospital_id
  )
);

insert into public.hospital_feature_settings(
  hospital_id, feature_key, is_enabled, sort_order
)
select
  h.id,
  'prescriptions',
  true,
  55
from public.hospitals h
on conflict(hospital_id, feature_key) do nothing;

-- 설계 원칙
-- 1. PAWU는 약물 용량을 자동 결정하지 않습니다.
-- 2. 처방은 수의사가 직접 입력하고 확정합니다.
-- 3. 보호자는 병원이 확정하고 공개한 처방전만 확인합니다.
-- 4. 재고 품목 연결은 가능하지만 자동 차감은 추후 검토 단계에서 수행합니다.
