-- PAWU LAB & IMAGING V6.4
-- V5 ~ V6.3 적용 후 실행하세요.

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.hospital_staff
set permissions =
  coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') = 'owner' then
      '{"view_lab":true,"write_lab":true,"finalize_lab":true}'::jsonb
    when coalesce(role, '') = 'veterinarian' then
      '{"view_lab":true,"write_lab":true,"finalize_lab":true}'::jsonb
    when coalesce(role, '') in ('nurse','receptionist') then
      '{"view_lab":true,"write_lab":true,"finalize_lab":false}'::jsonb
    else
      '{"view_lab":true,"write_lab":false,"finalize_lab":false}'::jsonb
  end;

create table if not exists public.lab_orders (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  emr_record_id bigint references public.emr_records(id) on delete set null,
  reservation_id bigint references public.reservations(id) on delete set null,
  category text not null,
  test_name text not null,
  status text not null default 'ordered'
    check (status in ('ordered','collected','processing','completed','finalized','cancelled')),
  priority text not null default 'routine'
    check (priority in ('routine','urgent','stat')),
  specimen_type text,
  clinical_note text,
  external_lab_name text,
  interpretation text,
  guardian_summary text,
  guardian_visible boolean not null default false,
  requested_by uuid references public.profiles(id) on delete set null,
  finalized_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  requested_at timestamptz not null default now(),
  collected_at timestamptz,
  completed_at timestamptz,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lab_orders_hospital_status_idx
  on public.lab_orders(hospital_id, status, created_at desc);

create index if not exists lab_orders_pet_created_idx
  on public.lab_orders(pet_id, created_at desc);

create index if not exists lab_orders_emr_idx
  on public.lab_orders(emr_record_id);

create table if not exists public.lab_result_values (
  id bigint generated by default as identity primary key,
  lab_order_id bigint not null references public.lab_orders(id) on delete cascade,
  analyte_name text not null,
  result_value numeric,
  result_text text,
  unit text,
  reference_low numeric,
  reference_high numeric,
  reference_text text,
  abnormal_flag text not null default 'normal'
    check (abnormal_flag in ('normal','low','high','critical','unknown')),
  sort_order integer not null default 0,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists lab_result_values_order_sort_idx
  on public.lab_result_values(lab_order_id, sort_order, id);

create table if not exists public.lab_attachments (
  id bigint generated by default as identity primary key,
  lab_order_id bigint not null references public.lab_orders(id) on delete cascade,
  file_name text not null,
  file_path text not null,
  mime_type text,
  file_size bigint,
  attachment_type text not null default 'other'
    check (attachment_type in ('image','pdf','dicom','other')),
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(lab_order_id, file_path)
);

create index if not exists lab_attachments_order_idx
  on public.lab_attachments(lab_order_id, created_at desc);

create table if not exists public.lab_audit_logs (
  id bigint generated by default as identity primary key,
  lab_order_id bigint not null references public.lab_orders(id) on delete cascade,
  action text not null
    check (action in ('created','updated','finalized','reopened','file_added','file_deleted')),
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists lab_audit_logs_order_idx
  on public.lab_audit_logs(lab_order_id, created_at desc);

create or replace function public.pawu_reopen_lab_order(
  p_hospital_id bigint,
  p_order_id bigint,
  p_actor_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if coalesce(trim(p_reason), '') = '' then
    raise exception '재개 사유가 필요합니다.';
  end if;

  select status
  into v_status
  from public.lab_orders
  where id = p_order_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '검사 주문을 찾지 못했습니다.';
  end if;

  if v_status <> 'finalized' then
    raise exception '확정된 검사만 다시 열 수 있습니다.';
  end if;

  update public.lab_orders
  set status = 'completed',
      finalized_at = null,
      finalized_by = null,
      updated_by = p_actor_user_id,
      updated_at = now()
  where id = p_order_id;

  insert into public.lab_audit_logs(
    lab_order_id, action, reason, actor_user_id
  )
  values(
    p_order_id, 'reopened', p_reason, p_actor_user_id
  );

  return jsonb_build_object('order_id', p_order_id, 'status', 'completed');
end;
$$;

insert into storage.buckets(id, name, public, file_size_limit)
values('lab-results', 'lab-results', false, 52428800)
on conflict(id) do update
set public = false,
    file_size_limit = 52428800;

alter table public.lab_orders enable row level security;
alter table public.lab_result_values enable row level security;
alter table public.lab_attachments enable row level security;
alter table public.lab_audit_logs enable row level security;

drop policy if exists "hospital and guardian read lab orders" on public.lab_orders;
create policy "hospital and guardian read lab orders"
on public.lab_orders for select to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = lab_orders.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = lab_orders.hospital_id
  )
  or exists(
    select 1 from public.pets p
    where p.id = lab_orders.pet_id
      and p.user_id = auth.uid()
      and lab_orders.status = 'finalized'
      and lab_orders.guardian_visible = true
  )
);

drop policy if exists "hospital and guardian read lab values" on public.lab_result_values;
create policy "hospital and guardian read lab values"
on public.lab_result_values for select to authenticated
using (
  exists(
    select 1
    from public.lab_orders lo
    join public.pets p on p.id = lo.pet_id
    where lo.id = lab_result_values.lab_order_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = lo.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = lo.hospital_id
        )
        or (
          p.user_id = auth.uid()
          and lo.status = 'finalized'
          and lo.guardian_visible = true
        )
      )
  )
);

drop policy if exists "hospital and guardian read lab attachments" on public.lab_attachments;
create policy "hospital and guardian read lab attachments"
on public.lab_attachments for select to authenticated
using (
  exists(
    select 1
    from public.lab_orders lo
    join public.pets p on p.id = lo.pet_id
    where lo.id = lab_attachments.lab_order_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = lo.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = lo.hospital_id
        )
        or (
          p.user_id = auth.uid()
          and lo.status = 'finalized'
          and lo.guardian_visible = true
        )
      )
  )
);

drop policy if exists "hospital members upload lab files" on storage.objects;
create policy "hospital members upload lab files"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'lab-results'
  and (
    exists(
      select 1 from public.hospital_staff hs
      where hs.user_id = auth.uid()
        and hs.is_active = true
    )
    or exists(
      select 1 from public.hospital_admins ha
      where ha.user_id = auth.uid()
    )
  )
);

drop policy if exists "hospital members read lab files" on storage.objects;
create policy "hospital members read lab files"
on storage.objects for select to authenticated
using (
  bucket_id = 'lab-results'
  and (
    exists(
      select 1 from public.hospital_staff hs
      where hs.user_id = auth.uid()
        and hs.is_active = true
    )
    or exists(
      select 1 from public.hospital_admins ha
      where ha.user_id = auth.uid()
    )
  )
);

-- 보호자 파일 열람은 서버 API가 10분짜리 signed URL을 발급합니다.
-- 영상·PDF 원본은 비공개 버킷에 저장합니다.
-- AI 판독은 포함하지 않으며 병원에서 확정한 설명만 보호자에게 공개합니다.
