-- PAWU HOSPITAL SYSTEM V2
-- V1 SQL 적용 후 실행하세요.

alter table public.reservations
  add column if not exists workflow_updated_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'reservations_status_v2_check'
  ) then
    alter table public.reservations
      drop constraint if exists reservations_status_check;
    alter table public.reservations
      add constraint reservations_status_v2_check
      check (status in ('requested','approved','arrived','in_progress','payment_pending','completed','rejected','cancelled','no_show'));
  end if;
exception when others then
  raise notice '예약 status 제약조건은 기존 프로젝트 설정에 맞게 수동 확인이 필요할 수 있습니다: %', sqlerrm;
end $$;

alter table public.pets
  add column if not exists allergies text,
  add column if not exists chronic_conditions text,
  add column if not exists microchip_number text,
  add column if not exists blood_type text,
  add column if not exists is_neutered boolean;

create table if not exists public.hospital_staff (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  email text not null,
  role text not null check (role in ('owner','veterinarian','nurse','receptionist')),
  permissions jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id,user_id)
);

create table if not exists public.medical_exams (
  id bigint generated by default as identity primary key,
  medical_record_id bigint references public.medical_records(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  exam_type text not null,
  exam_name text not null,
  result_summary text,
  result_detail text,
  performed_at date not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.surgery_records (
  id bigint generated by default as identity primary key,
  medical_record_id bigint references public.medical_records(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  surgery_name text not null,
  procedure_notes text,
  surgeon_name text,
  anesthesia_notes text,
  performed_at date not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.medical_attachments (
  id bigint generated by default as identity primary key,
  medical_record_id bigint references public.medical_records(id) on delete set null,
  exam_id bigint references public.medical_exams(id) on delete set null,
  surgery_id bigint references public.surgery_records(id) on delete set null,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  uploaded_by uuid references auth.users(id) on delete set null,
  file_name text not null,
  file_path text not null,
  file_type text not null,
  mime_type text,
  file_size bigint,
  public_url text,
  created_at timestamptz not null default now()
);

create index if not exists hospital_staff_user_idx on public.hospital_staff(user_id,is_active);
create index if not exists medical_exams_pet_date_idx on public.medical_exams(pet_id,performed_at desc);
create index if not exists surgery_records_pet_date_idx on public.surgery_records(pet_id,performed_at desc);
create index if not exists medical_attachments_pet_idx on public.medical_attachments(pet_id,created_at desc);

insert into public.hospital_staff(hospital_id,user_id,display_name,email,role,permissions,is_active)
select ha.hospital_id,ha.user_id,'병원 원장',coalesce(u.email,''),'owner',
'{"manage_staff":true,"manage_reservations":true,"write_medical_records":true,"view_medical_records":true,"manage_billing_status":true,"manage_attachments":true}'::jsonb,true
from public.hospital_admins ha
join auth.users u on u.id=ha.user_id
on conflict(hospital_id,user_id) do nothing;

alter table public.hospital_staff enable row level security;
alter table public.medical_exams enable row level security;
alter table public.surgery_records enable row level security;
alter table public.medical_attachments enable row level security;

drop policy if exists "hospital staff read coworkers" on public.hospital_staff;
create policy "hospital staff read coworkers" on public.hospital_staff for select to authenticated
using (exists(select 1 from public.hospital_staff me where me.user_id=auth.uid() and me.hospital_id=hospital_staff.hospital_id and me.is_active=true));

drop policy if exists "hospital owners manage staff" on public.hospital_staff;
create policy "hospital owners manage staff" on public.hospital_staff for all to authenticated
using (exists(select 1 from public.hospital_staff me where me.user_id=auth.uid() and me.hospital_id=hospital_staff.hospital_id and me.role='owner' and me.is_active=true))
with check (exists(select 1 from public.hospital_staff me where me.user_id=auth.uid() and me.hospital_id=hospital_staff.hospital_id and me.role='owner' and me.is_active=true));

drop policy if exists "hospital and guardian read exams" on public.medical_exams;
create policy "hospital and guardian read exams" on public.medical_exams for select to authenticated
using (
  exists(select 1 from public.pets p where p.id=medical_exams.pet_id and p.user_id=auth.uid())
  or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=medical_exams.hospital_id and hs.is_active=true)
);

drop policy if exists "hospital and guardian read surgeries" on public.surgery_records;
create policy "hospital and guardian read surgeries" on public.surgery_records for select to authenticated
using (
  exists(select 1 from public.pets p where p.id=surgery_records.pet_id and p.user_id=auth.uid())
  or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=surgery_records.hospital_id and hs.is_active=true)
);

drop policy if exists "hospital and guardian read attachments" on public.medical_attachments;
create policy "hospital and guardian read attachments" on public.medical_attachments for select to authenticated
using (
  exists(select 1 from public.pets p where p.id=medical_attachments.pet_id and p.user_id=auth.uid())
  or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=medical_attachments.hospital_id and hs.is_active=true)
);

drop policy if exists "hospital staff insert attachments" on public.medical_attachments;
create policy "hospital staff insert attachments" on public.medical_attachments for insert to authenticated
with check (exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=medical_attachments.hospital_id and hs.is_active=true));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('medical-attachments','medical-attachments',true,20971520,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "hospital staff upload medical attachments" on storage.objects;
create policy "hospital staff upload medical attachments" on storage.objects for insert to authenticated
with check (bucket_id='medical-attachments' and exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.is_active=true));

drop policy if exists "authenticated read medical attachments" on storage.objects;
create policy "authenticated read medical attachments" on storage.objects for select to authenticated
using (bucket_id='medical-attachments');
