-- PAWU V7.7.0
-- 보호자 복약 일정·복용 기록·인앱 알림 기반
-- 기존 데이터 삭제 없음

begin;

create table if not exists public.medication_dose_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  medical_prescription_id bigint not null
    references public.medical_prescriptions(id)
    on delete cascade,
  scheduled_date date not null,
  scheduled_time time not null,
  status text not null default 'pending'
    check (status in ('pending', 'taken', 'skipped')),
  taken_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (
    user_id,
    medical_prescription_id,
    scheduled_date,
    scheduled_time
  )
);

create index if not exists medication_dose_logs_user_date_idx
  on public.medication_dose_logs(user_id, scheduled_date, scheduled_time);

alter table public.medication_dose_logs enable row level security;

drop policy if exists "guardian_can_read_own_dose_logs"
  on public.medication_dose_logs;

create policy "guardian_can_read_own_dose_logs"
on public.medication_dose_logs
for select
to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.medical_prescriptions mp
    join public.medical_records mr
      on mr.id = mp.medical_record_id
    join public.reservations r
      on r.id = mr.reservation_id
    where mp.id = medication_dose_logs.medical_prescription_id
      and r.user_id = auth.uid()
  )
);

drop policy if exists "guardian_can_insert_own_dose_logs"
  on public.medication_dose_logs;

create policy "guardian_can_insert_own_dose_logs"
on public.medication_dose_logs
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.medical_prescriptions mp
    join public.medical_records mr
      on mr.id = mp.medical_record_id
    join public.reservations r
      on r.id = mr.reservation_id
    where mp.id = medication_dose_logs.medical_prescription_id
      and r.user_id = auth.uid()
  )
);

drop policy if exists "guardian_can_update_own_dose_logs"
  on public.medication_dose_logs;

create policy "guardian_can_update_own_dose_logs"
on public.medication_dose_logs
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

commit;
