-- PAWU V7.3.2
-- 품종 / 사료 브랜드 / 제품 마스터 데이터 + 선택형 생활 프로필

create table if not exists public.pet_breeds (
  id bigint generated by default as identity primary key,
  species text not null check (species in ('dog', 'cat')),
  name_ko text not null,
  name_en text,
  sort_order integer not null default 1000,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (species, name_ko)
);

create table if not exists public.pet_food_brands (
  id bigint generated by default as identity primary key,
  name_ko text not null unique,
  name_en text,
  supported_species text[] not null default array['dog','cat']::text[],
  sort_order integer not null default 1000,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pet_food_products (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.pet_food_brands(id) on delete cascade,
  species text not null check (species in ('dog', 'cat', 'all')),
  name_ko text not null,
  sort_order integer not null default 1000,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, species, name_ko)
);

create index if not exists pet_breeds_species_active_idx
  on public.pet_breeds(species, is_active, sort_order, name_ko);

create index if not exists pet_food_brands_active_idx
  on public.pet_food_brands(is_active, sort_order, name_ko);

create index if not exists pet_food_products_brand_species_idx
  on public.pet_food_products(brand_id, species, is_active, sort_order, name_ko);

alter table public.pet_breeds enable row level security;
alter table public.pet_food_brands enable row level security;
alter table public.pet_food_products enable row level security;

drop policy if exists "master breeds readable" on public.pet_breeds;
create policy "master breeds readable"
on public.pet_breeds for select
using (is_active = true);

drop policy if exists "master food brands readable" on public.pet_food_brands;
create policy "master food brands readable"
on public.pet_food_brands for select
using (is_active = true);

drop policy if exists "master food products readable" on public.pet_food_products;
create policy "master food products readable"
on public.pet_food_products for select
using (is_active = true);

alter table public.pets
  add column if not exists breed_id bigint references public.pet_breeds(id) on delete set null;

alter table public.pet_lifestyle_profiles
  add column if not exists food_brand_id bigint references public.pet_food_brands(id) on delete set null,
  add column if not exists food_product_id bigint references public.pet_food_products(id) on delete set null,
  add column if not exists feeding_type text not null default 'scheduled';

alter table public.pet_lifestyle_profiles
  drop constraint if exists pet_lifestyle_profiles_feeding_type_check;

alter table public.pet_lifestyle_profiles
  add constraint pet_lifestyle_profiles_feeding_type_check
  check (feeding_type in ('scheduled', 'free'));

alter table public.pet_lifestyle_profiles
  alter column feeding_times_per_day drop not null;

alter table public.pet_lifestyle_profiles
  drop constraint if exists pet_lifestyle_profiles_feeding_times_per_day_check;

alter table public.pet_lifestyle_profiles
  add constraint pet_lifestyle_profiles_feeding_times_per_day_check
  check (
    (feeding_type = 'scheduled' and feeding_times_per_day between 1 and 5)
    or
    (feeding_type = 'free' and feeding_times_per_day is null)
  );

-- 강아지 품종 초기 마스터
insert into public.pet_breeds (species, name_ko, name_en, sort_order)
values
  ('dog','말티즈','Maltese',10),
  ('dog','푸들','Poodle',20),
  ('dog','포메라니안','Pomeranian',30),
  ('dog','비숑 프리제','Bichon Frise',40),
  ('dog','시츄','Shih Tzu',50),
  ('dog','치와와','Chihuahua',60),
  ('dog','요크셔테리어','Yorkshire Terrier',70),
  ('dog','미니어처 슈나우저','Miniature Schnauzer',80),
  ('dog','닥스훈트','Dachshund',90),
  ('dog','웰시코기','Welsh Corgi',100),
  ('dog','프렌치 불도그','French Bulldog',110),
  ('dog','골든 리트리버','Golden Retriever',120),
  ('dog','래브라도 리트리버','Labrador Retriever',130),
  ('dog','시바견','Shiba Inu',140),
  ('dog','진돗개','Jindo',150),
  ('dog','보더콜리','Border Collie',160),
  ('dog','사모예드','Samoyed',170),
  ('dog','시베리안 허스키','Siberian Husky',180),
  ('dog','믹스견','Mixed Breed',900)
on conflict (species, name_ko) do update
set name_en = excluded.name_en,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

-- 고양이 품종 초기 마스터
insert into public.pet_breeds (species, name_ko, name_en, sort_order)
values
  ('cat','코리안 숏헤어','Korean Shorthair',10),
  ('cat','러시안 블루','Russian Blue',20),
  ('cat','브리티시 숏헤어','British Shorthair',30),
  ('cat','스코티시 폴드','Scottish Fold',40),
  ('cat','먼치킨','Munchkin',50),
  ('cat','페르시안','Persian',60),
  ('cat','샴','Siamese',70),
  ('cat','아메리칸 숏헤어','American Shorthair',80),
  ('cat','노르웨이 숲','Norwegian Forest',90),
  ('cat','메인쿤','Maine Coon',100),
  ('cat','랙돌','Ragdoll',110),
  ('cat','벵갈','Bengal',120),
  ('cat','터키시 앙고라','Turkish Angora',130),
  ('cat','아비시니안','Abyssinian',140),
  ('cat','스핑크스','Sphynx',150),
  ('cat','믹스묘','Mixed Breed',900)
on conflict (species, name_ko) do update
set name_en = excluded.name_en,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

-- 사료 브랜드 초기 마스터
insert into public.pet_food_brands (name_ko, name_en, supported_species, sort_order)
values
  ('로얄캐닌','Royal Canin',array['dog','cat']::text[],10),
  ('힐스','Hill''s',array['dog','cat']::text[],20),
  ('퓨리나 프로플랜','Purina Pro Plan',array['dog','cat']::text[],30),
  ('오리젠','Orijen',array['dog','cat']::text[],40),
  ('아카나','Acana',array['dog','cat']::text[],50),
  ('ANF','ANF',array['dog','cat']::text[],60),
  ('내추럴코어','Natural Core',array['dog','cat']::text[],70),
  ('뉴트리나','Nutrina',array['dog','cat']::text[],80),
  ('하림펫푸드','Harim Pet Food',array['dog','cat']::text[],90)
on conflict (name_ko) do update
set name_en = excluded.name_en,
    supported_species = excluded.supported_species,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

-- 제품명은 초기 예시 마스터이며 Supabase Table Editor에서 계속 추가/수정 가능
with brand as (
  select id, name_ko from public.pet_food_brands
)
insert into public.pet_food_products (brand_id, species, name_ko, sort_order)
select brand.id, seed.species, seed.product_name, seed.sort_order
from (
  values
    ('로얄캐닌','dog','미니 인도어 어덜트',10),
    ('로얄캐닌','dog','미니 퍼피',20),
    ('로얄캐닌','dog','미니 에이징 12+',30),
    ('로얄캐닌','cat','키튼',10),
    ('로얄캐닌','cat','인도어',20),
    ('로얄캐닌','cat','헤어볼 케어',30),
    ('로얄캐닌','cat','유리너리 케어',40),

    ('힐스','dog','사이언스 다이어트 퍼피',10),
    ('힐스','dog','사이언스 다이어트 어덜트',20),
    ('힐스','cat','사이언스 다이어트 키튼',10),
    ('힐스','cat','사이언스 다이어트 어덜트',20),

    ('퓨리나 프로플랜','dog','퍼피',10),
    ('퓨리나 프로플랜','dog','어덜트',20),
    ('퓨리나 프로플랜','cat','키튼',10),
    ('퓨리나 프로플랜','cat','어덜트',20),

    ('오리젠','dog','오리지널 독',10),
    ('오리젠','dog','퍼피',20),
    ('오리젠','cat','오리지널 캣',10),
    ('오리젠','cat','키튼',20),

    ('아카나','dog','어덜트 독',10),
    ('아카나','dog','퍼피',20),
    ('아카나','cat','와일드 프레이리 캣',10),

    ('ANF','dog','독 식스프리',10),
    ('ANF','cat','캣 식스프리',10),

    ('내추럴코어','dog','에코 독',10),
    ('내추럴코어','cat','에코 캣',10),

    ('뉴트리나','dog','건강백서',10),
    ('뉴트리나','cat','비스트로 캣',10),

    ('하림펫푸드','dog','더리얼 독',10),
    ('하림펫푸드','cat','더리얼 캣',10)
) as seed(brand_name, species, product_name, sort_order)
join brand on brand.name_ko = seed.brand_name
on conflict (brand_id, species, name_ko) do update
set sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();
