begin;

create table if not exists public.central_medications (
  id bigint generated by default as identity primary key,
  source_code text,
  source_item_id text,
  product_name_ko text not null,
  product_name_en text,
  ingredient_name_ko text,
  ingredient_name_en text,
  manufacturer_name text,
  dosage_form text,
  strength_text text,
  route_hint text,
  target_species text[] not null default '{}',
  medication_category text,
  is_anesthetic boolean not null default false,
  is_controlled boolean not null default false,
  is_veterinary_approved boolean not null default true,
  approval_status text,
  approval_number text,
  source_url text,
  source_updated_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  search_text text generated always as (
    lower(
      coalesce(product_name_ko,'') || ' ' ||
      coalesce(product_name_en,'') || ' ' ||
      coalesce(ingredient_name_ko,'') || ' ' ||
      coalesce(ingredient_name_en,'') || ' ' ||
      coalesce(manufacturer_name,'') || ' ' ||
      coalesce(strength_text,'')
    )
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_code, source_item_id)
);

create index if not exists central_medications_search_idx
  on public.central_medications using gin (to_tsvector('simple', search_text));

create index if not exists central_medications_product_name_idx
  on public.central_medications(product_name_ko);

create table if not exists public.hospital_medications (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  central_medication_id bigint references public.central_medications(id) on delete restrict,
  hospital_alias text,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  purchase_unit text,
  stock_unit text,
  dispensing_unit text,
  conversion_factor numeric check (conversion_factor is null or conversion_factor > 0),
  storage_location text,
  reorder_level numeric,
  notes text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, central_medication_id)
);

create index if not exists hospital_medications_hospital_active_idx
  on public.hospital_medications(hospital_id, is_active, created_at desc);

alter table public.medication_order_items
  add column if not exists central_medication_id bigint
    references public.central_medications(id) on delete set null,
  add column if not exists hospital_medication_id bigint
    references public.hospital_medications(id) on delete set null,
  add column if not exists product_strength_snapshot text,
  add column if not exists dosage_form_snapshot text,
  add column if not exists manufacturer_snapshot text;

alter table public.central_medications enable row level security;
alter table public.hospital_medications enable row level security;

drop policy if exists "authenticated read central medications"
  on public.central_medications;

create policy "authenticated read central medications"
on public.central_medications
for select
to authenticated
using (true);

drop policy if exists "hospital members read formulary"
  on public.hospital_medications;

create policy "hospital members read formulary"
on public.hospital_medications
for select
to authenticated
using (
  exists (
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_medications.hospital_id
      and hs.is_active = true
  )
);

do $$
begin
  if to_regclass('public.hospital_feature_settings') is not null then
    insert into public.hospital_feature_settings(
      hospital_id, feature_key, is_enabled, sort_order
    )
    select h.id, 'medication_master', true, 52
    from public.hospitals h
    on conflict(hospital_id, feature_key) do nothing;
  end if;
end;
$$;

commit;

select
  to_regclass('public.central_medications') as central_medications,
  to_regclass('public.hospital_medications') as hospital_medications;
