-- PAWU PLATFORM V4
-- V1, V2, V3 SQL 적용 후 실행하세요.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  link_url text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications(user_id, read_at)
  where read_at is null;

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  reservation_updates boolean not null default true,
  chat_messages boolean not null default true,
  medical_updates boolean not null default true,
  medication_reminders boolean not null default true,
  vaccination_reminders boolean not null default true,
  marketing boolean not null default false,
  browser_push boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions(user_id, is_active);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_type text not null check (actor_type in ('guardian','hospital','admin','system')),
  hospital_id bigint references public.hospitals(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_hospital_created_idx
  on public.audit_logs(hospital_id, created_at desc);

create index if not exists audit_logs_actor_created_idx
  on public.audit_logs(actor_user_id, created_at desc);

create table if not exists public.service_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid references auth.users(id) on delete set null,
  hospital_id bigint references public.hospitals(id) on delete set null,
  category text not null,
  subject text not null,
  body text not null,
  status text not null default 'new'
    check (status in ('new','reviewing','resolved','closed')),
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  assigned_admin_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists service_reports_status_created_idx
  on public.service_reports(status, created_at desc);

create table if not exists public.master_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.service_reports enable row level security;
alter table public.master_admins enable row level security;

drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications"
on public.notifications for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications"
on public.notifications for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "users read own notification preferences" on public.notification_preferences;
create policy "users read own notification preferences"
on public.notification_preferences for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users manage own notification preferences" on public.notification_preferences;
create policy "users manage own notification preferences"
on public.notification_preferences for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions"
on public.push_subscriptions for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "hospital members read hospital audit logs" on public.audit_logs;
create policy "hospital members read hospital audit logs"
on public.audit_logs for select to authenticated
using (
  exists (
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = audit_logs.hospital_id
      and hs.is_active = true
  )
  or exists (
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = audit_logs.hospital_id
  )
  or exists (
    select 1 from public.master_admins ma
    where ma.user_id = auth.uid()
  )
);

drop policy if exists "users create service reports" on public.service_reports;
create policy "users create service reports"
on public.service_reports for insert to authenticated
with check (reporter_user_id = auth.uid());

drop policy if exists "users read own service reports" on public.service_reports;
create policy "users read own service reports"
on public.service_reports for select to authenticated
using (
  reporter_user_id = auth.uid()
  or exists (select 1 from public.master_admins ma where ma.user_id = auth.uid())
);

drop policy if exists "master admins manage reports" on public.service_reports;
create policy "master admins manage reports"
on public.service_reports for update to authenticated
using (exists (select 1 from public.master_admins ma where ma.user_id = auth.uid()))
with check (exists (select 1 from public.master_admins ma where ma.user_id = auth.uid()));

drop policy if exists "master admins read master admins" on public.master_admins;
create policy "master admins read master admins"
on public.master_admins for select to authenticated
using (exists (select 1 from public.master_admins ma where ma.user_id = auth.uid()));

-- 예약 상태 변경 알림
create or replace function public.pawu_notify_reservation_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.status is distinct from old.status and new.user_id is not null then
    insert into public.notifications(user_id, type, title, body, link_url, metadata)
    values (
      new.user_id,
      'reservation_status',
      '예약 상태가 변경되었습니다',
      '예약 상태: ' || new.status,
      '/my-reservations',
      jsonb_build_object('reservation_id', new.id, 'status', new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists reservations_notification_trigger on public.reservations;
create trigger reservations_notification_trigger
after update of status on public.reservations
for each row execute function public.pawu_notify_reservation_status();

-- 새 채팅 메시지 알림
create or replace function public.pawu_notify_chat_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cc public.chat_conversations%rowtype;
  target_user uuid;
begin
  select * into cc from public.chat_conversations where id = new.conversation_id;

  if new.sender_type = 'hospital' then
    target_user := cc.guardian_user_id;
    insert into public.notifications(user_id, type, title, body, link_url, metadata)
    values (
      target_user,
      'chat_message',
      '병원에서 새 메시지가 왔습니다',
      coalesce(new.content, new.file_name, '첨부파일'),
      '/chat/' || cc.id,
      jsonb_build_object('conversation_id', cc.id, 'message_id', new.id)
    );
  end if;

  return new;
end;
$$;

drop trigger if exists chat_message_notification_trigger on public.chat_messages;
create trigger chat_message_notification_trigger
after insert on public.chat_messages
for each row execute function public.pawu_notify_chat_message();

-- 진료기록 등록 알림
create or replace function public.pawu_notify_medical_record()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.user_id is not null then
    insert into public.notifications(user_id, type, title, body, link_url, metadata)
    values (
      new.user_id,
      'medical_record',
      '새 진료기록이 등록되었습니다',
      coalesce(new.diagnosis, '진료기록을 확인해 주세요.'),
      '/health-notebook/record/' || new.id,
      jsonb_build_object('medical_record_id', new.id, 'pet_id', new.pet_id)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists medical_record_notification_trigger on public.medical_records;
create trigger medical_record_notification_trigger
after insert on public.medical_records
for each row execute function public.pawu_notify_medical_record();

-- 기존 회원의 기본 알림 설정
insert into public.notification_preferences(user_id)
select id from auth.users
on conflict(user_id) do nothing;
