create table if not exists public.fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  device_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fcm_tokens_user_active_idx
  on public.fcm_tokens(user_id, is_active);

alter table public.fcm_tokens enable row level security;

drop policy if exists "users manage own fcm tokens" on public.fcm_tokens;
create policy "users manage own fcm tokens"
on public.fcm_tokens for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
