-- PAWU DASHBOARD SETTINGS V6.4.2
-- V6.4.1 적용 후 실행하세요.

create table if not exists public.hospital_feature_settings (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  feature_key text not null,
  is_enabled boolean not null default true,
  sort_order integer not null default 0,
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, feature_key)
);

create index if not exists hospital_feature_settings_hospital_sort_idx
  on public.hospital_feature_settings(hospital_id, sort_order, feature_key);

create table if not exists public.hospital_dashboard_widgets (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  widget_key text not null,
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  widget_size text not null default 'medium'
    check (widget_size in ('small','medium','large')),
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, widget_key)
);

create index if not exists hospital_dashboard_widgets_hospital_sort_idx
  on public.hospital_dashboard_widgets(hospital_id, sort_order, widget_key);

alter table public.hospital_feature_settings enable row level security;
alter table public.hospital_dashboard_widgets enable row level security;

drop policy if exists "hospital members read feature settings"
  on public.hospital_feature_settings;

create policy "hospital members read feature settings"
on public.hospital_feature_settings
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_feature_settings.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_feature_settings.hospital_id
  )
);

drop policy if exists "hospital managers manage feature settings"
  on public.hospital_feature_settings;

create policy "hospital managers manage feature settings"
on public.hospital_feature_settings
for all
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_feature_settings.hospital_id
      and hs.is_active = true
      and hs.role in ('owner','admin','manager')
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_feature_settings.hospital_id
  )
)
with check (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_feature_settings.hospital_id
      and hs.is_active = true
      and hs.role in ('owner','admin','manager')
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_feature_settings.hospital_id
  )
);

drop policy if exists "hospital members read dashboard widgets"
  on public.hospital_dashboard_widgets;

create policy "hospital members read dashboard widgets"
on public.hospital_dashboard_widgets
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_dashboard_widgets.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_dashboard_widgets.hospital_id
  )
);

drop policy if exists "hospital managers manage dashboard widgets"
  on public.hospital_dashboard_widgets;

create policy "hospital managers manage dashboard widgets"
on public.hospital_dashboard_widgets
for all
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_dashboard_widgets.hospital_id
      and hs.is_active = true
      and hs.role in ('owner','admin','manager')
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_dashboard_widgets.hospital_id
  )
)
with check (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = hospital_dashboard_widgets.hospital_id
      and hs.is_active = true
      and hs.role in ('owner','admin','manager')
  )
  or exists(
    select 1
    from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = hospital_dashboard_widgets.hospital_id
  )
);

-- 각 병원의 기본값은 최초 설정 API 접근 시 자동 생성됩니다.
-- 기능을 숨겨도 데이터 및 테이블은 삭제되지 않습니다.
-- 대시보드 메뉴는 안전한 복귀 경로로 항상 표시됩니다.
