begin;

create table if not exists public.guardian_pet_hospitals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, pet_id, hospital_id)
);

create index if not exists guardian_pet_hospitals_user_idx
  on public.guardian_pet_hospitals(user_id, is_primary, created_at desc);
create index if not exists guardian_pet_hospitals_hospital_idx
  on public.guardian_pet_hospitals(hospital_id, created_at desc);

create table if not exists public.hospital_adoption_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint references public.pets(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (user_id, hospital_id)
);

create index if not exists hospital_adoption_requests_hospital_idx
  on public.hospital_adoption_requests(hospital_id, created_at desc);

alter table public.guardian_pet_hospitals enable row level security;
alter table public.hospital_adoption_requests enable row level security;

drop policy if exists guardian_pet_hospitals_select_own on public.guardian_pet_hospitals;
create policy guardian_pet_hospitals_select_own
on public.guardian_pet_hospitals for select
using (auth.uid() = user_id);

drop policy if exists guardian_pet_hospitals_insert_own on public.guardian_pet_hospitals;
create policy guardian_pet_hospitals_insert_own
on public.guardian_pet_hospitals for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.pets p
    where p.id = pet_id and p.user_id = auth.uid()
  )
);

drop policy if exists guardian_pet_hospitals_update_own on public.guardian_pet_hospitals;
create policy guardian_pet_hospitals_update_own
on public.guardian_pet_hospitals for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.pets p
    where p.id = pet_id and p.user_id = auth.uid()
  )
);

drop policy if exists guardian_pet_hospitals_delete_own on public.guardian_pet_hospitals;
create policy guardian_pet_hospitals_delete_own
on public.guardian_pet_hospitals for delete
using (auth.uid() = user_id);

drop policy if exists hospital_adoption_requests_select_own on public.hospital_adoption_requests;
create policy hospital_adoption_requests_select_own
on public.hospital_adoption_requests for select
using (auth.uid() = user_id);

drop policy if exists hospital_adoption_requests_insert_own on public.hospital_adoption_requests;
create policy hospital_adoption_requests_insert_own
on public.hospital_adoption_requests for insert
with check (auth.uid() = user_id);

drop policy if exists hospital_adoption_requests_delete_own on public.hospital_adoption_requests;
create policy hospital_adoption_requests_delete_own
on public.hospital_adoption_requests for delete
using (auth.uid() = user_id);

create or replace function public.pawu_set_primary_hospital_v702(
  p_pet_id bigint,
  p_hospital_id bigint
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_id bigint;
begin
  if v_user_id is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not exists (
    select 1 from public.pets
    where id = p_pet_id and user_id = v_user_id
  ) then
    raise exception '본인의 반려동물만 설정할 수 있습니다.';
  end if;

  if not exists (select 1 from public.hospitals where id = p_hospital_id) then
    raise exception '병원 정보를 찾을 수 없습니다.';
  end if;

  update public.guardian_pet_hospitals
  set is_primary = false, updated_at = now()
  where user_id = v_user_id and pet_id = p_pet_id;

  insert into public.guardian_pet_hospitals(
    user_id, pet_id, hospital_id, is_primary, updated_at
  ) values (
    v_user_id, p_pet_id, p_hospital_id, true, now()
  )
  on conflict(user_id, pet_id, hospital_id)
  do update set is_primary = true, updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.pawu_set_primary_hospital_v702(bigint,bigint) to authenticated;

commit;
