-- PAWU V6.5.8 재고·약품 관리 고도화
alter table if exists public.inventory_items
  add column if not exists reorder_quantity numeric(14,4) not null default 0 check (reorder_quantity >= 0),
  add column if not exists expiry_warning_days integer not null default 60 check (expiry_warning_days between 1 and 3650),
  add column if not exists regulatory_type text not null default 'general' check (regulatory_type in ('general','prescription','controlled','narcotic')),
  add column if not exists auto_deduct_enabled boolean not null default true;

create table if not exists public.inventory_suppliers(
 id bigint generated by default as identity primary key,
 hospital_id bigint not null references public.hospitals(id) on delete cascade,
 name text not null, contact_name text, phone text, email text, business_number text, memo text,
 is_active boolean not null default true, created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(hospital_id,name)
);
create table if not exists public.inventory_alerts(
 id bigint generated by default as identity primary key,
 hospital_id bigint not null references public.hospitals(id) on delete cascade,
 inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
 lot_id bigint references public.inventory_lots(id) on delete cascade,
 alert_type text not null check(alert_type in('low_stock','out_of_stock','expiring','expired')),
 severity text not null check(severity in('info','warning','critical')),
 source_key text not null, message text not null, resolved_at timestamptz, resolved_by uuid references auth.users(id) on delete set null,
 resolution_note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(hospital_id,source_key)
);
create index if not exists inventory_alerts_open_idx on public.inventory_alerts(hospital_id,resolved_at,severity,created_at desc);

create or replace function public.pawu_refresh_inventory_alerts(p_hospital_id bigint) returns integer language plpgsql security definer set search_path=public as $$
declare v_count integer:=0; r record; v_type text; v_severity text; v_key text; v_message text;
begin
 for r in select * from public.inventory_items where hospital_id=p_hospital_id and is_active=true loop
  if r.current_quantity<=0 then v_type:='out_of_stock';v_severity:='critical';v_key:='item:'||r.id||':out';v_message:=r.name||' 재고가 품절되었습니다.';
  elsif r.current_quantity<=r.minimum_quantity then v_type:='low_stock';v_severity:='warning';v_key:='item:'||r.id||':low';v_message:=r.name||' 재고가 안전재고 이하입니다. 현재 '||r.current_quantity||' '||r.unit;
  else update public.inventory_alerts set resolved_at=coalesce(resolved_at,now()),updated_at=now() where hospital_id=p_hospital_id and inventory_item_id=r.id and alert_type in('low_stock','out_of_stock') and resolved_at is null; continue; end if;
  insert into public.inventory_alerts(hospital_id,inventory_item_id,alert_type,severity,source_key,message) values(p_hospital_id,r.id,v_type,v_severity,v_key,v_message) on conflict(hospital_id,source_key) do update set alert_type=excluded.alert_type,severity=excluded.severity,message=excluded.message,resolved_at=null,updated_at=now();v_count:=v_count+1;
 end loop;
 for r in select l.*,i.hospital_id,i.name,i.expiry_warning_days from public.inventory_lots l join public.inventory_items i on i.id=l.inventory_item_id where i.hospital_id=p_hospital_id and l.remaining_quantity>0 and l.expires_on is not null loop
  if r.expires_on<current_date then v_type:='expired';v_severity:='critical';v_key:='lot:'||r.id||':expired';v_message:=r.name||' LOT '||r.lot_number||'가 만료되었습니다 ('||r.expires_on||').';
  elsif r.expires_on<=current_date+r.expiry_warning_days then v_type:='expiring';v_severity:='warning';v_key:='lot:'||r.id||':expiring';v_message:=r.name||' LOT '||r.lot_number||' 유효기간이 임박했습니다 ('||r.expires_on||').';
  else update public.inventory_alerts set resolved_at=coalesce(resolved_at,now()),updated_at=now() where hospital_id=p_hospital_id and lot_id=r.id and alert_type in('expiring','expired') and resolved_at is null; continue; end if;
  insert into public.inventory_alerts(hospital_id,inventory_item_id,lot_id,alert_type,severity,source_key,message) values(p_hospital_id,r.inventory_item_id,r.id,v_type,v_severity,v_key,v_message) on conflict(hospital_id,source_key) do update set alert_type=excluded.alert_type,severity=excluded.severity,message=excluded.message,resolved_at=null,updated_at=now();v_count:=v_count+1;
 end loop; return v_count; end $$;

alter table public.inventory_suppliers enable row level security; alter table public.inventory_alerts enable row level security;
drop policy if exists "hospital members read inventory suppliers" on public.inventory_suppliers; create policy "hospital members read inventory suppliers" on public.inventory_suppliers for select to authenticated using(exists(select 1 from public.hospital_admins ha where ha.user_id=auth.uid() and ha.hospital_id=inventory_suppliers.hospital_id) or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=inventory_suppliers.hospital_id and hs.is_active=true));
drop policy if exists "hospital managers manage inventory suppliers" on public.inventory_suppliers; create policy "hospital managers manage inventory suppliers" on public.inventory_suppliers for all to authenticated using(exists(select 1 from public.hospital_admins ha where ha.user_id=auth.uid() and ha.hospital_id=inventory_suppliers.hospital_id) or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=inventory_suppliers.hospital_id and hs.is_active=true and (hs.role='owner' or coalesce((hs.permissions->>'manage_inventory')::boolean,false)))) with check(true);
drop policy if exists "hospital members read inventory alerts" on public.inventory_alerts; create policy "hospital members read inventory alerts" on public.inventory_alerts for select to authenticated using(exists(select 1 from public.hospital_admins ha where ha.user_id=auth.uid() and ha.hospital_id=inventory_alerts.hospital_id) or exists(select 1 from public.hospital_staff hs where hs.user_id=auth.uid() and hs.hospital_id=inventory_alerts.hospital_id and hs.is_active=true));
revoke all on function public.pawu_refresh_inventory_alerts(bigint) from public; grant execute on function public.pawu_refresh_inventory_alerts(bigint) to authenticated,service_role;
