begin;

create table if not exists public.emr_audit_logs (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  emr_record_id bigint not null references public.emr_records(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_display_name text,
  actor_role text,
  action_type text not null check (action_type in ('created','updated','finalized','reopened')),
  reason text,
  changed_fields jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists emr_audit_logs_record_created_idx
  on public.emr_audit_logs(emr_record_id, created_at desc);
create index if not exists emr_audit_logs_hospital_created_idx
  on public.emr_audit_logs(hospital_id, created_at desc);
create index if not exists emr_audit_logs_pet_created_idx
  on public.emr_audit_logs(pet_id, created_at desc);

create or replace function public.pawu_emr_changed_fields(old_row public.emr_records, new_row public.emr_records)
returns jsonb
language plpgsql
stable
as $$
declare
  result jsonb := '{}'::jsonb;
begin
  if old_row.chief_complaint is distinct from new_row.chief_complaint then result := result || jsonb_build_object('chiefComplaint', jsonb_build_object('before', old_row.chief_complaint, 'after', new_row.chief_complaint)); end if;
  if old_row.subjective is distinct from new_row.subjective then result := result || jsonb_build_object('subjective', jsonb_build_object('before', old_row.subjective, 'after', new_row.subjective)); end if;
  if old_row.objective is distinct from new_row.objective then result := result || jsonb_build_object('objective', jsonb_build_object('before', old_row.objective, 'after', new_row.objective)); end if;
  if old_row.assessment is distinct from new_row.assessment then result := result || jsonb_build_object('assessment', jsonb_build_object('before', old_row.assessment, 'after', new_row.assessment)); end if;
  if old_row.plan is distinct from new_row.plan then result := result || jsonb_build_object('plan', jsonb_build_object('before', old_row.plan, 'after', new_row.plan)); end if;
  if old_row.diagnosis_summary is distinct from new_row.diagnosis_summary then result := result || jsonb_build_object('diagnosisSummary', jsonb_build_object('before', old_row.diagnosis_summary, 'after', new_row.diagnosis_summary)); end if;
  if old_row.weight_kg is distinct from new_row.weight_kg then result := result || jsonb_build_object('weightKg', jsonb_build_object('before', old_row.weight_kg, 'after', new_row.weight_kg)); end if;
  if old_row.temperature_c is distinct from new_row.temperature_c then result := result || jsonb_build_object('temperatureC', jsonb_build_object('before', old_row.temperature_c, 'after', new_row.temperature_c)); end if;
  if old_row.heart_rate is distinct from new_row.heart_rate then result := result || jsonb_build_object('heartRate', jsonb_build_object('before', old_row.heart_rate, 'after', new_row.heart_rate)); end if;
  if old_row.respiratory_rate is distinct from new_row.respiratory_rate then result := result || jsonb_build_object('respiratoryRate', jsonb_build_object('before', old_row.respiratory_rate, 'after', new_row.respiratory_rate)); end if;
  if old_row.bcs is distinct from new_row.bcs then result := result || jsonb_build_object('bcs', jsonb_build_object('before', old_row.bcs, 'after', new_row.bcs)); end if;
  if old_row.crt_seconds is distinct from new_row.crt_seconds then result := result || jsonb_build_object('crtSeconds', jsonb_build_object('before', old_row.crt_seconds, 'after', new_row.crt_seconds)); end if;
  if old_row.next_visit_date is distinct from new_row.next_visit_date then result := result || jsonb_build_object('nextVisitDate', jsonb_build_object('before', old_row.next_visit_date, 'after', new_row.next_visit_date)); end if;
  return result;
end;
$$;

create or replace function public.pawu_emr_write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid;
  actor_name text;
  actor_role_value text;
  action_value text;
  change_value jsonb;
begin
  actor_id := coalesce(new.updated_by, new.created_by, new.finalized_by);

  select hs.display_name, hs.role
    into actor_name, actor_role_value
  from public.hospital_staff hs
  where hs.hospital_id = new.hospital_id
    and hs.user_id = actor_id
  limit 1;

  if actor_name is null then
    select coalesce(u.raw_user_meta_data->>'name', u.email, '병원 사용자'), 'owner'
      into actor_name, actor_role_value
    from auth.users u
    where u.id = actor_id;
  end if;

  if tg_op = 'INSERT' then
    action_value := 'created';
    change_value := '{}'::jsonb;
  else
    change_value := public.pawu_emr_changed_fields(old, new);
    if old.status is distinct from new.status and new.status = 'finalized' then
      action_value := 'finalized';
    elsif old.status is distinct from new.status and old.status = 'finalized' and new.status = 'draft' then
      action_value := 'reopened';
    elsif change_value <> '{}'::jsonb then
      action_value := 'updated';
    else
      return new;
    end if;
  end if;

  insert into public.emr_audit_logs(
    hospital_id, emr_record_id, pet_id, actor_user_id,
    actor_display_name, actor_role, action_type, reason, changed_fields
  ) values (
    new.hospital_id, new.id, new.pet_id, actor_id,
    coalesce(actor_name, '병원 사용자'), coalesce(actor_role_value, 'unknown'),
    action_value,
    case when action_value = 'reopened' then new.reopen_reason else null end,
    change_value
  );

  return new;
end;
$$;

drop trigger if exists emr_records_audit_trigger on public.emr_records;
create trigger emr_records_audit_trigger
after insert or update on public.emr_records
for each row execute function public.pawu_emr_write_audit_log();

alter table public.emr_audit_logs enable row level security;
drop policy if exists "hospital members read emr audit logs" on public.emr_audit_logs;
create policy "hospital members read emr audit logs"
on public.emr_audit_logs for select to authenticated
using (
  exists(select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = emr_audit_logs.hospital_id
      and hs.is_active = true)
  or exists(select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = emr_audit_logs.hospital_id)
);

grant select on public.emr_audit_logs to authenticated;
grant all on public.emr_audit_logs to service_role;
grant usage, select on sequence public.emr_audit_logs_id_seq to service_role;

notify pgrst, 'reload schema';
commit;
