-- PAWU V7.0.3 전국 병원 DB 기반
create extension if not exists pg_trgm;

alter table public.hospitals add column if not exists normalized_name text;
alter table public.hospitals add column if not exists region_level1 text;
alter table public.hospitals add column if not exists region_level2 text;
alter table public.hospitals add column if not exists imported_at timestamptz;
alter table public.hospitals add column if not exists import_log_id bigint;
alter table public.hospitals add column if not exists geocode_status text not null default 'pending';
alter table public.hospitals add column if not exists geocode_error text;

create table if not exists public.hospital_import_logs (
 id bigint generated by default as identity primary key, file_name text, file_sha256 text,
 total_rows int not null default 0, valid_rows int not null default 0, invalid_rows int not null default 0,
 inserted_count int not null default 0, updated_count int not null default 0, unchanged_count int not null default 0,
 duplicate_count int not null default 0, failed_count int not null default 0,
 status text not null default 'pending' check(status in ('pending','processing','completed','failed')),
 started_at timestamptz, completed_at timestamptz, error_message text, metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
create table if not exists public.hospital_import_changes (
 id bigint generated by default as identity primary key,
 import_log_id bigint not null references public.hospital_import_logs(id) on delete cascade,
 hospital_id bigint references public.hospitals(id) on delete set null, external_id text,
 change_type text not null check(change_type in ('inserted','updated','unchanged','duplicate','failed')),
 changed_fields text[] not null default '{}', old_data jsonb, new_data jsonb, error_message text,
 created_at timestamptz not null default now()
);
create table if not exists public.hospital_import_staging (
 id bigint generated by default as identity primary key,
 import_log_id bigint references public.hospital_import_logs(id) on delete cascade,
 row_number int, external_id text, name text, address text, road_address text, lot_address text, phone text,
 latitude double precision, longitude double precision, business_status text, detailed_business_status text,
 license_date date, closed_at date, raw_data jsonb not null default '{}'::jsonb,
 validation_status text not null default 'pending', validation_error text, created_at timestamptz not null default now()
);

create unique index if not exists hospitals_external_id_unique_idx on public.hospitals(external_id) where external_id is not null;
create index if not exists hospitals_name_trgm_idx on public.hospitals using gin(name gin_trgm_ops);
create index if not exists hospitals_address_trgm_idx on public.hospitals using gin(address gin_trgm_ops);
create index if not exists hospitals_phone_trgm_idx on public.hospitals using gin(phone gin_trgm_ops);
create index if not exists hospitals_region_idx on public.hospitals(region_level1, region_level2);
create index if not exists hospitals_active_source_idx on public.hospitals(is_active, source_type);
create index if not exists hospitals_coordinates_idx on public.hospitals(latitude, longitude) where latitude is not null and longitude is not null;
create index if not exists hospital_import_changes_log_type_idx on public.hospital_import_changes(import_log_id, change_type);
create index if not exists hospital_import_logs_created_idx on public.hospital_import_logs(created_at desc);

alter table public.hospital_import_logs enable row level security;
alter table public.hospital_import_changes enable row level security;
alter table public.hospital_import_staging enable row level security;
