-- PAWU V8.0.0-A
-- 검사·영상 시스템 DB 기반
-- 기존 데이터 삭제 없음

begin;

create table if not exists public.diagnostic_orders (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null
    references public.hospitals(id)
    on delete cascade,
  medical_record_id bigint not null
    references public.medical_records(id)
    on delete cascade,
  hospital_patient_id bigint
    references public.hospital_patients(id)
    on delete set null,
  reservation_id bigint
    references public.reservations(id)
    on delete set null,

  category text not null
    check (
      category in (
        'laboratory',
        'xray',
        'ultrasound',
        'ct',
        'mri',
        'endoscopy',
        'pathology',
        'other'
      )
    ),
  test_code text,
  test_name text not null,
  body_site text,
  priority text not null default 'routine'
    check (priority in ('routine', 'urgent', 'stat')),
  status text not null default 'ordered'
    check (
      status in (
        'ordered',
        'scheduled',
        'collecting',
        'in_progress',
        'completed',
        'cancelled'
      )
    ),

  ordered_by uuid references auth.users(id) on delete set null,
  ordered_at timestamptz not null default now(),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,

  clinical_note text,
  interpretation text,
  internal_note text,
  guardian_summary text,
  is_guardian_visible boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists diagnostic_orders_record_idx
  on public.diagnostic_orders(medical_record_id, created_at desc);

create index if not exists diagnostic_orders_hospital_status_idx
  on public.diagnostic_orders(hospital_id, status, created_at desc);

create index if not exists diagnostic_orders_patient_idx
  on public.diagnostic_orders(hospital_patient_id, created_at desc);


create table if not exists public.diagnostic_result_items (
  id bigint generated by default as identity primary key,
  diagnostic_order_id bigint not null
    references public.diagnostic_orders(id)
    on delete cascade,

  item_code text,
  item_name text not null,
  value_text text,
  value_number numeric,
  unit text,
  reference_min numeric,
  reference_max numeric,
  reference_text text,
  abnormal_flag text
    check (
      abnormal_flag is null
      or abnormal_flag in (
        'normal',
        'low',
        'high',
        'critical_low',
        'critical_high',
        'abnormal'
      )
    ),
  sort_order integer not null default 0,
  note text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists diagnostic_result_items_order_idx
  on public.diagnostic_result_items(
    diagnostic_order_id,
    sort_order,
    id
  );


create table if not exists public.diagnostic_files (
  id bigint generated by default as identity primary key,
  diagnostic_order_id bigint not null
    references public.diagnostic_orders(id)
    on delete cascade,

  storage_bucket text not null default 'diagnostic-files',
  storage_path text not null,
  original_filename text not null,
  mime_type text,
  size_bytes bigint,
  file_kind text not null default 'other'
    check (
      file_kind in (
        'image',
        'dicom',
        'pdf',
        'report',
        'video',
        'other'
      )
    ),
  caption text,
  is_guardian_visible boolean not null default false,
  uploaded_by uuid references auth.users(id) on delete set null,

  created_at timestamptz not null default now(),
  unique(storage_bucket, storage_path)
);

create index if not exists diagnostic_files_order_idx
  on public.diagnostic_files(diagnostic_order_id, created_at);


create table if not exists public.diagnostic_audit_logs (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null
    references public.hospitals(id)
    on delete cascade,
  diagnostic_order_id bigint
    references public.diagnostic_orders(id)
    on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists diagnostic_audit_logs_order_idx
  on public.diagnostic_audit_logs(
    diagnostic_order_id,
    created_at desc
  );


-- updated_at 공통 함수가 없을 수 있어 검사 전용 함수로 생성
create or replace function public.pawu_touch_diagnostic_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists diagnostic_orders_touch_updated_at
  on public.diagnostic_orders;

create trigger diagnostic_orders_touch_updated_at
before update on public.diagnostic_orders
for each row
execute function public.pawu_touch_diagnostic_updated_at();

drop trigger if exists diagnostic_result_items_touch_updated_at
  on public.diagnostic_result_items;

create trigger diagnostic_result_items_touch_updated_at
before update on public.diagnostic_result_items
for each row
execute function public.pawu_touch_diagnostic_updated_at();


-- Storage bucket
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'diagnostic-files',
  'diagnostic-files',
  false,
  52428800,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/pdf',
    'video/mp4',
    'application/dicom',
    'application/octet-stream'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;


-- 병원 프로그램은 서버 API + service role만 사용
alter table public.diagnostic_orders enable row level security;
alter table public.diagnostic_result_items enable row level security;
alter table public.diagnostic_files enable row level security;
alter table public.diagnostic_audit_logs enable row level security;

-- 보호자 공개 SELECT 정책은 V8.0.0-C에서 추가
-- 현재는 클라이언트 직접 접근을 허용하지 않음

commit;
