-- PAWU V7.5.1
-- 기존 테이블이 일부 생성되어 있어도 안전하게 보완하는 전자차트 호환 마이그레이션
-- 기존 데이터 삭제 없음 / DROP 없음

begin;

-- =========================================================
-- 1. 병원 환자 테이블
-- =========================================================

create table if not exists public.hospital_patients (
  id bigint generated by default as identity primary key
);

alter table public.hospital_patients
  add column if not exists hospital_id bigint,
  add column if not exists pet_id bigint,
  add column if not exists guardian_user_id uuid,
  add column if not exists first_reservation_id bigint,
  add column if not exists patient_number text,
  add column if not exists memo text,
  add column if not exists last_visit_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'hospital_patients_hospital_id_fkey'
      and conrelid = 'public.hospital_patients'::regclass
  ) then
    alter table public.hospital_patients
      add constraint hospital_patients_hospital_id_fkey
      foreign key (hospital_id)
      references public.hospitals(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'hospital_patients_pet_id_fkey'
      and conrelid = 'public.hospital_patients'::regclass
  ) then
    alter table public.hospital_patients
      add constraint hospital_patients_pet_id_fkey
      foreign key (pet_id)
      references public.pets(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'hospital_patients_guardian_user_id_fkey'
      and conrelid = 'public.hospital_patients'::regclass
  ) then
    alter table public.hospital_patients
      add constraint hospital_patients_guardian_user_id_fkey
      foreign key (guardian_user_id)
      references auth.users(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'hospital_patients_first_reservation_id_fkey'
      and conrelid = 'public.hospital_patients'::regclass
  ) then
    alter table public.hospital_patients
      add constraint hospital_patients_first_reservation_id_fkey
      foreign key (first_reservation_id)
      references public.reservations(id)
      on delete set null;
  end if;
end
$$;

create unique index if not exists hospital_patients_hospital_pet_unique_idx
  on public.hospital_patients(hospital_id, pet_id);

create index if not exists hospital_patients_hospital_updated_idx
  on public.hospital_patients(hospital_id, updated_at desc);

-- =========================================================
-- 2. 전자차트 테이블
-- =========================================================

create table if not exists public.medical_records (
  id bigint generated by default as identity primary key
);

alter table public.medical_records
  add column if not exists hospital_id bigint,
  add column if not exists hospital_patient_id bigint,
  add column if not exists pet_id bigint,
  add column if not exists reservation_id bigint,
  add column if not exists veterinarian_user_id uuid,
  add column if not exists guardian_information text,
  add column if not exists ai_reference_summary text,
  add column if not exists chief_complaint text,
  add column if not exists subjective text,
  add column if not exists objective text,
  add column if not exists assessment text,
  add column if not exists plan text,
  add column if not exists diagnosis text,
  add column if not exists treatment text,
  add column if not exists follow_up text,
  add column if not exists veterinarian_note text,
  add column if not exists status text not null default 'draft',
  add column if not exists completed_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_hospital_id_fkey'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_hospital_id_fkey
      foreign key (hospital_id)
      references public.hospitals(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_hospital_patient_id_fkey'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_hospital_patient_id_fkey
      foreign key (hospital_patient_id)
      references public.hospital_patients(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_pet_id_fkey'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_pet_id_fkey
      foreign key (pet_id)
      references public.pets(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_reservation_id_fkey'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_reservation_id_fkey
      foreign key (reservation_id)
      references public.reservations(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_veterinarian_user_id_fkey'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_veterinarian_user_id_fkey
      foreign key (veterinarian_user_id)
      references auth.users(id)
      on delete set null;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_records_status_check'
      and conrelid = 'public.medical_records'::regclass
  ) then
    alter table public.medical_records
      add constraint medical_records_status_check
      check (status in ('draft', 'completed', 'locked'));
  end if;
end
$$;

create index if not exists medical_records_patient_created_idx
  on public.medical_records(hospital_patient_id, created_at desc);

create index if not exists medical_records_hospital_created_idx
  on public.medical_records(hospital_id, created_at desc);

create unique index if not exists medical_records_reservation_unique_idx
  on public.medical_records(reservation_id)
  where reservation_id is not null;

-- =========================================================
-- 3. 처방 테이블
-- =========================================================

create table if not exists public.medical_prescriptions (
  id bigint generated by default as identity primary key
);

alter table public.medical_prescriptions
  add column if not exists medical_record_id bigint,
  add column if not exists hospital_id bigint,
  add column if not exists medication_name text,
  add column if not exists dosage text,
  add column if not exists frequency text,
  add column if not exists duration text,
  add column if not exists route text,
  add column if not exists instructions text,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_prescriptions_medical_record_id_fkey'
      and conrelid = 'public.medical_prescriptions'::regclass
  ) then
    alter table public.medical_prescriptions
      add constraint medical_prescriptions_medical_record_id_fkey
      foreign key (medical_record_id)
      references public.medical_records(id)
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'medical_prescriptions_hospital_id_fkey'
      and conrelid = 'public.medical_prescriptions'::regclass
  ) then
    alter table public.medical_prescriptions
      add constraint medical_prescriptions_hospital_id_fkey
      foreign key (hospital_id)
      references public.hospitals(id)
      on delete cascade;
  end if;
end
$$;

create index if not exists medical_prescriptions_record_idx
  on public.medical_prescriptions(medical_record_id, created_at);

-- =========================================================
-- 4. 필수 컬럼 NOT NULL 보완
-- 기존 비정상 빈 데이터가 있을 수 있으므로 데이터가 없는 경우에만 적용
-- =========================================================

do $$
begin
  if not exists (select 1 from public.hospital_patients where hospital_id is null or pet_id is null) then
    alter table public.hospital_patients alter column hospital_id set not null;
    alter table public.hospital_patients alter column pet_id set not null;
  end if;

  if not exists (
    select 1
    from public.medical_records
    where hospital_id is null or hospital_patient_id is null or pet_id is null
  ) then
    alter table public.medical_records alter column hospital_id set not null;
    alter table public.medical_records alter column hospital_patient_id set not null;
    alter table public.medical_records alter column pet_id set not null;
  end if;

  if not exists (
    select 1
    from public.medical_prescriptions
    where medical_record_id is null or hospital_id is null or medication_name is null
  ) then
    alter table public.medical_prescriptions alter column medical_record_id set not null;
    alter table public.medical_prescriptions alter column hospital_id set not null;
    alter table public.medical_prescriptions alter column medication_name set not null;
  end if;
end
$$;

-- =========================================================
-- 5. RLS
-- =========================================================

alter table public.hospital_patients enable row level security;
alter table public.medical_records enable row level security;
alter table public.medical_prescriptions enable row level security;

commit;
