-- PAWU COMMUNICATION & AI V3
-- V1, V2 SQL 적용 후 실행하세요.

alter table public.medical_records
  add column if not exists ai_summary_updated_at timestamptz;

create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null unique references public.reservations(id) on delete cascade,
  guardian_user_id uuid not null references auth.users(id) on delete cascade,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint references public.pets(id) on delete set null,
  status text not null default 'open' check (status in ('open','closed','blocked')),
  last_message_at timestamptz,
  last_message_preview text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  sender_type text not null check (sender_type in ('guardian','hospital','system')),
  message_type text not null default 'text' check (message_type in ('text','image','video','file','system')),
  content text,
  file_name text,
  file_path text,
  public_url text,
  mime_type text,
  file_size bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists chat_conversations_guardian_idx
  on public.chat_conversations(guardian_user_id,last_message_at desc);

create index if not exists chat_conversations_hospital_idx
  on public.chat_conversations(hospital_id,last_message_at desc);

create index if not exists chat_messages_conversation_idx
  on public.chat_messages(conversation_id,created_at);

create table if not exists public.ai_symptom_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  pet_id bigint references public.pets(id) on delete set null,
  species text,
  symptom_text text not null,
  guide_level text not null check (guide_level in ('observe','urgent','emergency')),
  guide_result jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.hospital_verification_requests (
  id bigint generated by default as identity primary key,
  applicant_user_id uuid references auth.users(id) on delete set null,
  hospital_name text not null,
  business_number text,
  veterinarian_name text,
  license_number text,
  status text not null default 'pending'
    check (status in ('pending','reviewing','approved','needs_documents','rejected')),
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  risk_reasons text[] not null default '{}',
  document_paths text[] not null default '{}',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;
alter table public.ai_symptom_sessions enable row level security;
alter table public.hospital_verification_requests enable row level security;

drop policy if exists "participants read conversations" on public.chat_conversations;
create policy "participants read conversations"
on public.chat_conversations for select
to authenticated
using (
  guardian_user_id = auth.uid()
  or exists (
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = chat_conversations.hospital_id
      and hs.is_active = true
  )
  or exists (
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = chat_conversations.hospital_id
  )
);

drop policy if exists "participants read messages" on public.chat_messages;
create policy "participants read messages"
on public.chat_messages for select
to authenticated
using (
  exists (
    select 1 from public.chat_conversations cc
    where cc.id = chat_messages.conversation_id
      and (
        cc.guardian_user_id = auth.uid()
        or exists (
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = cc.hospital_id
            and hs.is_active = true
        )
        or exists (
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = cc.hospital_id
        )
      )
  )
);

drop policy if exists "users read own ai symptom sessions" on public.ai_symptom_sessions;
create policy "users read own ai symptom sessions"
on public.ai_symptom_sessions for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "users insert own ai symptom sessions" on public.ai_symptom_sessions;
create policy "users insert own ai symptom sessions"
on public.ai_symptom_sessions for insert
to authenticated
with check (user_id = auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'chat-attachments',
  'chat-attachments',
  true,
  26214400,
  array[
    'image/jpeg','image/png','image/webp','image/gif',
    'video/mp4','video/webm',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict(id) do update
set file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "authenticated upload chat attachments" on storage.objects;
create policy "authenticated upload chat attachments"
on storage.objects for insert
to authenticated
with check (bucket_id = 'chat-attachments');

drop policy if exists "authenticated read chat attachments" on storage.objects;
create policy "authenticated read chat attachments"
on storage.objects for select
to authenticated
using (bucket_id = 'chat-attachments');

alter publication supabase_realtime add table public.chat_messages;
