begin;

create table if not exists public.emr_records (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  reservation_id bigint references public.reservations(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft','finalized')),
  chief_complaint text,
  subjective text,
  objective text,
  assessment text,
  plan text,
  diagnosis_summary text,
  weight_kg numeric(8,3),
  temperature_c numeric(5,2),
  heart_rate integer,
  respiratory_rate integer,
  bcs numeric(4,1),
  crt_seconds numeric(5,2),
  next_visit_date date,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  finalized_by uuid references auth.users(id) on delete set null,
  finalized_at timestamptz,
  reopen_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.emr_records
  add column if not exists hospital_id bigint references public.hospitals(id) on delete cascade,
  add column if not exists pet_id bigint references public.pets(id) on delete restrict,
  add column if not exists reservation_id bigint references public.reservations(id) on delete set null,
  add column if not exists status text default 'draft',
  add column if not exists chief_complaint text,
  add column if not exists subjective text,
  add column if not exists objective text,
  add column if not exists assessment text,
  add column if not exists plan text,
  add column if not exists diagnosis_summary text,
  add column if not exists weight_kg numeric(8,3),
  add column if not exists temperature_c numeric(5,2),
  add column if not exists heart_rate integer,
  add column if not exists respiratory_rate integer,
  add column if not exists bcs numeric(4,1),
  add column if not exists crt_seconds numeric(5,2),
  add column if not exists next_visit_date date,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists updated_by uuid references auth.users(id) on delete set null,
  add column if not exists finalized_by uuid references auth.users(id) on delete set null,
  add column if not exists finalized_at timestamptz,
  add column if not exists reopen_reason text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create index if not exists emr_records_hospital_created_idx
  on public.emr_records(hospital_id, created_at desc);

create index if not exists emr_records_pet_created_idx
  on public.emr_records(pet_id, created_at desc);

create index if not exists emr_records_reservation_idx
  on public.emr_records(reservation_id)
  where reservation_id is not null;

create unique index if not exists emr_records_one_per_reservation_idx
  on public.emr_records(reservation_id)
  where reservation_id is not null;

alter table public.emr_records enable row level security;

drop policy if exists "hospital members read emr records" on public.emr_records;
create policy "hospital members read emr records"
on public.emr_records
for select to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = emr_records.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = emr_records.hospital_id
  )
);

grant select on public.emr_records to authenticated;
grant all on public.emr_records to service_role;
grant usage, select on sequence public.emr_records_id_seq to service_role;

notify pgrst, 'reload schema';

commit;
