-- PAWU INVENTORY AUTOMATION V6.1
-- V5 및 V6 적용 후 실행하세요.
-- 진료 항목별 예상 재고 사용량, 실제 사용량 검토, 확정 차감, 역분개를 추가합니다.

alter table if exists public.hospital_invoices
  add column if not exists inventory_finalized_at timestamptz,
  add column if not exists inventory_finalized_by uuid references auth.users(id) on delete set null,
  add column if not exists inventory_reversed_at timestamptz,
  add column if not exists inventory_reversed_by uuid references auth.users(id) on delete set null;

create table if not exists public.invoice_inventory_usage (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.hospital_invoices(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  planned_quantity numeric(14,4) not null default 0 check (planned_quantity >= 0),
  actual_quantity numeric(14,4) not null default 0 check (actual_quantity >= 0),
  status text not null default 'draft'
    check (status in ('draft','finalized','reversed')),
  note text,
  finalized_at timestamptz,
  finalized_by uuid references auth.users(id) on delete set null,
  reversed_at timestamptz,
  reversed_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(invoice_id, inventory_item_id)
);

create index if not exists invoice_inventory_usage_invoice_status_idx
  on public.invoice_inventory_usage(invoice_id, status);

create or replace function public.pawu_finalize_invoice_inventory(
  p_hospital_id bigint,
  p_invoice_id bigint,
  p_actor_user_id uuid,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage record;
  v_invoice record;
  v_count integer := 0;
begin
  select id, inventory_finalized_at, inventory_reversed_at
  into v_invoice
  from public.hospital_invoices
  where id = p_invoice_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '청구서를 찾지 못했습니다.';
  end if;

  if v_invoice.inventory_finalized_at is not null
     and v_invoice.inventory_reversed_at is null then
    raise exception '이미 재고 차감이 확정된 청구서입니다.';
  end if;

  if not exists(
    select 1
    from public.invoice_inventory_usage
    where invoice_id = p_invoice_id
      and status = 'draft'
  ) then
    raise exception '확정할 재고 사용량이 없습니다.';
  end if;

  for v_usage in
    select iu.id, iu.inventory_item_id, iu.actual_quantity
    from public.invoice_inventory_usage iu
    join public.inventory_items ii on ii.id = iu.inventory_item_id
    where iu.invoice_id = p_invoice_id
      and iu.status = 'draft'
      and ii.hospital_id = p_hospital_id
    order by iu.inventory_item_id
    for update of iu
  loop
    if v_usage.actual_quantity > 0 then
      perform public.pawu_apply_inventory_movement(
        p_hospital_id,
        v_usage.inventory_item_id,
        'invoice_use',
        -v_usage.actual_quantity,
        coalesce(p_reason, '진료 완료 재고 사용 확정'),
        'hospital_invoice',
        p_invoice_id,
        null,
        null,
        p_actor_user_id
      );
    end if;

    update public.invoice_inventory_usage
    set status = 'finalized',
        finalized_at = now(),
        finalized_by = p_actor_user_id,
        updated_at = now()
    where id = v_usage.id;

    v_count := v_count + 1;
  end loop;

  update public.hospital_invoices
  set inventory_finalized_at = now(),
      inventory_finalized_by = p_actor_user_id,
      inventory_reversed_at = null,
      inventory_reversed_by = null,
      updated_at = now()
  where id = p_invoice_id;

  return jsonb_build_object(
    'invoice_id', p_invoice_id,
    'finalized_usage_count', v_count
  );
end;
$$;

create or replace function public.pawu_reverse_invoice_inventory(
  p_hospital_id bigint,
  p_invoice_id bigint,
  p_actor_user_id uuid,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usage record;
  v_invoice record;
  v_count integer := 0;
begin
  select id, inventory_finalized_at, inventory_reversed_at
  into v_invoice
  from public.hospital_invoices
  where id = p_invoice_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '청구서를 찾지 못했습니다.';
  end if;

  if v_invoice.inventory_finalized_at is null then
    raise exception '재고 차감이 확정되지 않은 청구서입니다.';
  end if;

  if v_invoice.inventory_reversed_at is not null then
    raise exception '이미 역분개된 청구서입니다.';
  end if;

  for v_usage in
    select iu.id, iu.inventory_item_id, iu.actual_quantity
    from public.invoice_inventory_usage iu
    join public.inventory_items ii on ii.id = iu.inventory_item_id
    where iu.invoice_id = p_invoice_id
      and iu.status = 'finalized'
      and ii.hospital_id = p_hospital_id
    order by iu.inventory_item_id
    for update of iu
  loop
    if v_usage.actual_quantity > 0 then
      perform public.pawu_apply_inventory_movement(
        p_hospital_id,
        v_usage.inventory_item_id,
        'reversal',
        v_usage.actual_quantity,
        coalesce(p_reason, '청구 취소 또는 수정에 따른 재고 복구'),
        'hospital_invoice',
        p_invoice_id,
        null,
        null,
        p_actor_user_id
      );
    end if;

    update public.invoice_inventory_usage
    set status = 'reversed',
        reversed_at = now(),
        reversed_by = p_actor_user_id,
        updated_at = now()
    where id = v_usage.id;

    v_count := v_count + 1;
  end loop;

  update public.hospital_invoices
  set inventory_reversed_at = now(),
      inventory_reversed_by = p_actor_user_id,
      updated_at = now()
  where id = p_invoice_id;

  return jsonb_build_object(
    'invoice_id', p_invoice_id,
    'reversed_usage_count', v_count
  );
end;
$$;

alter table public.invoice_inventory_usage enable row level security;

drop policy if exists "hospital members read invoice inventory usage"
on public.invoice_inventory_usage;

create policy "hospital members read invoice inventory usage"
on public.invoice_inventory_usage for select to authenticated
using (
  exists(
    select 1
    from public.hospital_invoices hi
    where hi.id = invoice_inventory_usage.invoice_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = hi.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = hi.hospital_id
        )
      )
  )
);

-- 서버 API는 service-role 클라이언트를 사용해 작성 및 확정합니다.
-- 클라이언트에서 inventory_items.current_quantity를 직접 변경하지 마세요.
-- 청구서 생성 시 재고를 차감하지 않고 실제 사용량 검토 후 확정합니다.
-- 차감 취소는 기존 이력을 삭제하지 않고 reversal 입출고 이력을 추가합니다.
