-- PAWU V7.4.0
-- 진료 준비 묶음 + 이벤트 중요도 + 사전 요약 저장 기반

alter table public.pet_health_events
  add column if not exists priority text not null default 'normal';

alter table public.pet_health_events
  drop constraint if exists pet_health_events_priority_check;

alter table public.pet_health_events
  add constraint pet_health_events_priority_check
  check (priority in ('emergency', 'high', 'normal', 'reference'));

create index if not exists pet_health_events_pet_priority_occurred_idx
  on public.pet_health_events(pet_id, priority, occurred_at desc);

-- 기존 이벤트의 종류/정도에 따라 초기 중요도 자동 보정
update public.pet_health_events
set priority = case
  when event_type in ('seizure', 'accident') or severity = 'severe'
    then 'emergency'
  when event_type in (
    'vomiting',
    'diarrhea',
    'appetite_loss',
    'water_change',
    'cough',
    'limping'
  ) or severity = 'moderate'
    then 'high'
  when event_type in ('hospital_visit', 'weight')
    then 'reference'
  else 'normal'
end
where priority = 'normal';

create table if not exists public.visit_preparations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete cascade,
  reservation_id bigint references public.reservations(id) on delete set null,
  title text not null,
  main_concern text,
  status text not null default 'draft'
    check (status in ('draft', 'ready', 'linked', 'archived')),
  generated_summary text,
  generated_timeline text,
  generated_key_points text,
  summary_version text not null default 'rule-v1',
  generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists visit_preparations_user_pet_created_idx
  on public.visit_preparations(user_id, pet_id, created_at desc);

create index if not exists visit_preparations_reservation_idx
  on public.visit_preparations(reservation_id)
  where reservation_id is not null;

create table if not exists public.visit_preparation_events (
  id bigint generated by default as identity primary key,
  visit_preparation_id bigint not null
    references public.visit_preparations(id) on delete cascade,
  event_id bigint not null
    references public.pet_health_events(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (visit_preparation_id, event_id)
);

create index if not exists visit_preparation_events_preparation_idx
  on public.visit_preparation_events(visit_preparation_id, sort_order);

alter table public.visit_preparations enable row level security;
alter table public.visit_preparation_events enable row level security;

drop policy if exists "guardians read own visit preparations"
on public.visit_preparations;

create policy "guardians read own visit preparations"
on public.visit_preparations
for select
using (auth.uid() = user_id);

drop policy if exists "guardians create own visit preparations"
on public.visit_preparations;

create policy "guardians create own visit preparations"
on public.visit_preparations
for insert
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.pets p
    where p.id = pet_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "guardians update own visit preparations"
on public.visit_preparations;

create policy "guardians update own visit preparations"
on public.visit_preparations
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "guardians delete own visit preparations"
on public.visit_preparations;

create policy "guardians delete own visit preparations"
on public.visit_preparations
for delete
using (auth.uid() = user_id);

drop policy if exists "guardians read own preparation events"
on public.visit_preparation_events;

create policy "guardians read own preparation events"
on public.visit_preparation_events
for select
using (
  exists (
    select 1
    from public.visit_preparations vp
    where vp.id = visit_preparation_id
      and vp.user_id = auth.uid()
  )
);

drop policy if exists "guardians create own preparation events"
on public.visit_preparation_events;

create policy "guardians create own preparation events"
on public.visit_preparation_events
for insert
with check (
  exists (
    select 1
    from public.visit_preparations vp
    join public.pet_health_events e on e.id = event_id
    where vp.id = visit_preparation_id
      and vp.user_id = auth.uid()
      and e.user_id = auth.uid()
      and e.pet_id = vp.pet_id
  )
);

drop policy if exists "guardians delete own preparation events"
on public.visit_preparation_events;

create policy "guardians delete own preparation events"
on public.visit_preparation_events
for delete
using (
  exists (
    select 1
    from public.visit_preparations vp
    where vp.id = visit_preparation_id
      and vp.user_id = auth.uid()
  )
);
