-- PAWU V6.5.6 접수·대기 시스템
create table if not exists public.hospital_waiting_entries (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  reservation_id bigint null references public.reservations(id) on delete set null,
  pet_id bigint null references public.pets(id) on delete set null,
  waiting_date date not null default current_date,
  waiting_number integer not null,
  pet_name text not null,
  guardian_name text,
  phone text,
  visit_reason text,
  symptoms text,
  source text not null default 'walk_in' check (source in ('reservation','walk_in')),
  priority text not null default 'normal' check (priority in ('emergency','urgent','normal')),
  status text not null default 'waiting' check (status in ('waiting','called','in_consultation','exam','billing','completed','cancelled','no_show')),
  room_name text,
  assigned_staff_name text,
  call_count integer not null default 0,
  checked_in_at timestamptz not null default now(),
  called_at timestamptz,
  consultation_started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (hospital_id, waiting_date, waiting_number),
  unique (hospital_id, reservation_id)
);

create index if not exists hospital_waiting_entries_board_idx
  on public.hospital_waiting_entries (hospital_id, waiting_date, status, priority, waiting_number);
create index if not exists hospital_waiting_entries_pet_idx
  on public.hospital_waiting_entries (hospital_id, pet_id, checked_in_at desc);

create or replace function public.pawu_next_waiting_number(p_hospital_id bigint, p_date date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_next integer;
begin
  perform pg_advisory_xact_lock(p_hospital_id, (p_date - date '2000-01-01'));
  select coalesce(max(waiting_number), 0) + 1 into v_next
  from public.hospital_waiting_entries
  where hospital_id = p_hospital_id and waiting_date = p_date;
  return v_next;
end;
$$;

alter table public.hospital_waiting_entries enable row level security;
comment on table public.hospital_waiting_entries is 'PAWU V6.5.6 병원 접수 및 실시간 대기 보드';
