-- PAWU V7.3: 반려동물 생활 프로필 + 날짜별 건강 이벤트

create table if not exists public.pet_lifestyle_profiles (
  pet_id bigint primary key references public.pets(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_brand text not null,
  food_product text not null,
  feeding_times_per_day integer not null check (feeding_times_per_day between 1 and 12),
  feeding_amount_per_day_g numeric(8,2),
  treats text,
  allergies text,
  current_medications text,
  supplements text,
  neutered boolean,
  living_environment text check (living_environment in ('indoor','outdoor','mixed')),
  primary_hospital_id bigint references public.hospitals(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pet_health_events (
  id bigint generated by default as identity primary key,
  pet_id bigint not null references public.pets(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  occurred_at timestamptz not null,
  event_type text not null check (event_type in (
    'vomiting','diarrhea','appetite_loss','water_change','cough','sneeze',
    'eye','ear','skin','limping','seizure','food_change','medication_change',
    'weight','hospital_visit','accident','other'
  )),
  severity text check (severity in ('mild','moderate','severe')),
  count_value integer check (count_value is null or count_value >= 0),
  title text not null,
  note text,
  photo_urls text[] not null default '{}',
  video_urls text[] not null default '{}',
  share_with_hospital boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pet_lifestyle_profiles_user_id_idx
  on public.pet_lifestyle_profiles(user_id);
create index if not exists pet_health_events_pet_occurred_idx
  on public.pet_health_events(pet_id, occurred_at desc);
create index if not exists pet_health_events_user_id_idx
  on public.pet_health_events(user_id);

alter table public.pet_lifestyle_profiles enable row level security;
alter table public.pet_health_events enable row level security;

drop policy if exists "pet lifestyle owner select" on public.pet_lifestyle_profiles;
create policy "pet lifestyle owner select" on public.pet_lifestyle_profiles
for select using (auth.uid() = user_id);
drop policy if exists "pet lifestyle owner insert" on public.pet_lifestyle_profiles;
create policy "pet lifestyle owner insert" on public.pet_lifestyle_profiles
for insert with check (auth.uid() = user_id);
drop policy if exists "pet lifestyle owner update" on public.pet_lifestyle_profiles;
create policy "pet lifestyle owner update" on public.pet_lifestyle_profiles
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "pet lifestyle owner delete" on public.pet_lifestyle_profiles;
create policy "pet lifestyle owner delete" on public.pet_lifestyle_profiles
for delete using (auth.uid() = user_id);

drop policy if exists "pet event owner select" on public.pet_health_events;
create policy "pet event owner select" on public.pet_health_events
for select using (auth.uid() = user_id);
drop policy if exists "pet event owner insert" on public.pet_health_events;
create policy "pet event owner insert" on public.pet_health_events
for insert with check (auth.uid() = user_id);
drop policy if exists "pet event owner update" on public.pet_health_events;
create policy "pet event owner update" on public.pet_health_events
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "pet event owner delete" on public.pet_health_events;
create policy "pet event owner delete" on public.pet_health_events
for delete using (auth.uid() = user_id);
