create table if not exists public.hospital_beds (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 name text not null, ward text, bed_type text not null default 'general' check (bed_type in ('general','icu','isolation')),
 is_active boolean not null default true, occupied boolean not null default false, created_at timestamptz not null default now(), unique(hospital_id,name)
);
create table if not exists public.hospital_admissions (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 patient_id bigint, patient_name text not null, guardian_name text, guardian_phone text, bed_id bigint references public.hospital_beds(id), bed_name text,
 reason text, status text not null default 'admitted' check(status in('planned','admitted','discharged','cancelled')),
 admitted_at timestamptz default now(), expected_discharge_at timestamptz, discharged_at timestamptz, created_by uuid, discharged_by uuid, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.hospital_admission_tasks (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 admission_id bigint not null references public.hospital_admissions(id) on delete cascade, title text not null, due_at timestamptz not null,
 status text not null default 'pending' check(status in('pending','done','cancelled')), assignee_name text, note text, created_by uuid, completed_by uuid, completed_at timestamptz, created_at timestamptz default now()
);
create table if not exists public.hospital_surgeries (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 patient_id bigint, patient_name text not null, admission_id bigint references public.hospital_admissions(id) on delete set null,
 title text not null, surgeon_name text, operating_room text, scheduled_start timestamptz not null, scheduled_end timestamptz,
 status text not null default 'scheduled' check(status in('scheduled','ready','in_progress','recovery','completed','cancelled')),
 consent_confirmed boolean default false, fasting_confirmed boolean default false, preop_test_confirmed boolean default false, anesthesia_confirmed boolean default false,
 note text, created_by uuid, created_at timestamptz default now(), updated_at timestamptz default now()
);
create index if not exists hospital_admissions_active_idx on public.hospital_admissions(hospital_id,status);
create index if not exists hospital_tasks_due_idx on public.hospital_admission_tasks(hospital_id,due_at);
create index if not exists hospital_surgeries_start_idx on public.hospital_surgeries(hospital_id,scheduled_start);

create or replace function public.pawu_admit_patient_v659(p_hospital_id bigint,p_patient_id bigint,p_patient_name text,p_guardian_name text,p_guardian_phone text,p_bed_id bigint,p_reason text,p_expected_discharge_at timestamptz,p_actor_id uuid)
returns bigint language plpgsql security definer set search_path=public as $$ declare v_bed hospital_beds%rowtype; v_id bigint; begin
 select * into v_bed from hospital_beds where id=p_bed_id and hospital_id=p_hospital_id for update;
 if not found or v_bed.occupied or not v_bed.is_active then raise exception '사용 가능한 병상이 아닙니다.'; end if;
 insert into hospital_admissions(hospital_id,patient_id,patient_name,guardian_name,guardian_phone,bed_id,bed_name,reason,status,admitted_at,expected_discharge_at,created_by)
 values(p_hospital_id,p_patient_id,p_patient_name,p_guardian_name,p_guardian_phone,p_bed_id,v_bed.name,p_reason,'admitted',now(),p_expected_discharge_at,p_actor_id) returning id into v_id;
 update hospital_beds set occupied=true where id=p_bed_id; return v_id; end $$;
create or replace function public.pawu_discharge_patient_v659(p_hospital_id bigint,p_admission_id bigint,p_actor_id uuid)
returns void language plpgsql security definer set search_path=public as $$ declare v_bed_id bigint; begin
 select bed_id into v_bed_id from hospital_admissions where id=p_admission_id and hospital_id=p_hospital_id and status='admitted' for update;
 if not found then raise exception '퇴원 가능한 입원 기록이 없습니다.'; end if;
 update hospital_admissions set status='discharged',discharged_at=now(),discharged_by=p_actor_id,updated_at=now() where id=p_admission_id;
 update hospital_beds set occupied=false where id=v_bed_id and hospital_id=p_hospital_id; end $$;

alter table public.hospital_beds enable row level security;
alter table public.hospital_admissions enable row level security;
alter table public.hospital_admission_tasks enable row level security;
alter table public.hospital_surgeries enable row level security;
