-- PAWU PROFILES & BILLING V5
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text, display_name text,
  role text not null default 'guardian' check (role in ('guardian','hospital','admin')),
  status text not null default 'active' check (status in ('active','suspended','withdrawn','dormant')),
  last_login_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists profiles_role_status_idx on public.profiles(role,status);
insert into public.profiles(id,email,display_name,role,status,created_at)
select u.id,u.email,coalesce(u.raw_user_meta_data->>'name',split_part(coalesce(u.email,''),'@',1)),
case when exists(select 1 from public.master_admins m where m.user_id=u.id) then 'admin' when exists(select 1 from public.hospital_staff s where s.user_id=u.id and s.is_active=true) or exists(select 1 from public.hospital_admins a where a.user_id=u.id) then 'hospital' else 'guardian' end,
'active',u.created_at from auth.users u on conflict(id) do update set email=excluded.email,role=excluded.role,updated_at=now();
create or replace function public.pawu_create_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,display_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name',split_part(coalesce(new.email,''),'@',1))) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists pawu_auth_user_profile_trigger on auth.users; create trigger pawu_auth_user_profile_trigger after insert on auth.users for each row execute function public.pawu_create_profile();

create table if not exists public.hospital_service_items (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 name text not null, category text not null, description text, default_price integer not null default 0 check(default_price>=0),
 species_scope text not null default 'all' check(species_scope in ('all','dog','cat','other')), is_favorite boolean not null default false,
 is_active boolean not null default true, sort_order integer not null default 0, created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(hospital_id,name)
);
create index if not exists hospital_service_items_lookup_idx on public.hospital_service_items(hospital_id,is_active,category,sort_order);
create table if not exists public.hospital_invoices (
 id bigint generated by default as identity primary key, hospital_id bigint not null references public.hospitals(id) on delete cascade,
 reservation_id bigint references public.reservations(id) on delete set null, pet_id bigint not null references public.pets(id) on delete restrict,
 guardian_user_id uuid references auth.users(id) on delete set null, status text not null default 'draft' check(status in ('draft','payment_pending','paid','cancelled','refunded')),
 subtotal_amount integer not null default 0 check(subtotal_amount>=0), discount_amount integer not null default 0 check(discount_amount>=0), total_amount integer not null default 0 check(total_amount>=0),
 memo text, payment_method text, payment_provider text, payment_transaction_id text, payment_requested_at timestamptz, paid_at timestamptz,
 created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists hospital_invoices_hospital_idx on public.hospital_invoices(hospital_id,status,created_at desc);
create index if not exists hospital_invoices_guardian_idx on public.hospital_invoices(guardian_user_id,created_at desc);
create table if not exists public.hospital_invoice_items (
 id bigint generated by default as identity primary key, invoice_id bigint not null references public.hospital_invoices(id) on delete cascade,
 service_item_id bigint references public.hospital_service_items(id) on delete set null, item_name text not null, unit_price integer not null default 0,
 quantity integer not null default 1 check(quantity>0), discount_amount integer not null default 0, additional_amount integer not null default 0,
 line_amount integer not null default 0, note text, sort_order integer not null default 0, created_at timestamptz not null default now()
);
create index if not exists hospital_invoice_items_invoice_idx on public.hospital_invoice_items(invoice_id,sort_order);
update public.hospital_staff set permissions=coalesce(permissions,'{}'::jsonb)||case when role='owner' then '{"manage_billing_catalog":true,"create_invoices":true,"manage_payments":true}'::jsonb when role in ('veterinarian','nurse') then '{"create_invoices":true}'::jsonb when role='receptionist' then '{"create_invoices":true,"manage_payments":true}'::jsonb else '{}'::jsonb end;
alter table public.profiles enable row level security; alter table public.hospital_service_items enable row level security; alter table public.hospital_invoices enable row level security; alter table public.hospital_invoice_items enable row level security;
drop policy if exists "profile own read" on public.profiles; create policy "profile own read" on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from public.master_admins m where m.user_id=auth.uid()));
drop policy if exists "profile own update" on public.profiles; create policy "profile own update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists "service catalog hospital read" on public.hospital_service_items; create policy "service catalog hospital read" on public.hospital_service_items for select to authenticated using(exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=public.hospital_service_items.hospital_id and s.is_active=true) or exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=public.hospital_service_items.hospital_id));
drop policy if exists "guardian invoice read" on public.hospital_invoices; create policy "guardian invoice read" on public.hospital_invoices for select to authenticated using(guardian_user_id=auth.uid() or exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=public.hospital_invoices.hospital_id and s.is_active=true) or exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=public.hospital_invoices.hospital_id));
drop policy if exists "invoice item participant read" on public.hospital_invoice_items; create policy "invoice item participant read" on public.hospital_invoice_items for select to authenticated using(exists(select 1 from public.hospital_invoices i where i.id=invoice_id and (i.guardian_user_id=auth.uid() or exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=i.hospital_id and s.is_active=true) or exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=i.hospital_id))));
