create table if not exists public.hospital_visit_reviews (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  guardian_user_id uuid not null references auth.users(id) on delete cascade,
  pet_id bigint references public.pets(id) on delete set null,
  visit_date date not null,
  title text,
  content text not null check (char_length(trim(content)) between 5 and 3000),
  image_paths text[] not null default '{}',
  hospital_reply text,
  hospital_replied_at timestamptz,
  hospital_replied_by uuid references auth.users(id) on delete set null,
  status text not null default 'published' check (status in ('published','hidden','deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reservation_id)
);

create index if not exists hospital_visit_reviews_hospital_created_idx
  on public.hospital_visit_reviews(hospital_id, created_at desc);
create index if not exists hospital_visit_reviews_guardian_idx
  on public.hospital_visit_reviews(guardian_user_id, created_at desc);

alter table public.hospital_visit_reviews enable row level security;

drop policy if exists "published reviews are public" on public.hospital_visit_reviews;
create policy "published reviews are public"
  on public.hospital_visit_reviews for select
  using (status = 'published');

drop policy if exists "guardians manage own reviews" on public.hospital_visit_reviews;
create policy "guardians manage own reviews"
  on public.hospital_visit_reviews for all
  using (auth.uid() = guardian_user_id)
  with check (auth.uid() = guardian_user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'visit-review-images',
  'visit-review-images',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
