begin;

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.hospital_staff
set permissions =
  coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') in ('owner','veterinarian','nurse') then
      '{"view_dispensing":true,"manage_dispensing":true}'::jsonb
    when coalesce(role, '') in ('assistant','receptionist') then
      '{"view_dispensing":true,"manage_dispensing":false}'::jsonb
    else
      '{"view_dispensing":false,"manage_dispensing":false}'::jsonb
  end;

create table if not exists public.dispensing_jobs (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  medication_order_id bigint not null unique
    references public.medication_orders(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  status text not null default 'queued'
    check (status in ('queued','in_progress','completed','cancelled')),
  priority integer not null default 0,
  queued_at timestamptz not null default now(),
  started_at timestamptz,
  started_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  guardian_instruction_snapshot text,
  completion_note text,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dispensing_jobs_hospital_status_queue_idx
  on public.dispensing_jobs(hospital_id, status, priority desc, queued_at);

create index if not exists dispensing_jobs_pet_created_idx
  on public.dispensing_jobs(pet_id, created_at desc);

create table if not exists public.dispensing_items (
  id bigint generated by default as identity primary key,
  dispensing_job_id bigint not null
    references public.dispensing_jobs(id) on delete cascade,
  medication_order_item_id bigint not null unique
    references public.medication_order_items(id) on delete restrict,
  medication_name text not null,
  inventory_item_id bigint references public.inventory_items(id) on delete restrict,
  requested_quantity numeric(14,4),
  quantity_unit text,
  dispensed_quantity numeric(14,4),
  lot_id bigint references public.inventory_lots(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending','dispensed','cancelled')),
  warning_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dispensing_items_job_idx
  on public.dispensing_items(dispensing_job_id, id);

create index if not exists dispensing_items_inventory_idx
  on public.dispensing_items(inventory_item_id);

create table if not exists public.dispensing_audit_logs (
  id bigint generated by default as identity primary key,
  dispensing_job_id bigint not null
    references public.dispensing_jobs(id) on delete cascade,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists dispensing_audit_logs_job_created_idx
  on public.dispensing_audit_logs(dispensing_job_id, created_at desc);

create or replace function public.pawu_create_dispensing_job_for_order(
  p_medication_order_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.medication_orders%rowtype;
  v_job_id bigint;
begin
  select *
  into v_order
  from public.medication_orders
  where id = p_medication_order_id;

  if not found or v_order.status <> 'finalized' then
    return null;
  end if;

  insert into public.dispensing_jobs(
    hospital_id, medication_order_id, pet_id,
    guardian_instruction_snapshot
  )
  values(
    v_order.hospital_id, v_order.id, v_order.pet_id,
    v_order.guardian_note
  )
  on conflict (medication_order_id) do update
    set guardian_instruction_snapshot =
      excluded.guardian_instruction_snapshot,
        updated_at = now()
  returning id into v_job_id;

  insert into public.dispensing_items(
    dispensing_job_id, medication_order_item_id,
    medication_name, inventory_item_id,
    requested_quantity, quantity_unit, warning_note
  )
  select
    v_job_id, moi.id, moi.medication_name,
    moi.inventory_item_id, moi.total_quantity,
    moi.dose_unit,
    case
      when moi.inventory_item_id is null then '재고 품목 미연결'
      when moi.total_quantity is null then '총 처방량 미입력'
      else null
    end
  from public.medication_order_items moi
  where moi.medication_order_id = p_medication_order_id
  on conflict (medication_order_item_id) do update
    set medication_name = excluded.medication_name,
        inventory_item_id = excluded.inventory_item_id,
        requested_quantity = excluded.requested_quantity,
        quantity_unit = excluded.quantity_unit,
        warning_note = excluded.warning_note,
        updated_at = now();

  return v_job_id;
end;
$$;

create or replace function public.pawu_medication_order_dispensing_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'finalized'
     and (tg_op = 'INSERT' or old.status is distinct from new.status) then
    perform public.pawu_create_dispensing_job_for_order(new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists medication_order_create_dispensing_job
  on public.medication_orders;

create trigger medication_order_create_dispensing_job
after insert or update of status
on public.medication_orders
for each row
execute function public.pawu_medication_order_dispensing_trigger();

select public.pawu_create_dispensing_job_for_order(id)
from public.medication_orders
where status = 'finalized';

create or replace function public.pawu_complete_dispensing_job(
  p_hospital_id bigint,
  p_dispensing_job_id bigint,
  p_actor_user_id uuid,
  p_completion_note text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job public.dispensing_jobs%rowtype;
  v_item public.dispensing_items%rowtype;
  v_payload jsonb;
  v_quantity numeric(14,4);
  v_lot_id bigint;
  v_inventory public.inventory_items%rowtype;
  v_lot public.inventory_lots%rowtype;
  v_before numeric(14,4);
  v_after numeric(14,4);
begin
  select *
  into v_job
  from public.dispensing_jobs
  where id = p_dispensing_job_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '조제 작업을 찾지 못했습니다.';
  end if;

  if v_job.status not in ('queued','in_progress') then
    raise exception '대기 또는 진행 중인 조제만 완료할 수 있습니다.';
  end if;

  if jsonb_typeof(p_items) <> 'array' then
    raise exception '조제 품목 정보가 올바르지 않습니다.';
  end if;

  for v_item in
    select *
    from public.dispensing_items
    where dispensing_job_id = p_dispensing_job_id
    order by id
    for update
  loop
    select elem
    into v_payload
    from jsonb_array_elements(p_items) elem
    where (elem->>'id')::bigint = v_item.id
    limit 1;

    if v_payload is null then
      raise exception '조제 수량이 누락된 품목이 있습니다: %',
        v_item.medication_name;
    end if;

    v_quantity := (v_payload->>'dispensedQuantity')::numeric;
    v_lot_id := nullif(v_payload->>'lotId', '')::bigint;

    if v_quantity is null or v_quantity <= 0 then
      raise exception '조제 수량은 0보다 커야 합니다: %',
        v_item.medication_name;
    end if;

    if v_item.inventory_item_id is null then
      raise exception '재고 품목이 연결되지 않았습니다: %',
        v_item.medication_name;
    end if;

    select *
    into v_inventory
    from public.inventory_items
    where id = v_item.inventory_item_id
      and hospital_id = p_hospital_id
      and is_active = true
    for update;

    if not found then
      raise exception '재고 품목을 찾지 못했습니다: %',
        v_item.medication_name;
    end if;

    v_before := v_inventory.current_quantity;
    v_after := v_before - v_quantity;

    if v_after < 0 then
      raise exception '재고가 부족합니다: %, 현재 %, 필요 %',
        v_item.medication_name, v_before, v_quantity;
    end if;

    if v_lot_id is not null then
      select *
      into v_lot
      from public.inventory_lots
      where id = v_lot_id
        and inventory_item_id = v_item.inventory_item_id
      for update;

      if not found then
        raise exception '유효한 LOT를 찾지 못했습니다: %',
          v_item.medication_name;
      end if;

      if v_lot.expires_on is not null
         and v_lot.expires_on < current_date then
        raise exception '유효기간이 지난 LOT입니다: %',
          v_item.medication_name;
      end if;

      if v_lot.remaining_quantity < v_quantity then
        raise exception 'LOT 재고가 부족합니다: %',
          v_item.medication_name;
      end if;

      update public.inventory_lots
      set remaining_quantity = remaining_quantity - v_quantity
      where id = v_lot_id;
    elsif v_inventory.management_type in ('lot','strict') then
      raise exception 'LOT 관리 품목은 LOT 선택이 필요합니다: %',
        v_item.medication_name;
    end if;

    update public.inventory_items
    set current_quantity = v_after,
        updated_at = now()
    where id = v_item.inventory_item_id;

    insert into public.inventory_movements(
      inventory_item_id, lot_id, movement_type,
      quantity_change, quantity_before, quantity_after,
      reason, reference_type, reference_id, created_by
    )
    values(
      v_item.inventory_item_id, v_lot_id, 'use',
      -v_quantity, v_before, v_after,
      '처방 조제 완료', 'dispensing_job',
      p_dispensing_job_id, p_actor_user_id
    );

    update public.dispensing_items
    set dispensed_quantity = v_quantity,
        lot_id = v_lot_id,
        status = 'dispensed',
        updated_at = now()
    where id = v_item.id;
  end loop;

  if not exists(
    select 1
    from public.dispensing_items
    where dispensing_job_id = p_dispensing_job_id
  ) then
    raise exception '조제할 품목이 없습니다.';
  end if;

  update public.dispensing_jobs
  set status = 'completed',
      completed_at = now(),
      completed_by = p_actor_user_id,
      completion_note = p_completion_note,
      updated_at = now()
  where id = p_dispensing_job_id;

  insert into public.dispensing_audit_logs(
    dispensing_job_id, action, details, actor_user_id
  )
  values(
    p_dispensing_job_id,
    'completed',
    jsonb_build_object('items', p_items, 'note', p_completion_note),
    p_actor_user_id
  );

  return jsonb_build_object(
    'dispensing_job_id', p_dispensing_job_id,
    'status', 'completed'
  );
end;
$$;

revoke all on function public.pawu_complete_dispensing_job(
  bigint,bigint,uuid,text,jsonb
) from public;
grant execute on function public.pawu_complete_dispensing_job(
  bigint,bigint,uuid,text,jsonb
) to service_role;

alter table public.dispensing_jobs enable row level security;
alter table public.dispensing_items enable row level security;
alter table public.dispensing_audit_logs enable row level security;

drop policy if exists "hospital members read dispensing jobs"
  on public.dispensing_jobs;
create policy "hospital members read dispensing jobs"
on public.dispensing_jobs
for select to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = dispensing_jobs.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = dispensing_jobs.hospital_id
  )
);

drop policy if exists "hospital members read dispensing items"
  on public.dispensing_items;
create policy "hospital members read dispensing items"
on public.dispensing_items
for select to authenticated
using (
  exists(
    select 1 from public.dispensing_jobs dj
    where dj.id = dispensing_items.dispensing_job_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = dj.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = dj.hospital_id
        )
      )
  )
);

drop policy if exists "hospital members read dispensing logs"
  on public.dispensing_audit_logs;
create policy "hospital members read dispensing logs"
on public.dispensing_audit_logs
for select to authenticated
using (
  exists(
    select 1 from public.dispensing_jobs dj
    where dj.id = dispensing_audit_logs.dispensing_job_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = dj.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = dj.hospital_id
        )
      )
  )
);

commit;
