-- PAWU PRESCRIPTION & MEDICATION V6.5 REBUILD
--
-- 핵심 변경:
-- 기존 프로젝트에 이미 존재할 수 있는 public.prescriptions 테이블을 절대 변경하지 않습니다.
-- 신규 처방 시스템은 충돌 방지를 위해 medication_orders 계열 테이블을 사용합니다.
-- V6.5 또는 HF1이 일부 실행되었더라도 기존 테이블과 데이터는 삭제하지 않습니다.

begin;

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.hospital_staff
set permissions =
  coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') in ('owner','veterinarian') then
      '{"view_prescription":true,"write_prescription":true,"finalize_prescription":true}'::jsonb
    when coalesce(role, '') in ('nurse','assistant') then
      '{"view_prescription":true,"write_prescription":true,"finalize_prescription":false}'::jsonb
    else
      '{"view_prescription":true,"write_prescription":false,"finalize_prescription":false}'::jsonb
  end;

create table if not exists public.medication_orders (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  pet_id bigint not null references public.pets(id) on delete restrict,
  emr_record_id bigint references public.emr_records(id) on delete set null,
  reservation_id bigint references public.reservations(id) on delete set null,
  status text not null default 'draft'
    check (status in ('draft','finalized','cancelled')),
  diagnosis_summary text,
  guardian_note text,
  guardian_visible boolean not null default false,
  start_date date,
  end_date date,
  finalized_at timestamptz,
  finalized_by uuid references auth.users(id) on delete set null,
  cancellation_reason text,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medication_orders_hospital_status_created_idx
  on public.medication_orders(hospital_id, status, created_at desc);

create index if not exists medication_orders_pet_created_idx
  on public.medication_orders(pet_id, created_at desc);

create index if not exists medication_orders_emr_idx
  on public.medication_orders(emr_record_id);

create table if not exists public.medication_order_items (
  id bigint generated by default as identity primary key,
  medication_order_id bigint not null
    references public.medication_orders(id) on delete cascade,
  medication_name text not null,
  active_ingredient text,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  dose_amount numeric not null check (dose_amount > 0),
  dose_unit text not null,
  route text not null,
  frequency text not null,
  duration_days integer check (duration_days is null or duration_days > 0),
  total_quantity numeric check (total_quantity is null or total_quantity > 0),
  instructions text,
  warning_note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists medication_order_items_order_sort_idx
  on public.medication_order_items(medication_order_id, sort_order, id);

create index if not exists medication_order_items_inventory_idx
  on public.medication_order_items(inventory_item_id);

create table if not exists public.medication_order_templates (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  name text not null,
  category text,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, name)
);

create index if not exists medication_order_templates_hospital_active_idx
  on public.medication_order_templates(hospital_id, is_active, name);

create table if not exists public.medication_order_template_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null
    references public.medication_order_templates(id) on delete cascade,
  medication_name text not null,
  active_ingredient text,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  dose_amount numeric,
  dose_unit text,
  route text,
  frequency text,
  duration_days integer,
  total_quantity numeric,
  instructions text,
  warning_note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists medication_order_template_items_template_sort_idx
  on public.medication_order_template_items(template_id, sort_order, id);

create table if not exists public.medication_order_audit_logs (
  id bigint generated by default as identity primary key,
  medication_order_id bigint not null
    references public.medication_orders(id) on delete cascade,
  action text not null
    check (action in ('created','updated','finalized','reopened','cancelled')),
  reason text,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists medication_order_audit_logs_order_idx
  on public.medication_order_audit_logs(medication_order_id, created_at desc);

create or replace function public.pawu_reopen_medication_order(
  p_hospital_id bigint,
  p_medication_order_id bigint,
  p_actor_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text;
begin
  if coalesce(trim(p_reason), '') = '' then
    raise exception '재개 사유가 필요합니다.';
  end if;

  select status
  into v_status
  from public.medication_orders
  where id = p_medication_order_id
    and hospital_id = p_hospital_id
  for update;

  if not found then
    raise exception '처방전을 찾지 못했습니다.';
  end if;

  if v_status <> 'finalized' then
    raise exception '확정된 처방전만 다시 열 수 있습니다.';
  end if;

  update public.medication_orders
  set status = 'draft',
      finalized_at = null,
      finalized_by = null,
      updated_by = p_actor_user_id,
      updated_at = now()
  where id = p_medication_order_id;

  insert into public.medication_order_audit_logs(
    medication_order_id, action, reason, actor_user_id
  )
  values(
    p_medication_order_id, 'reopened', p_reason, p_actor_user_id
  );

  return jsonb_build_object(
    'medication_order_id', p_medication_order_id,
    'status', 'draft'
  );
end;
$$;

revoke all on function public.pawu_reopen_medication_order(bigint,bigint,uuid,text)
from public;
grant execute on function public.pawu_reopen_medication_order(bigint,bigint,uuid,text)
to service_role;

alter table public.medication_orders enable row level security;
alter table public.medication_order_items enable row level security;
alter table public.medication_order_templates enable row level security;
alter table public.medication_order_template_items enable row level security;
alter table public.medication_order_audit_logs enable row level security;

drop policy if exists "medication orders participant read"
  on public.medication_orders;

create policy "medication orders participant read"
on public.medication_orders
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = medication_orders.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1
    from public.pets p
    where p.id = medication_orders.pet_id
      and p.user_id = auth.uid()
      and medication_orders.status = 'finalized'
      and medication_orders.guardian_visible = true
  )
);

drop policy if exists "medication order items participant read"
  on public.medication_order_items;

create policy "medication order items participant read"
on public.medication_order_items
for select
to authenticated
using (
  exists(
    select 1
    from public.medication_orders mo
    join public.pets p on p.id = mo.pet_id
    where mo.id = medication_order_items.medication_order_id
      and (
        exists(
          select 1
          from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = mo.hospital_id
            and hs.is_active = true
        )
        or (
          p.user_id = auth.uid()
          and mo.status = 'finalized'
          and mo.guardian_visible = true
        )
      )
  )
);

drop policy if exists "hospital members read medication templates"
  on public.medication_order_templates;

create policy "hospital members read medication templates"
on public.medication_order_templates
for select
to authenticated
using (
  exists(
    select 1
    from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = medication_order_templates.hospital_id
      and hs.is_active = true
  )
);

-- 템플릿 항목은 반드시 해당 병원 템플릿을 통해서만 조회합니다.
drop policy if exists "hospital members read medication template items"
  on public.medication_order_template_items;

create policy "hospital members read medication template items"
on public.medication_order_template_items
for select
to authenticated
using (
  exists(
    select 1
    from public.medication_order_templates mot
    join public.hospital_staff hs
      on hs.hospital_id = mot.hospital_id
    where mot.id = medication_order_template_items.template_id
      and hs.user_id = auth.uid()
      and hs.is_active = true
  )
);

-- V6.4.2 설정 테이블이 존재할 때만 메뉴 기본값을 추가합니다.
do $$
begin
  if to_regclass('public.hospital_feature_settings') is not null then
    insert into public.hospital_feature_settings(
      hospital_id, feature_key, is_enabled, sort_order
    )
    select h.id, 'prescriptions', true, 55
    from public.hospitals h
    on conflict(hospital_id, feature_key) do nothing;
  end if;
end;
$$;

commit;

-- 실행 후 검증용 조회
select
  to_regclass('public.medication_orders') as medication_orders,
  to_regclass('public.medication_order_items') as medication_order_items,
  to_regclass('public.medication_order_templates') as medication_order_templates,
  to_regclass('public.medication_order_audit_logs') as medication_order_audit_logs;
