-- PAWU INVENTORY V6
-- V5 적용 후 실행하세요.
-- 기존 DB 구조가 일부 달라도 재실행할 수 있도록 IF NOT EXISTS 중심으로 구성했습니다.

alter table if exists public.hospital_staff
  add column if not exists permissions jsonb not null default '{}'::jsonb,
  add column if not exists is_active boolean not null default true;

update public.hospital_staff
set permissions = coalesce(permissions, '{}'::jsonb) ||
  case
    when coalesce(role, '') = 'owner' then
      '{"view_inventory":true,"manage_inventory":true,"adjust_inventory":true}'::jsonb
    when coalesce(role, '') in ('veterinarian','nurse','receptionist') then
      '{"view_inventory":true,"manage_inventory":false,"adjust_inventory":true}'::jsonb
    else
      '{"view_inventory":true,"manage_inventory":false,"adjust_inventory":false}'::jsonb
  end
where permissions is not null;

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  name text not null,
  category text not null,
  unit text not null,
  sku text,
  barcode text,
  manufacturer text,
  supplier_name text,
  storage_location text,
  current_quantity numeric(14,4) not null default 0 check (current_quantity >= 0),
  minimum_quantity numeric(14,4) not null default 0 check (minimum_quantity >= 0),
  average_unit_cost numeric(14,2) not null default 0 check (average_unit_cost >= 0),
  management_type text not null default 'general'
    check (management_type in ('general','expiry','lot','strict')),
  requires_reason boolean not null default false,
  is_active boolean not null default true,
  memo text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(hospital_id, name)
);

create index if not exists inventory_items_hospital_category_idx
  on public.inventory_items(hospital_id, category, is_active);

create index if not exists inventory_items_hospital_stock_idx
  on public.inventory_items(hospital_id, current_quantity, minimum_quantity);

create table if not exists public.inventory_lots (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
  lot_number text not null,
  expires_on date,
  received_on date not null default current_date,
  received_quantity numeric(14,4) not null check (received_quantity > 0),
  remaining_quantity numeric(14,4) not null check (remaining_quantity >= 0),
  unit_cost numeric(14,2) check (unit_cost >= 0),
  supplier_name text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(inventory_item_id, lot_number)
);

create index if not exists inventory_lots_item_expiry_idx
  on public.inventory_lots(inventory_item_id, expires_on, remaining_quantity);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  lot_id bigint references public.inventory_lots(id) on delete set null,
  movement_type text not null
    check (movement_type in ('receive','use','waste','adjust','return','invoice_use','reversal')),
  quantity_change numeric(14,4) not null check (quantity_change <> 0),
  quantity_before numeric(14,4) not null,
  quantity_after numeric(14,4) not null check (quantity_after >= 0),
  unit_cost numeric(14,2),
  reason text,
  reference_type text,
  reference_id bigint,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_item_created_idx
  on public.inventory_movements(inventory_item_id, created_at desc);

create index if not exists inventory_movements_reference_idx
  on public.inventory_movements(reference_type, reference_id);

create table if not exists public.service_item_inventory_usage (
  id bigint generated by default as identity primary key,
  hospital_service_item_id bigint not null references public.hospital_service_items(id) on delete cascade,
  inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
  default_quantity numeric(14,4) not null check (default_quantity > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(hospital_service_item_id, inventory_item_id)
);

create index if not exists service_item_inventory_usage_service_idx
  on public.service_item_inventory_usage(hospital_service_item_id);

create or replace function public.pawu_apply_inventory_movement(
  p_hospital_id bigint,
  p_inventory_item_id bigint,
  p_movement_type text,
  p_quantity_change numeric,
  p_reason text default null,
  p_reference_type text default null,
  p_reference_id bigint default null,
  p_lot_id bigint default null,
  p_unit_cost numeric default null,
  p_actor_user_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before numeric(14,4);
  v_after numeric(14,4);
  v_old_cost numeric(14,2);
  v_new_cost numeric(14,2);
begin
  if p_quantity_change = 0 then
    raise exception '수량 변화는 0일 수 없습니다.';
  end if;

  select current_quantity, average_unit_cost
  into v_before, v_old_cost
  from public.inventory_items
  where id = p_inventory_item_id
    and hospital_id = p_hospital_id
    and is_active = true
  for update;

  if not found then
    raise exception '재고 품목을 찾지 못했습니다.';
  end if;

  v_after := v_before + p_quantity_change;
  if v_after < 0 then
    raise exception '재고가 부족합니다. 현재 재고: %', v_before;
  end if;

  v_new_cost := v_old_cost;
  if p_quantity_change > 0 and p_unit_cost is not null then
    if v_before + p_quantity_change > 0 then
      v_new_cost :=
        round(((v_before * v_old_cost) + (p_quantity_change * p_unit_cost)) /
        (v_before + p_quantity_change), 2);
    end if;
  end if;

  update public.inventory_items
  set current_quantity = v_after,
      average_unit_cost = v_new_cost,
      updated_at = now()
  where id = p_inventory_item_id;

  insert into public.inventory_movements(
    inventory_item_id, lot_id, movement_type, quantity_change,
    quantity_before, quantity_after, unit_cost, reason,
    reference_type, reference_id, created_by
  )
  values(
    p_inventory_item_id, p_lot_id, p_movement_type, p_quantity_change,
    v_before, v_after, p_unit_cost, p_reason,
    p_reference_type, p_reference_id, p_actor_user_id
  );

  return jsonb_build_object(
    'inventory_item_id', p_inventory_item_id,
    'quantity_before', v_before,
    'quantity_after', v_after
  );
end;
$$;

alter table public.inventory_items enable row level security;
alter table public.inventory_lots enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.service_item_inventory_usage enable row level security;

drop policy if exists "hospital members read inventory items" on public.inventory_items;
create policy "hospital members read inventory items"
on public.inventory_items for select to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = inventory_items.hospital_id
      and hs.is_active = true
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = inventory_items.hospital_id
  )
);

drop policy if exists "hospital managers manage inventory items" on public.inventory_items;
create policy "hospital managers manage inventory items"
on public.inventory_items for all to authenticated
using (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = inventory_items.hospital_id
      and hs.is_active = true
      and (
        coalesce(hs.role, '') = 'owner'
        or coalesce((hs.permissions->>'manage_inventory')::boolean, false)
      )
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = inventory_items.hospital_id
  )
)
with check (
  exists(
    select 1 from public.hospital_staff hs
    where hs.user_id = auth.uid()
      and hs.hospital_id = inventory_items.hospital_id
      and hs.is_active = true
      and (
        coalesce(hs.role, '') = 'owner'
        or coalesce((hs.permissions->>'manage_inventory')::boolean, false)
      )
  )
  or exists(
    select 1 from public.hospital_admins ha
    where ha.user_id = auth.uid()
      and ha.hospital_id = inventory_items.hospital_id
  )
);

drop policy if exists "hospital members read inventory lots" on public.inventory_lots;
create policy "hospital members read inventory lots"
on public.inventory_lots for select to authenticated
using (
  exists(
    select 1 from public.inventory_items i
    where i.id = inventory_lots.inventory_item_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = i.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = i.hospital_id
        )
      )
  )
);

drop policy if exists "hospital members read inventory movements" on public.inventory_movements;
create policy "hospital members read inventory movements"
on public.inventory_movements for select to authenticated
using (
  exists(
    select 1 from public.inventory_items i
    where i.id = inventory_movements.inventory_item_id
      and (
        exists(
          select 1 from public.hospital_staff hs
          where hs.user_id = auth.uid()
            and hs.hospital_id = i.hospital_id
            and hs.is_active = true
        )
        or exists(
          select 1 from public.hospital_admins ha
          where ha.user_id = auth.uid()
            and ha.hospital_id = i.hospital_id
        )
      )
  )
);

-- 중요:
-- 재고 수량 변경은 클라이언트에서 직접 UPDATE 하지 않고
-- 서버 API가 pawu_apply_inventory_movement RPC를 호출해 원자적으로 처리합니다.
-- V6에서는 진료 항목과 예상 재고 사용량을 연결할 테이블까지 준비합니다.
-- 실제 자동 차감은 진료 완료 확정 시 직원이 사용량을 검토한 뒤 실행하도록 V6.1에서 연결합니다.
