-- PAWU PLATFORM V7.0.0
-- 상용화 기반: 감사로그, 권한 프리셋, 중복실행 방지, 내보내기 기록

create table if not exists public.hospital_audit_logs_v7 (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  action text not null,
  resource_type text not null,
  resource_id text,
  severity text not null default 'info' check (severity in ('info','warning','critical')),
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists hospital_audit_logs_v7_hospital_created_idx on public.hospital_audit_logs_v7(hospital_id, created_at desc);
create index if not exists hospital_audit_logs_v7_action_idx on public.hospital_audit_logs_v7(hospital_id, action, created_at desc);
create index if not exists hospital_audit_logs_v7_severity_idx on public.hospital_audit_logs_v7(hospital_id, severity, created_at desc);
alter table public.hospital_audit_logs_v7 enable row level security;
drop policy if exists "hospital audit v7 read" on public.hospital_audit_logs_v7;
create policy "hospital audit v7 read" on public.hospital_audit_logs_v7 for select to authenticated using (
  exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=hospital_audit_logs_v7.hospital_id)
  or exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=hospital_audit_logs_v7.hospital_id and s.is_active=true and (s.role='owner' or coalesce((s.permissions->>'view_audit_logs')::boolean,false)))
);

create table if not exists public.hospital_role_presets_v7 (
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  role_key text not null,
  role_name text not null,
  permissions jsonb not null default '{}'::jsonb,
  is_system boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key(hospital_id, role_key)
);
alter table public.hospital_role_presets_v7 enable row level security;
drop policy if exists "role presets v7 read" on public.hospital_role_presets_v7;
create policy "role presets v7 read" on public.hospital_role_presets_v7 for select to authenticated using (
  exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=hospital_role_presets_v7.hospital_id)
  or exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=hospital_role_presets_v7.hospital_id and s.is_active=true)
);

create table if not exists public.hospital_idempotency_keys_v7 (
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  operation_key text not null,
  request_hash text,
  response_payload jsonb,
  status text not null default 'processing' check(status in ('processing','completed','failed')),
  expires_at timestamptz not null default (now()+interval '24 hours'),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key(hospital_id, operation_key)
);
create index if not exists hospital_idempotency_keys_v7_expiry_idx on public.hospital_idempotency_keys_v7(expires_at);
alter table public.hospital_idempotency_keys_v7 enable row level security;

create table if not exists public.hospital_data_exports_v7 (
  id bigint generated by default as identity primary key,
  hospital_id bigint not null references public.hospitals(id) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  export_type text not null default 'operational_json',
  record_count integer not null default 0,
  status text not null default 'completed' check(status in ('processing','completed','failed')),
  created_at timestamptz not null default now()
);
create index if not exists hospital_data_exports_v7_idx on public.hospital_data_exports_v7(hospital_id,created_at desc);
alter table public.hospital_data_exports_v7 enable row level security;
drop policy if exists "hospital exports v7 read" on public.hospital_data_exports_v7;
create policy "hospital exports v7 read" on public.hospital_data_exports_v7 for select to authenticated using (
  exists(select 1 from public.hospital_admins a where a.user_id=auth.uid() and a.hospital_id=hospital_data_exports_v7.hospital_id)
  or exists(select 1 from public.hospital_staff s where s.user_id=auth.uid() and s.hospital_id=hospital_data_exports_v7.hospital_id and s.is_active=true and (s.role='owner' or coalesce((s.permissions->>'export_data')::boolean,false)))
);

-- 기존 역할에 V7 기본 권한 보강
update public.hospital_staff set permissions=coalesce(permissions,'{}'::jsonb) ||
case
 when role='owner' then '{"view_dashboard":true,"view_patients":true,"write_medical_records":true,"manage_prescriptions":true,"manage_dispensing":true,"manage_billing":true,"manage_inventory":true,"manage_inpatient":true,"manage_surgery":true,"manage_staff":true,"view_audit_logs":true,"export_data":true,"manage_security":true}'::jsonb
 when role='veterinarian' then '{"view_dashboard":true,"view_patients":true,"write_medical_records":true,"manage_prescriptions":true,"manage_inpatient":true,"manage_surgery":true}'::jsonb
 when role='nurse' then '{"view_dashboard":true,"view_patients":true,"manage_dispensing":true,"manage_inventory":true,"manage_inpatient":true}'::jsonb
 when role='receptionist' then '{"view_dashboard":true,"view_patients":true,"manage_billing":true}'::jsonb
 else '{"view_dashboard":true,"view_patients":true}'::jsonb end;

insert into public.hospital_audit_logs_v7(hospital_id,actor_role,action,resource_type,severity,summary,metadata)
select id,'system','platform.v7_migrated','hospital','info','PAWU Platform V7.0.0 마이그레이션 완료','{"version":"7.0.0"}'::jsonb
from public.hospitals
where not exists(select 1 from public.hospital_audit_logs_v7 l where l.hospital_id=hospitals.id and l.action='platform.v7_migrated');
