-- PAWU V8.2.0-A
-- 입원·수술 시스템 DB 기반
-- 기존 데이터 삭제 없음

begin;

-- ---------------------------------------------------------
-- 1. 입원 기록
-- ---------------------------------------------------------
create table if not exists public.hospitalizations (
  id bigint generated by default as identity primary key,

  hospital_id bigint not null
    references public.hospitals(id)
    on delete cascade,

  medical_record_id bigint
    references public.medical_records(id)
    on delete set null,

  hospital_patient_id bigint not null
    references public.hospital_patients(id)
    on delete cascade,

  reservation_id bigint
    references public.reservations(id)
    on delete set null,

  status text not null default 'admitted'
    check (
      status in (
        'planned',
        'admitted',
        'in_treatment',
        'recovering',
        'ready_for_discharge',
        'discharged',
        'cancelled'
      )
    ),

  admission_reason text not null,
  ward_name text,
  cage_number text,

  admitted_at timestamptz not null default now(),
  expected_discharge_at timestamptz,
  discharged_at timestamptz,

  attending_vet_user_id uuid
    references auth.users(id)
    on delete set null,

  assigned_staff_user_id uuid
    references auth.users(id)
    on delete set null,

  risk_level text not null default 'standard'
    check (
      risk_level in (
        'standard',
        'watch',
        'high',
        'critical'
      )
    ),

  isolation_required boolean not null default false,
  fasting_required boolean not null default false,

  internal_note text,
  guardian_summary text,
  is_guardian_visible boolean not null default false,

  created_by uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hospitalizations_hospital_status_idx
  on public.hospitalizations(
    hospital_id,
    status,
    admitted_at desc
  );

create index if not exists hospitalizations_patient_idx
  on public.hospitalizations(
    hospital_patient_id,
    admitted_at desc
  );

create index if not exists hospitalizations_record_idx
  on public.hospitalizations(
    medical_record_id,
    admitted_at desc
  );


-- ---------------------------------------------------------
-- 2. 입원 이벤트 및 간호기록
-- ---------------------------------------------------------
create table if not exists public.hospitalization_events (
  id bigint generated by default as identity primary key,

  hospitalization_id bigint not null
    references public.hospitalizations(id)
    on delete cascade,

  event_type text not null
    check (
      event_type in (
        'vital',
        'meal',
        'water',
        'medication',
        'injection',
        'iv',
        'urination',
        'defecation',
        'vomiting',
        'pain',
        'wound',
        'mobility',
        'behavior',
        'procedure',
        'round',
        'guardian_update',
        'other'
      )
    ),

  occurred_at timestamptz not null default now(),

  title text not null,
  content text,

  temperature_c numeric,
  heart_rate_bpm integer,
  respiratory_rate_bpm integer,
  systolic_bp integer,
  diastolic_bp integer,
  weight_kg numeric,
  pain_score integer
    check (
      pain_score is null
      or pain_score between 0 and 10
    ),

  amount_value numeric,
  amount_unit text,

  status_value text,
  abnormal_flag boolean not null default false,
  requires_follow_up boolean not null default false,

  recorded_by uuid
    references auth.users(id)
    on delete set null,

  is_guardian_visible boolean not null default false,
  guardian_message text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hospitalization_events_timeline_idx
  on public.hospitalization_events(
    hospitalization_id,
    occurred_at desc
  );

create index if not exists hospitalization_events_followup_idx
  on public.hospitalization_events(
    hospitalization_id,
    requires_follow_up,
    occurred_at desc
  );


-- ---------------------------------------------------------
-- 3. 입원 치료 계획
-- ---------------------------------------------------------
create table if not exists public.hospitalization_care_plans (
  id bigint generated by default as identity primary key,

  hospitalization_id bigint not null
    references public.hospitalizations(id)
    on delete cascade,

  plan_type text not null
    check (
      plan_type in (
        'medication',
        'fluid',
        'feeding',
        'monitoring',
        'wound_care',
        'exercise',
        'test',
        'procedure',
        'other'
      )
    ),

  title text not null,
  instruction text,

  start_at timestamptz not null default now(),
  end_at timestamptz,

  frequency text,
  scheduled_times jsonb not null default '[]'::jsonb,

  status text not null default 'active'
    check (
      status in (
        'planned',
        'active',
        'paused',
        'completed',
        'cancelled'
      )
    ),

  created_by uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hospitalization_care_plans_active_idx
  on public.hospitalization_care_plans(
    hospitalization_id,
    status,
    start_at
  );


-- ---------------------------------------------------------
-- 4. 수술 기록
-- ---------------------------------------------------------
create table if not exists public.surgeries (
  id bigint generated by default as identity primary key,

  hospital_id bigint not null
    references public.hospitals(id)
    on delete cascade,

  medical_record_id bigint
    references public.medical_records(id)
    on delete set null,

  hospital_patient_id bigint not null
    references public.hospital_patients(id)
    on delete cascade,

  reservation_id bigint
    references public.reservations(id)
    on delete set null,

  hospitalization_id bigint
    references public.hospitalizations(id)
    on delete set null,

  surgery_name text not null,
  surgery_code text,
  body_site text,

  status text not null default 'scheduled'
    check (
      status in (
        'scheduled',
        'preparing',
        'anesthesia',
        'in_surgery',
        'recovery',
        'completed',
        'cancelled'
      )
    ),

  urgency text not null default 'elective'
    check (
      urgency in (
        'elective',
        'urgent',
        'emergency'
      )
    ),

  scheduled_start_at timestamptz,
  anesthesia_started_at timestamptz,
  surgery_started_at timestamptz,
  surgery_ended_at timestamptz,
  recovery_started_at timestamptz,
  completed_at timestamptz,

  primary_surgeon_user_id uuid
    references auth.users(id)
    on delete set null,

  anesthetist_user_id uuid
    references auth.users(id)
    on delete set null,

  anesthesia_type text,
  anesthesia_note text,

  preoperative_diagnosis text,
  postoperative_diagnosis text,
  procedure_note text,
  findings text,
  complications text,
  recovery_status text,

  estimated_blood_loss_ml numeric,
  specimen_collected boolean not null default false,

  internal_note text,
  guardian_summary text,
  is_guardian_visible boolean not null default false,

  created_by uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists surgeries_hospital_status_idx
  on public.surgeries(
    hospital_id,
    status,
    scheduled_start_at
  );

create index if not exists surgeries_patient_idx
  on public.surgeries(
    hospital_patient_id,
    created_at desc
  );

create index if not exists surgeries_hospitalization_idx
  on public.surgeries(
    hospitalization_id,
    created_at desc
  );


-- ---------------------------------------------------------
-- 5. 수술 참여자
-- ---------------------------------------------------------
create table if not exists public.surgery_team_members (
  id bigint generated by default as identity primary key,

  surgery_id bigint not null
    references public.surgeries(id)
    on delete cascade,

  user_id uuid
    references auth.users(id)
    on delete set null,

  member_name text,
  role text not null
    check (
      role in (
        'primary_surgeon',
        'assistant_surgeon',
        'anesthetist',
        'nurse',
        'technician',
        'observer',
        'other'
      )
    ),

  note text,
  created_at timestamptz not null default now()
);

create index if not exists surgery_team_members_surgery_idx
  on public.surgery_team_members(
    surgery_id,
    role
  );


-- ---------------------------------------------------------
-- 6. 수술 체크리스트
-- ---------------------------------------------------------
create table if not exists public.surgery_checklist_items (
  id bigint generated by default as identity primary key,

  surgery_id bigint not null
    references public.surgeries(id)
    on delete cascade,

  phase text not null
    check (
      phase in (
        'pre_op',
        'before_anesthesia',
        'before_incision',
        'before_closure',
        'recovery'
      )
    ),

  item_key text,
  label text not null,
  is_checked boolean not null default false,

  checked_at timestamptz,
  checked_by uuid
    references auth.users(id)
    on delete set null,

  note text,
  sort_order integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists surgery_checklist_items_phase_idx
  on public.surgery_checklist_items(
    surgery_id,
    phase,
    sort_order
  );


-- ---------------------------------------------------------
-- 7. 수술 중 활력징후
-- ---------------------------------------------------------
create table if not exists public.surgery_vital_signs (
  id bigint generated by default as identity primary key,

  surgery_id bigint not null
    references public.surgeries(id)
    on delete cascade,

  measured_at timestamptz not null default now(),

  temperature_c numeric,
  heart_rate_bpm integer,
  respiratory_rate_bpm integer,
  spo2_percent numeric,
  systolic_bp integer,
  diastolic_bp integer,
  map_bp integer,
  etco2_mmhg numeric,

  anesthesia_depth text,
  note text,
  abnormal_flag boolean not null default false,

  recorded_by uuid
    references auth.users(id)
    on delete set null,

  created_at timestamptz not null default now()
);

create index if not exists surgery_vital_signs_timeline_idx
  on public.surgery_vital_signs(
    surgery_id,
    measured_at
  );


-- ---------------------------------------------------------
-- 8. 퇴원 요약
-- ---------------------------------------------------------
create table if not exists public.hospitalization_discharge_summaries (
  id bigint generated by default as identity primary key,

  hospitalization_id bigint not null unique
    references public.hospitalizations(id)
    on delete cascade,

  discharge_condition text,
  treatment_summary text,
  medication_summary text,
  feeding_instruction text,
  activity_instruction text,
  wound_care_instruction text,
  warning_signs text,
  follow_up_instruction text,
  next_visit_at timestamptz,

  ai_draft text,
  ai_generated_at timestamptz,
  finalized_by uuid
    references auth.users(id)
    on delete set null,
  finalized_at timestamptz,

  is_guardian_visible boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ---------------------------------------------------------
-- 9. 감사 로그
-- ---------------------------------------------------------
create table if not exists public.inpatient_surgery_audit_logs (
  id bigint generated by default as identity primary key,

  hospital_id bigint not null
    references public.hospitals(id)
    on delete cascade,

  hospitalization_id bigint
    references public.hospitalizations(id)
    on delete cascade,

  surgery_id bigint
    references public.surgeries(id)
    on delete cascade,

  actor_user_id uuid
    references auth.users(id)
    on delete set null,

  action text not null,
  before_data jsonb,
  after_data jsonb,

  created_at timestamptz not null default now()
);

create index if not exists inpatient_surgery_audit_logs_hospitalization_idx
  on public.inpatient_surgery_audit_logs(
    hospitalization_id,
    created_at desc
  );

create index if not exists inpatient_surgery_audit_logs_surgery_idx
  on public.inpatient_surgery_audit_logs(
    surgery_id,
    created_at desc
  );


-- ---------------------------------------------------------
-- 10. updated_at 자동 갱신
-- ---------------------------------------------------------
create or replace function public.pawu_touch_inpatient_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists hospitalizations_touch_updated_at
  on public.hospitalizations;

create trigger hospitalizations_touch_updated_at
before update on public.hospitalizations
for each row
execute function public.pawu_touch_inpatient_updated_at();

drop trigger if exists hospitalization_events_touch_updated_at
  on public.hospitalization_events;

create trigger hospitalization_events_touch_updated_at
before update on public.hospitalization_events
for each row
execute function public.pawu_touch_inpatient_updated_at();

drop trigger if exists hospitalization_care_plans_touch_updated_at
  on public.hospitalization_care_plans;

create trigger hospitalization_care_plans_touch_updated_at
before update on public.hospitalization_care_plans
for each row
execute function public.pawu_touch_inpatient_updated_at();

drop trigger if exists surgeries_touch_updated_at
  on public.surgeries;

create trigger surgeries_touch_updated_at
before update on public.surgeries
for each row
execute function public.pawu_touch_inpatient_updated_at();

drop trigger if exists surgery_checklist_items_touch_updated_at
  on public.surgery_checklist_items;

create trigger surgery_checklist_items_touch_updated_at
before update on public.surgery_checklist_items
for each row
execute function public.pawu_touch_inpatient_updated_at();

drop trigger if exists hospitalization_discharge_summaries_touch_updated_at
  on public.hospitalization_discharge_summaries;

create trigger hospitalization_discharge_summaries_touch_updated_at
before update on public.hospitalization_discharge_summaries
for each row
execute function public.pawu_touch_inpatient_updated_at();


-- ---------------------------------------------------------
-- 11. 기본 수술 체크리스트 자동 생성
-- ---------------------------------------------------------
create or replace function public.pawu_create_default_surgery_checklist()
returns trigger
language plpgsql
as $$
begin
  insert into public.surgery_checklist_items (
    surgery_id,
    phase,
    item_key,
    label,
    sort_order
  )
  values
    (new.id, 'pre_op', 'identity', '환자 신원과 수술 부위 확인', 10),
    (new.id, 'pre_op', 'consent', '보호자 수술·마취 동의 확인', 20),
    (new.id, 'pre_op', 'fasting', '금식 여부 확인', 30),
    (new.id, 'before_anesthesia', 'airway', '기도 및 응급 장비 확인', 10),
    (new.id, 'before_anesthesia', 'drug', '마취약과 용량 확인', 20),
    (new.id, 'before_incision', 'team', '집도의와 참여자 확인', 10),
    (new.id, 'before_incision', 'site', '수술 부위 최종 확인', 20),
    (new.id, 'before_closure', 'count', '기구·거즈 수량 확인', 10),
    (new.id, 'before_closure', 'specimen', '검체 라벨 및 의뢰 확인', 20),
    (new.id, 'recovery', 'vital', '회복기 활력징후 확인', 10),
    (new.id, 'recovery', 'pain', '통증 조절 계획 확인', 20),
    (new.id, 'recovery', 'guardian', '보호자 안내사항 준비', 30);

  return new;
end;
$$;

drop trigger if exists surgeries_create_default_checklist
  on public.surgeries;

create trigger surgeries_create_default_checklist
after insert on public.surgeries
for each row
execute function public.pawu_create_default_surgery_checklist();


-- ---------------------------------------------------------
-- 12. RLS
-- 병원 UI는 서버 API + service role을 사용
-- 보호자 공개 정책은 V8.2.0-D에서 추가
-- ---------------------------------------------------------
alter table public.hospitalizations enable row level security;
alter table public.hospitalization_events enable row level security;
alter table public.hospitalization_care_plans enable row level security;
alter table public.surgeries enable row level security;
alter table public.surgery_team_members enable row level security;
alter table public.surgery_checklist_items enable row level security;
alter table public.surgery_vital_signs enable row level security;
alter table public.hospitalization_discharge_summaries enable row level security;
alter table public.inpatient_surgery_audit_logs enable row level security;

commit;
