"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../../lib/supabase";
type Service={id:number;name:string;category:string;default_price:number;is_favorite:boolean;is_active:boolean};type Line={key:string;serviceItemId:number|null;name:string;unitPrice:number;quantity:number;discountAmount:number;additionalAmount:number;note:string};
export default function NewInvoicePage(){const[services,setServices]=useState<Service[]>([]);const[lines,setLines]=useState<Line[]>([]);const[petId,setPetId]=useState("");const[guardianUserId,setGuardianUserId]=useState("");const[discount,setDiscount]=useState(0);const[memo,setMemo]=useState("");const[message,setMessage]=useState("");const[invoiceId,setInvoiceId]=useState<number|null>(null);
async function token(){const{data}=await supabase.auth.getSession();return data.session?.access_token??""}useEffect(()=>{void(async()=>{const t=await token();if(!t)return;const r=await fetch("/api/hospital/billing/catalog",{headers:{authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok)setServices((j.items??[]).filter((v:Service)=>v.is_active))})()},[]);
function add(s:Service){setLines(v=>[...v,{key:`${s.id}-${Date.now()}`,serviceItemId:s.id,name:s.name,unitPrice:s.default_price,quantity:1,discountAmount:0,additionalAmount:0,note:""}])}function patch(key:string,p:Partial<Line>){setLines(v=>v.map(x=>x.key===key?{...x,...p}:x))}const subtotal=useMemo(()=>lines.reduce((sum,x)=>sum+Math.max(0,x.unitPrice*x.quantity-x.discountAmount+x.additionalAmount),0),[lines]);const total=Math.max(0,subtotal-discount);
async function save(){const t=await token();const r=await fetch("/api/hospital/billing/invoices",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({petId:Number(petId),guardianUserId:guardianUserId||null,items:lines,invoiceDiscount:discount,memo})});const j=await r.json();setMessage(r.ok?`청구서 저장 완료: ${Number(j.totalAmount).toLocaleString("ko-KR")}원`:j.message);if(r.ok)setInvoiceId(j.invoiceId)}async function requestPayment(){if(!invoiceId)return;const t=await token();const r=await fetch("/api/hospital/billing/invoices",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({invoiceId,action:"request_payment"})});const j=await r.json();setMessage(r.ok?"보호자에게 결제 요청을 보냈습니다.":j.message)}
return <main className="min-h-screen bg-slate-50 px-5 py-8 text-black"><div className="mx-auto max-w-6xl"><div className="flex justify-between"><Link href="/hospital-admin/v5" className="rounded-xl border bg-white px-4 py-2">← V5</Link><Link href="/hospital-admin/billing/catalog" className="rounded-xl border bg-white px-4 py-2">항목 설정</Link></div><h1 className="mt-8 text-3xl font-black">간편 청구서</h1>{message&&<p className="mt-4 rounded-xl bg-white p-3">{message}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-5"><h2 className="text-xl font-black">항목 선택</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{services.map(s=><button key={s.id} onClick={()=>add(s)} className="rounded-2xl border p-4 text-left"><strong>{s.is_favorite?"★ ":""}{s.name}</strong><p className="mt-2 text-sm">{s.default_price.toLocaleString("ko-KR")}원</p></button>)}</div></section><section className="rounded-3xl border bg-white p-5"><div className="grid gap-3 sm:grid-cols-2"><input value={petId} onChange={e=>setPetId(e.target.value.replace(/[^0-9]/g,""))} placeholder="반려동물 ID" className="rounded-xl border p-3"/><input value={guardianUserId} onChange={e=>setGuardianUserId(e.target.value)} placeholder="보호자 UUID (선택)" className="rounded-xl border p-3"/></div><div className="mt-4 space-y-3">{lines.map(x=><article key={x.key} className="rounded-2xl border p-4"><div className="flex gap-2"><input value={x.name} onChange={e=>patch(x.key,{name:e.target.value})} className="min-w-0 flex-1 rounded-lg border p-2 font-bold"/><button onClick={()=>setLines(v=>v.filter(y=>y.key!==x.key))} className="rounded-lg border px-3">삭제</button></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Num label="단가" value={x.unitPrice} set={v=>patch(x.key,{unitPrice:v})}/><Num label="수량" value={x.quantity} set={v=>patch(x.key,{quantity:Math.max(1,v)})}/><Num label="할인" value={x.discountAmount} set={v=>patch(x.key,{discountAmount:v})}/><Num label="추가" value={x.additionalAmount} set={v=>patch(x.key,{additionalAmount:v})}/></div></article>)}</div><label className="mt-4 block text-sm font-bold">전체 할인<input type="number" min={0} value={discount} onChange={e=>setDiscount(Math.max(0,Number(e.target.value)))} className="mt-1 w-full rounded-xl border p-3"/></label><textarea value={memo} onChange={e=>setMemo(e.target.value)} placeholder="청구 메모" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-4 rounded-2xl bg-black p-5 text-white"><p className="flex justify-between"><span>최종 금액</span><strong className="text-2xl">{total.toLocaleString("ko-KR")}원</strong></p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>void save()} className="rounded-xl border border-black p-4 font-bold">청구서 저장</button><button disabled={!invoiceId} onClick={()=>void requestPayment()} className="rounded-xl bg-black p-4 font-bold text-white disabled:bg-gray-400">결제 요청</button></div></section></div></div></main>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="text-xs font-bold">{label}<input type="number" min={0} value={value} onChange={e=>set(Math.max(0,Number(e.target.value)))} className="mt-1 w-full rounded-lg border p-2"/></label>}
